### ISSUE TITLE
C# evaluation API handles evaluation for only one vector. 

### ISSUE THREAD

**Issue by snurkabill** [Microsoft/CNTK#1055]
Hello, 

I am experiencing huge performance issue during evaluating which is much longer than training. Using 
[this interface](https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CSEvalClient/ModelEvaluator.cs#L129) is very slow for batch evaluation, especially on GPUs. Would it be possible to extend API with: 
`public static List<List<float>> Evaluate(List<List<float>> inputs)` which would be evaluated on GPU  as a btach? 

this is my GPU usage while training and evaluation. You can see that training took as much time as evaluation but on much longer data (we are working with time series). Evaluation should be super quick, there must be some performance bottleneck and I believe it's the unfortunate API. 
![gpu_load](https://cloud.githubusercontent.com/assets/4818573/20392544/92dc123e-acd8-11e6-87e4-8067d692b91a.png)

Do you have any ideas, how to solve this issue? I need to use C# evaluation. I was thinking about evaluation on CPU but I am not sure about that.

**Comment by chrubiofa** [comment]
I have a 16 core machine which was acting in a similar way during the eval process. What I ended up doing is going into the task manager and setting the affinity to like 4 cores of the cpu. This greatly improved the process.

**Comment by zhouwangzw** [comment]
Thanks for sharing your experience. I would like to know more about your eval scenarios for further investigation. What is the input data type in your model, image, speech or text? What is most important performance criteria for your scenario, throughput or latency? From your description, it seems you care more about throughput of batch input.  
The current C# Eval interface is designed/optimized for running single batch on CPU. It is also optimized for low latency of single input. By default the [numCPUThreads](https://github.com/Microsoft/CNTK/wiki/Top-level-configurations#numcputhreads) is set to 1, which could be changed  during [Init()](https://github.com/Microsoft/CNTK/wiki/Managed-EvalDLL-API). Depending on matrix size of input data and model, set numCPUThreads to a higher value could be helpful to improve performance. 
We are now working on C# Eval interface based on the new CNTK library API, which provides better support for GPU device, and also for batch input. I am appreciated if you could give us more detailed requirements regarding evaluaton so that we can take them into consieration for the new C# eval interface.  We can also discuss them offline if you would prefer.

Thanks,
Zhou

**Comment by snurkabill** [comment]
Hi, 

Due to our purposes, we had to build framework on top of CNTK which uses CNTK binaries and CNTK models as black-box. So basically we have code which automatically generates cntkConfigFile and runs CNTK.exe on it, storing the latest model + trainingModelCheckpoint, evaluates resulting model on testing set on it's own using EvalWrapper lib., calculates properties atc. and decides if the another iteration is necessary. We store CNTK models into DB for each itertion and, if needed, run more evaluation with more properties to be calculated. 

The important thing is that we runs many training instances at the same time on few GPUs (so on one GPU there can be trained/evaluted for example 6 models at the same time).  I've noticed problem during working with CNTK model that if I train it on GPU 0, then I can't switch in next iteration to GPU 1. This could be possibly solved with -4 switch (so not sure if there is easy way to train model on GPU and evaluate it on CPU) . Anyway, evaluting more models at the same time on CPU using eval wrapper caused huge thread-context switching problems.

 We are now thinking about workaround: let CNTK run eval on all training/stopping/testing sets after training, dump outputs into file, read file from our C# code and calculate eval-properties on it's own as before. Writing and reading (output)data vectors  might be faster than the slow vector by vector evaluation which is performed now.

**Comment by snurkabill** [comment]
for the rest of your quetions: we have two use cases. In production, ofc, there will be one model per CPU so fast latency is great. but the testing offline is problem since for each iteration, we need to evaluate model on thousands of vectors and we can't do it in a batch-like manner using evalWrapper, in offline testing scenario, throughput is needed. 

It's great to hear that you are improving C# eval API, we use it a lot. 

I will gladly discuss more details with you offline.

**Comment by zhouwangzw** [comment]
I am wondering whether the new [CNTK Library ](https://github.com/microsoft/cntk/wiki/CNTK-Library-API) could be userful for your use case. It allows your application to easily control the training and eval process, and to select which device to run the training/eval. The CNTK Library is now available in Python and C++. The C# interface is currently being developed, with C# eval interfae available first, then the complete CNTK Library API in C#.
Thanks again for sharing your experience and feedback with us!

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)

**Comment by zhouwangzw** [comment]
The C# interface is already available which supports evaluation of batch inputs on GPU (indeed it supports batch, sequence, and batch of sequences with dense, one-hot vector, or sparse input). Pleaes refer to [the page](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Library-Evaluation-on-Windows) for details.

Thanks,

**Comment by zhouwangzw** [comment]
I am closing the issue. Please feel free to reopen it if needed.
