### ISSUE TITLE
How to use trained Fast R-CNN model on new images

### ISSUE THREAD

**Issue by tolisElectro** [Microsoft/CNTK#1093]
Hello 
I've trained a Fast R-CNN model with my own data according to the "Object Detection using Fast R CNN" https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN tutorial. I've used positive,negative and test images for training and evaluation.  
How would I go about using the now trained model on detecting objects in completely new images ? I it as straight-forward as using the "eval" BrainScript command and loading a .jpg file or more complicated than that ? Also, there seems that in CSEvalClient there is an Image Classification template (EvaluateImageClassificationModel) which outputs predicted class, but no Object Detection template .

**Comment by zhouwangzw** [comment]
regarding using CSEvalClient for Fast R-CNN, @pkranen posted a preliminary solution at the branch pkranen/csevalFastrcnn, specifically in Examples/Evaluation/CSEvalClient/Program.cs. Note that it does not yet contain the ROI generation from C# and also the image preprocessing should be done as in the ImageDeserializer, i.e. preserve aspect ration while scaling and pad the remaining pixels with 114 per channel. Please refer to #978 for details.

**Comment by tolisElectro** [comment]
Thank you for the immediate reply and info !

**Comment by zhouwangzw** [comment]
@tolisElectro I am closing the issue. Please feel free to reopen it if needed.

**Comment by harewei** [comment]
Just opening this because I have two questions regarding the same topic.
1.Did anyone actually get @pkranen 's branch for evaluation working?  I mean I can run the program, but everything is considered "ground" even by using the trained grocery 100 model as stated in the project comment.
2.Is there a way to evaluate new image just using the default python script?  I tried putting new image in "test" folder but during A2_RunCntk.py it requires me to create ROI and label them manually, otherwise it would just give an error, which makes the whole task pointless if I have to manually evaluate images first before the network can predict them.
