### ISSUE TITLE
Installation problem: "Fatal Errer during execution" - failed with exit code [1]

### ISSUE THREAD

**Issue by RasmusKaer** [Microsoft/CNTK#1150]
Hi all 

**Step 3 Run the Powershell installation script**
I have an issue when I get to the third step of the five operations: 

![prob cntk](https://cloud.githubusercontent.com/assets/21052826/21014107/efd1b4a0-bd5c-11e6-8214-d602377fddce.JPG)

The installation cancels short after with the message of "Fatal Error during script execution!" - failed with exit code [1]

Anyone who knows how to get around this? I tried to uninstall anaconda, and re-run, but no success.

Thanks in advance

Rasmus

**Comment by fcivardi** [comment]
Hi Rasmus, 
do you get the same error I get here?
https://github.com/Microsoft/CNTK/issues/1146

**Comment by RasmusKaer** [comment]
I get the exact same!

**Comment by fcivardi** [comment]
I deleted the old local, restarted from scratch and now it goes on without error

**Comment by RasmusKaer** [comment]
Fcivardi, I uninstalled python and anaconda and tried to re-install cntk, but got the same error again ??? 

![image](https://cloud.githubusercontent.com/assets/21052826/21094835/105e8a50-c059-11e6-831c-36a1e41f8238.png)

**Comment by fcivardi** [comment]
Rasmus, 
try onebitbrain's solution at that link:
https://github.com/Microsoft/CNTK/issues/1146L
Look at the command that you see in the error message: 
start-process evn create etc.
and give this command at the cmd prompt:
conda env create --file .....copying exactly  what you see above between ' ',   with conda instead of  start-process.

Francesco

**Comment by eldakms** [comment]
Please try to repro on the latest master/v2. Feel free to reopen if this is still relevant. Thanks!
