### ISSUE TITLE
undefined reference to `MPI_Iallreduce'

### ISSUE THREAD

**Issue by yazdanbakhsh** [Microsoft/CNTK#1157]
Hi,

I am trying to instal CNTK on my ubuntu machine. I followed all the instructions in the README but still getting the following error:

/home/yazdan/phd/tools/cntk-dev/cntk/build/release/lib/libcntklibrary-2.0.so: undefined reference to `MPI_Iallreduce'
/home/yazdan/phd/tools/cntk-dev/cntk/build/release/lib/libcntklibrary-2.0.so: undefined reference to `MPI_Iallgather'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/yazdan/phd/tools/cntk-dev/cntk/build/release/bin/cppevalv2client] Error 1
make[1]: *** Waiting for unfinished jobs....
/home/yazdan/phd/tools/cntk-dev/cntk/build/release/lib/libcntklibrary-2.0.so: undefined reference to `MPI_Iallreduce'
/home/yazdan/phd/tools/cntk-dev/cntk/build/release/lib/libcntklibrary-2.0.so: undefined reference to `MPI_Iallgather'

**Comment by junjieqian** [comment]
Please take a look at https://github.com/Microsoft/CNTK/issues/269, which is the same issue.

**Comment by achaiah** [comment]
@junjieqian  Unfortunately #269 doesn't solve anything. The pull request from jplu has not been accepted as far as I can tell so building from scratch remains an issue on Ubuntu 14.04.  No good solution/workaround has been proposed thus far.

**Comment by junjieqian** [comment]
The issue is caused by MPI version. The solution is that you may have to reinstall the correct version of MPI as instructed in Wiki.

**Comment by yazdanbakhsh** [comment]
Thanks everyone. As mentioned before, the issue can be resolved once you have the proper version of MPI. I removed all the other MPI library and re-install the MPI provided in the README file and now it works well.

**Comment by achaiah** [comment]
I understand that but the exact problem is that I'm running an automated tool (docker) to build CNTK [from here](https://github.com/Microsoft/CNTK/tree/master/Tools/docker).  That process fails even though the Dockerfile specifies the correct version and installs it.  Manually removing the old MPI version is not an option. Therefore, the best solution would be to include a --with-mpi flag per the pull request so that automated build tools may succeed.
