### ISSUE TITLE
corpus material CNTK_HandsOn_KDD2016.zip links dead

### ISSUE THREAD

**Issue by mkiernan** [Microsoft/CNTK#1159]
Does anyone happen to have a working download link to the image & voice corpus material referenced in the tutorials ?  The filename is CNTK_HandsOn_KDD2016.zip

Many thanks,
Mike

**Comment by sayanpa** [comment]
There are a bunch of tutorials located here: https://github.com/Microsoft/CNTK/tree/master/Tutorial

**Comment by mahilleb-msft** [comment]
Hey, the branch that had the .zip file on it was accidentally removed for some time. But it should be back since quite some time now under https://github.com/Microsoft/CNTK/blob/fseide/kdd/Tutorials/CNTK_HandsOn_KDD2016.zip.
Also see here for the moved entry page: https://docs.microsoft.com/en-us/cognitive-toolkit/KDD-2016-Tutorial

Closing, please re-open if there's still a problem with this.

Thanks, Mark
