### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/CNTK#1185]
Building solutions which will need inference on NVidia TX-1 and TK-1 platform, which are R.O.S. and Arm based.  Would be phenomenal to have ARM support, specifically if we can get it before spring semester, we can include in a robotics course at the local university.

**Comment by fmegen** [comment]
We have an experimental port running in CPU-only mode on an ARM64 board (Pine64, https://www.pine64.org/) on Ubuntu.
While the ARM64 code is available in master already, that specific configuration would require some manual tweaks for configuration (mainly because some libraries we use are not at their standard place, like Openblas).

We did not yet address Nvidia SoCs that use the TK-1 architecture with embedded CUDA compute units.

**Comment by IvanFarkas** [comment]
Forget TK-1. I'd love to do edge computing with **[Nvidia Jetson TX2](https://developer.nvidia.com/embedded/develop/hardware)**.

**Comment by jerremy1336** [comment]
@fmegen What kind of specific configuration is needed to support ARM64?

**Comment by JimSEOW** [comment]
@fmegen  Is it available to W10Mobile (ARM) UWP?

**Comment by eldakms** [comment]
UWP is not yet supported.
