### ISSUE TITLE
Q-Learning over TimePeriode?

### ISSUE THREAD

**Issue by snapo** [Microsoft/CNTK#125]
Is it possible with CNTK to create a Q-Learning (reinforcement learning) Model for example with weather Data from the past 5 Years where it sees only 24h and needs to do a prediction on that what will the weather be tomorrow?

I am asking because i did not find any information n Q-Value learning and rewarding it...

**Comment by dongyu888** [comment]
CNTK currently can relatively easily support simple Q learning where given the state (i.e., observation and history) estimate the probability of next best action. To support full reinforcement learning, e.g., estimating Q-value given both state and action, you will need to wait till Python binding is ready.

However, your problem is very similar to a simple supervised regression problem which can be solved using recurrent network (e.g., an LSTM which can be found in the examples folder). The error signal in your case is directly given.

**Comment by saasier1** [comment]
I'd like to follow up on this. I'm currently using Accord.NET's Machine Learning toolkit, specifically the Q-Learning functions. This is for gesture detection using a Kinect 2 in a robotic application. The robot watches the user and based on how they move we select an action and based on the action selected a reward is produced. 

Do you have any further insight on how to do this with CNTK? You mentioned wait until Python bindings are ready. Is this not possible in C# presently?

**Comment by mradmila** [comment]
We do not expose C# bindings currently, so you'd have to wrap this yourself to make it work. It will be much easier to do once we expose Python bindings.

**Comment by gowthamnatarajan** [comment]
When might the python bindings be exposed?

**Comment by frankseide** [comment]
Expected for end of August.

Could you explain more why you use RL? Wouldn't you know for each gesture what the correct label is? Then you should be able to just use an LSTM with a classifier on the last hidden state, or something like that.
