### ISSUE TITLE
CNTK-2.0.beta8.0 performs much worse than CNTK-2.0.beta6.0

### ISSUE THREAD

**Issue by svml** [Microsoft/CNTK#1307]
I am observing that CNTK-2.0.beta8.0 performs much worse than CNTK-2.0.beta6.0 in one of my trivial tests. For example, correlation factor between output and input dropped from 0.999 to 0.949 and the figure showing output vs input looks much worse. I used the same data file and the same BranScript file in the test - the only difference was the CNTK version used. In the test, I (essentially) try to predict the value of "cos(n+1)" using single hidden layer LSTM network with 6 nodes and using as input "cos(n-1)" and "cos(n)".

**Comment by sayanpa** [comment]
This could be due to some initialization differences or noise from run to run. Any possibility of sending us a small repro.

**Comment by avader906** [comment]
@sayanpa is there an example model in the repository that is being timed for performance from one release to another ? this is in order to setup regression testing.

**Comment by wolfma61** [comment]
My understanding is - The original question is about correlation between input and output 

We measure/verify accuracy performance constantly internally in our test suites, sometimes changes are to be expected due to bugs/changes, but with a repo we could investigate why we haven't seen this here.

for this we would need a repo as Sayan pointed out. 

to answer your question: We also measure performance constantly for our builds as well as other metrics. Performance might not always improve, especially in the beta-phase right now, but meeting and exceeding the performance of previous versions is a definite goal. The samples/tutorials in the repo are designed to show basic concepts of designing and building models, sometimes scarifying performance for clarity. Our internal suites for performance use larger datasets, but use standard models and training scenarios,

Wolfgang

**Comment by svml** [comment]
@sayanpa , @wolfma61 

I have sent the BrainScript file and the data file I used for the test to your Microsoft e-mails (I hope it is Ok, github does not allow to attach any files to posts). Please, let me know your conclusions.

**Comment by snurkabill** [comment]
Hello, 

I am experiencing similar problem. Our unit tests have started failing after beta 8 was deployed. I've noticed some tolerance lowering at CNTK unit tests: 
https://github.com/Microsoft/CNTK/commit/48650ad61ec181b0331833a8b7d26a0401e50e3c
https://github.com/Microsoft/CNTK/commit/1e67e8cd1307d760b3a8be7716b3b3059df80c8b
https://github.com/Microsoft/CNTK/commit/35356ad47ef956fb0b21f3709b24de59e1596b36

is it possible that lowering test tolerance is somehow connected to this issue?

**Comment by sayanpa** [comment]
We are investigating the differences. A repro was provided by svml. Could you please provide us a small test if possible.

**Comment by sayanpa** [comment]
We were able to trace back the changes. Looks like there was a breaking change in Beta 7 that was documented in the release notes. Apologize for the inconvenience. You may need to change your unit tests appropriately to reflect this change.

https://github.com/Microsoft/CNTK/wiki/CNTK_2_0_beta_7_Release_Notes

Specifically:
Random number generator and distributions were updated at many places to be the same across supported platforms (Linux and Windows) 

Backward compatibility note: training (in particular initialization) may not be exactly reproducible with respect to the previous versions
