### ISSUE TITLE
ImportError: No module named 'fastRCNN.utils3_win64.cython_bbox'

### ISSUE THREAD

**Issue by Abimahesh** [Microsoft/CNTK#1358]
While run CNTK example in ubuntu it throws this error

Traceback (most recent call last):
  File "A1_GenerateInputROIs.py", line 5, in <module>
    import PARAMETERS
  File "/home/lakeba/Downloads/cntk/Examples/Image/Detection/FastRCNN/PARAMETERS.py", line 2, in <module>
    from cntk_helpers import *
  File "/home/lakeba/Downloads/cntk/Examples/Image/Detection/FastRCNN/cntk_helpers.py", line 7, in <module>
    from fastRCNN.nms import nms as nmsPython
  File "/home/lakeba/Downloads/cntk/Examples/Image/Detection/FastRCNN/fastRCNN/__init__.py", line 7, in <module>
    from .imdb import imdb
  File "/home/lakeba/Downloads/cntk/Examples/Image/Detection/FastRCNN/fastRCNN/imdb.py", line 19, in <module>
    from .utils3_win64.cython_bbox import bbox_overlaps
ImportError: No module named 'fastRCNN.utils3_win64.cython_bbox'

**Comment by pkranen** [comment]
From [here](https://github.com/Azure/ObjectDetectionUsingCntk/issues/4#issuecomment-274887660):

You are getting this error since the 'cython_bbox' binaries are compiled for windows. A quick fix would be to switch to a VM which runs windows. Alternately, you could install and compile for Linux yourself. See the original fast R-CNN code for that, e.g. [https://github.com/rbgirshick/fast-rcnn/tree/master/lib/utils](https://github.com/rbgirshick/fast-rcnn/tree/master/lib/utils).

**Comment by Abimahesh** [comment]
Thanks. Can you provide steps to compile for Linux please?

**Comment by pkranen** [comment]
It is described here: [https://github.com/rbgirshick/fast-rcnn](https://github.com/rbgirshick/fast-rcnn)

```
git clone --recursive https://github.com/rbgirshick/fast-rcnn.git
cd $FRCN_ROOT/lib
make
```

then copy the `cython_bbox` and `cython_nms` binaries from `$FRCN_ROOT/lib/utils` to `$CTNK_ROOT/Examples/Image/Detection/FastRCNN/fastRCNN/utils3_win64`. The folder name will be fixed in one of the next commits, stay tuned.

**Comment by Smarker** [comment]
@pkranen I just did the steps for linux. I can't perform `make` since I don't see a `makefile` in the `fast-rcnn` repo. Where's the `makefile`?
