### ISSUE TITLE
There needs to be a way to save/restore model state in python without hitting the disk.

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#1431]

**Comment by eldakms** [comment]
Could you please provide more detail? What does it mean save/restore without going to disk? Why cannot you simple clone, if you need another copy. Thank you.

**Comment by spandantiwari** [comment]
Please reopen if you have questions or more information.

**Comment by Ark-kun** [comment]
@eldakms So, how can I clone both the network and the trainer state? I want to backup the full state (model + trainer) before every minibatch so that I can easily restore if something goes wrong. I do not want to write any data to the disk though. Ideally, I do not want to fetch the data from GPU either.

**Comment by eldakms** [comment]
Hmm, unfortunately the trainer currently only provides ability saving a checkpoint to a file. Maybe you can ask the CNTK team to provide a method for in-memory representation (all is already in there, it is simply not exposed).

As a workaround you can save the Function + Learner state yourself, these simply return you dictionaries, without going to disk. The trainer also has some information about counters - this will be lost.

Saving per minibatch is still slow though. All weights are allocated on GPU, so in order to serialize them they should be fetched to CPU. Serialization is pretty heavy operation.
