### ISSUE TITLE
What does "randomize" mean in general reader configuration?

### ISSUE THREAD

**Issue by taeguk** [Microsoft/CNTK#1435]
https://github.com/Microsoft/CNTK/wiki/Understanding-and-Extending-Readers#general-reader-configuration

In general reader configuration, what does "randomize" mean??
I understanded it means that shuffle mini-batches every epoch.
Is it right? or not?

**Comment by eldakms** [comment]
hi taeguk,

more or less, but not exactly. it does not shuffle the minibatches but the sequences inside the whole corpus.

So let's say all your data is N sequences - S1, S2, S3 ... SN (sweep)

1) The first thing is that they are infinitely replicated along the global timeline:
S1, S2, S3 ... SN <end of sweep 1> S1, S2, S3 ... SN <end of sweep 2> S1, S2, S3 ... SN <end of sweep 3> ...

2) Inside the sweep, sequences are composed in chunks to allow efficient IO (one chunk is usually ~ 32 MB), so each chunk has many sequences (M << N):
C1[S1... Sk] C2[Sk+1 ... Sl] ... CM[Sl+ 1. .... SN]

3) When the new sweep starts we firstly shuffle all chunks in the sweep. Then we create a rolling window of X chunks based on the "randomizationWindow" value (using this value you can control how much data will reside in memory) and we randomized all sequences inside this rolling window.

4) when the first chunk of the rolling window is consumed, it get's dropped and we pull in the next chunk and do randomization of the window again, etc.

Thanks.

**Comment by taeguk** [comment]
Thank you! And I have a one more question.
I'm currently using CNTK C++ API for production in company. 
I developed simple sub-library, include features similar to that you explained.
My library do that progress in background for performance.

I want to know that progress are running in background thread.
And how efficient CNTK's implementation is?
If CNTK's implementation is good and fast, I want to use that instead of my implementation.

**Comment by eldakms** [comment]
Not sure what you mean by "progress", do you mean what we output /sampels per sec/aggregated error for minibatches/epochs?
Currently this is not available for V2 C++ library, only for Python. It is planned, but I cannot give any ETA as of now.

**Comment by taeguk** [comment]
"progress" means randomize including shuffle.
I want to know procedure "randomize" is running on background thread or on main thread?
In other words, I want to know that can utilize CPU/GPU idle time.

**Comment by eldakms** [comment]
IO chunks are prefetched on a separate thread. get_next_minibatch is also prefetched on a background thread (all randomization happens there). 

So that as soon as the network requests one minibatch for computation - in the background we already start working on the next minibatch, so that when the next request comes - we already have all data on GPU.

Something like this (if times go from here down):
Network asks for data                   -      reader returns Minibatch M and starts working on M2
Network does forward/backward -      in parallel reader does rand., pack., GPU transfer etc for M2
Network asks for data                  -       M2 is ready and given our and reader starts working on M3....

**Comment by taeguk** [comment]
I think it is efficient like I expect. Thank you very much for your kindness. :)
