### ISSUE TITLE
Please improve documentation re: RGB channel reversal by ImageDeserializer

### ISSUE THREAD

**Issue by mawah** [Microsoft/CNTK#1487]
Hi folks,

I've been working on a use case that requires applying a trained model to images that I can't load using MiniBatchSources. (Specifically, I am applying the trained model to image data in RDDs with PySpark.) I've been loading the images into numpy arrays of the appropriate shape before feeding them into the trained model for evaluation. The performance on images loaded in this way was, mysteriously, lower than the performance on images loaded from MiniBatchSources.

I finally figured out the problem while reading the `eval_single_image()` function definition in [this otherwise-unrelated example on transfer learning](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/TransferLearning/TransferLearning.py). Apparently, the CNTK ImageDeserializer that I used during training has the wholly unexpected functionality of *reversing the RGB channel order*.

Now that I know this, I can reverse an image's RGB channel order before feeding it to my trained model for evaluation...but it really is only through almighty grace that I discovered what was happening. Please document what the ImageDeserializer is doing so that users can know how to supply similar input data to their trained models. (Or better yet, stop reversing the RGB channel order; why is this done?)

**Comment by mawah** [comment]
Would also appreciate if anyone can explain why the RGB channel reversal during evaluation was not necessary in this [CIFAR-10 tutorial](https://github.com/Microsoft/CNTK/blob/v2.0.beta11.0/Tutorials/CNTK_201B_CIFAR-10_ImageHandsOn.ipynb). Is there a way to predict whether one needs the reversal or not, without experimentation?

**Comment by mfuntowicz** [comment]
Hi @mawah,

As you can see in the CIFAR10 tutorial, we use the ImageDeserializer which uses OpenCV under the hood. OpenCV layout is BGR that's why when using CNTK's ImageDeserializer capabilities you don't see any transformation over the image layout.

When you start feeding data "manually" to a network, you need to take extra care about the image layout the model was trained with:

- If your model was **trained using ImageDeserializer**, the internal image representation is **BGR**.
- If your model was **trained dynamically (ie. without using ImageDeserializer - with the Python binding for example)** you need to **keep the layout** you were using for training your model.

Hope it helps :)
Morgan

@cha-zhang : Maybe it would be helpfull for people to put the information about the image layout in the documentation of Image Reader ?

**Comment by mawah** [comment]
Thanks @mfuntowicz, this explanation really does help me understand the cause and determine when I'll need to perform the reversal. I leave it to you folks to decide where it would be most helpful to add a clarification in the docs. (Personally I looked under ImageDeserializer in the Python API reference and didn't see anything there. I don't see an entry there for ImageReader and would not have known to look for it.)

**Comment by mfuntowicz** [comment]
I'm closing the issue for now.
Feel free to reopen if you have any issue :).

Morgan
