### ISSUE TITLE
About the version of OpenCV and python

### ISSUE THREAD

**Issue by cjliux** [Microsoft/CNTK#1522]
OpenCV had released a newer version than 3.1. Can CNTK support version 3.2? And currently the newest version of python3 is 3.6, should I install the previous version of python?

**Comment by wolfma61** [comment]
Although I assume this is a general question - but for the record: are you concerned about Windows or Linux?
We build and test with opencv3.1, this is what is used in our recommend Anaconda Python version.

We will add Python 3.6 to the supported Python versions in the near future, although it has not been scheduled, so I can't promised that it will be in the next beta. But we understand that we need to support it soon. OpenCV3.2 might be a requirement for this switch.

You should install the Python version we recommend (if any possible), since this is what we build and test with. We supply WHLs only for 2.7, 3.4 and 3.5 - so no 'standard' installation on 3.6 at the moment

Hope this helps .... I will take a closer look at the 3.6 planning ...
Wolfgang

**Comment by bencherian** [comment]
I've successfully built ImageReader with OpenCV 3.2 on Windows. (I don't actually use it though, so I don't know if there's any broken functionality.) You need to edit the CNTK.Cpp.props file to add support for OpenCV 3.2. You can take a look at the file in my fork if you're interested.

**Comment by cjliux** [comment]
Well, thank all of you. It would be better for me to use OpenCV 3.1 to avoid troubles.
