### ISSUE TITLE
Hard, silent crash: CNTK/Python with Dense followed by Convolution

### ISSUE THREAD

**Issue by andrewww** [Microsoft/CNTK#1523]
Silently crashes the Python interpreter (i.e., no stack trace, not a Python exception). The condition seems to be having a Dense layer followed by a Convolution (or Deconvolution) layer. This may be an edge case with the 1-dimensional convolutions I'm working, but I can't tell.

CNTK 2.0b11; Windows 7 64-bit; Python 2.7.
Update: Also crashes with CNTK 2.0b12.
Crashes with both CPU and GPU devices.

The following is a minimum working example of this crash.  I have no way of further debugging this (I have a limited development environment).
```
import numpy as np
import cntk.ops as C
from cntk.models import Sequential
from cntk.layers import default_options, Convolution, Dense

num_filters=16
size_filters=8
n_input = 512

inputs = C.input_variable((1,n_input,1),np.float32)
net = Sequential([
    Dense(512),
    Convolution((size_filters,1),num_filters=num_filters,strides=1,pad=True),
    ])

# Crashes utterly silently on this line 
print( "Got here." )
z = net(inputs)
print( "Didn't get here." )
```

**Comment by bencherian** [comment]
CNTK seems to have issues with propagating errors in the C++ backend back into Python. But your problem is basically due to tensor shape mismatches during construction.

First, please note that the function composition starts at the left for the Sequential model. (i.e., the model you constructed goes from Input to Dense to Convolution, not Input to Convolution to Dense...I assume this is intentional despite being rather unorthodox since the Dense layer will mess up any spatial correlation that may exist in your input.)

`Dense(512)` produces a tensor of shape (512,) which cannot be fed into a Convolution layer which expects an explicit channel dimension (i.e., for 1D input, the input to the convolution should have shape (num_channels, num_pixels)). You need to explicitly specify the output shape for Dense to be compatible with the Convolution. The minimal required change to the code would be to change `Dense(512)` to `Dense((1,512,1))`. However, I don't think you need the trailing singleton dimension. I would rewrite the code as follows (assuming you really do want this model structure):

```Python
import numpy as np
import cntk as C
from cntk.models import Sequential
from cntk.layers import default_options, Convolution, Dense

num_filters=16
size_filters=8
n_input = 512

inputs = C.input_variable((1,n_input), np.float32)
net = Sequential([
    Dense((1,512)),
    Convolution((size_filters,), num_filters=num_filters, strides=1, pad=True),
    ])

# Crashes utterly silently on this line 
print( "Got here." )
z = net(inputs)
print( "Now will get here." )
```

**Comment by andrewww** [comment]
Thank you so much.

Yup, it is unorthodox and not just a screw-up. The actual problem involves structured inputs *and* structured outputs, but *not* shared structure. So the actual network is: 
Convolution (one or more) -> Dense (one or more) -> Convolution (one or more)

Incidentally, I *think* that I need the trailing singleton. Back when I was originally setting up CNN's over one-dimensional data, I couldn't get things to work out without it. Maybe it was something goofy like "can't do 1D convolutions on the GPU" or something.
