### ISSUE TITLE
CNTKLibraryAPI. Crash on LSTM-model loaded evaluation.

### ISSUE THREAD

**Issue by Henry-White** [Microsoft/CNTK#1543]
latest update (27.02), CNTKLibraryAPI, Single thread on CPU.
Source based on CNTKLibraryCPPEvalCPUOnlyExamples.
Execution LSTM with model loaded (auto modelFuncPtr = CNTK::Function::LoadModel(modelFilePath, device);)
crashed on:
evalFunc->Forward({{inputVar, inputValue}}, outputs, device);
Model, config, source and output are included here:
[https://drive.google.com/open?id=0B9DUjrGF_JqreC1uaE1pS19IX1U](url)

**Comment by zhouwangzw** [comment]
Thanks for reporting it. I will take a look.

**Comment by zhouwangzw** [comment]
@Henry-White I looked into the code you have shared. It seems that there are some mistakes in your code when preparing data.
int rsize = -1; int n = 0; float r[100]; while (sscanf(sa, "%*[^0-9]%f%n", r + rsize, &n)) { sa += n; rsize++; }
For me, the rsize should be 0, otherwise ther+rsizein sscanf access to r[-1] which could corrupt the stack. And since your input sa, has more than 100 float numbers, indeed 119, the size of the array r should be at least 119 (if your input changes, the array size needs to be adapted. Would std::vector be a better choice for r, instead of array?)
With the following change
int rsize = 0; int n = 0; float r[119];
, I can run your example without problem.

#1434

**Comment by Henry-White** [comment]
update, rebuild, solved.
