### ISSUE TITLE
Nework Archtecture Question - RPROP

### ISSUE THREAD

**Issue by robertjanks** [Microsoft/CNTK#1561]
I have been using FANN RPROP software and getting decent results (>90%) on different datasets like this: https://archive.ics.uci.edu/ml/datasets/Wine
I have not been able to figure out how to get similar results using CNTK BS.
How do I build a BS network that most closely works like FANN RPROP?

Here is what I have tried (only gets about 65%):
[wine-red1.txt](https://github.com/Microsoft/CNTK/files/817818/wine-red1.txt)
[wine-red2.txt](https://github.com/Microsoft/CNTK/files/817822/wine-red2.txt)
[wine-red3.txt](https://github.com/Microsoft/CNTK/files/817823/wine-red3.txt)
[wine-red4.txt](https://github.com/Microsoft/CNTK/files/817820/wine-red4.txt)
[wine-red5.txt](https://github.com/Microsoft/CNTK/files/817821/wine-red5.txt)
[wine-red6.txt](https://github.com/Microsoft/CNTK/files/817819/wine-red6.txt)

**Comment by L-Ramos** [comment]
Dataset website is not opening, can you send us another place so we can take a look at the data?

**Comment by robertjanks** [comment]
Here is the csv data file:
[winequality-red.txt](https://github.com/Microsoft/CNTK/files/826156/winequality-red.txt)

Here is the data file description:
[winequality.txt](https://github.com/Microsoft/CNTK/files/826157/winequality.txt)

Here is what worked for the other software:

FANN RPROP C program -> 99.94% accuracy:
[wine_train.txt](https://github.com/Microsoft/CNTK/files/826160/wine_train.txt)
4 layer network, with 2 hidden layers of 99 nodes each, nothing too complicated

LIBSVM Ps1 Script for FloatFann.c program -> 98.25% accuracy:
[run-wine-red.txt](https://github.com/Microsoft/CNTK/files/826174/run-wine-red.txt)

The other software seems to do OK.

**Comment by L-Ramos** [comment]
So you want to predict wine quality right, thats why you have 11 labels, from 0 to 11? I'll check a few things and by the end of the day I'll give you a proper answer if I can figure something out.

**Comment by L-Ramos** [comment]
What file are you sing here:     
reader = [
        readerType = "CNTKTextFormatReader"
        file = "wine-red.txt"
        randomize = "none"
        maxErrors = 100
        traceLevel = 0
Just the winequality-red.txt that you uploaded above or did you separate it in |Labels 1 |features....?

**Comment by robertjanks** [comment]
I did reformat the data.
This is a simple reformat into the form |L ... |F...:
[wine-red.txt](https://github.com/Microsoft/CNTK/files/827431/wine-red.txt)

This is a reformat into the format |L ... |F... , but the data is re-scaled from -1 to 1:
[wine-red-scaled.txt](https://github.com/Microsoft/CNTK/files/827435/wine-red-scaled.txt)

**Comment by L-Ramos** [comment]
So, the website is loading now, according to the information on it the dataset is composed of 3 classes and 178 instances.
class 1 59
class 2 71
class 3 48
So I dont get why you have 11 labels an more than 1600 samples.

**Comment by robertjanks** [comment]
Sorry for the confusion.
I was not are that there are two completely different types of data for wine.

I am using the Wine Quality - Red dataset here:
https://archive.ics.uci.edu/ml/datasets/Wine+Quality

I am NOT using the Wine Cultivar data found here:
https://archive.ics.uci.edu/ml/datasets/Wine

**Comment by robertjanks** [comment]
The dataset description says this about the data:
   Output variable (based on sensory data): 
   12 - quality (score between 0 and 10)

I checked the class distribution and found this:
Class # 0 = 0
Class # 1 = 0
Class # 2 = 0
Class # 3 = 10
Class # 4 = 53
Class # 5 = 681
Class # 6 = 638
Class # 7 = 199
Class # 8 = 18
Class # 9 = 0
Class #10 = 0

So the data doesn't represent all possible outcomes. There are no records for 5 of the classes.
Does that mean CNTK is having trouble with the "empty" classes?
Should I only have 6 output nodes?

**Comment by L-Ramos** [comment]
Ok, I'm going to check it, are you still interested in the results?

**Comment by robertjanks** [comment]
Absolutely! I am very interested in using this software for many of my projects!

**Comment by L-Ramos** [comment]
Ok, I'll try a few experiments here, but according to the dataset description your problem is an "anomalie" detection problem. You have very unbalanced classes and detecting the most uncommon ones is quite important right? I dont think the normal Softmax will be able to detect the classes with very few examples. Think about it this way: My algorithm is trying to reduce error prediction. I present 3 classes to my algorithm, class A with 3 examples, class B with 7 examples e Class C with 90 examples. My algorithm will try to predict the classes, but probably the 3/7 example from the other classes will not be enough for it to generalize well. The conclusion will be, if it predicts all samples as C, then the error is only 10%. In fact its not learning how to differentiate them, just going for the one that appears the most. So class imbalance is a problem. You could try to test the Support Vector Machine, it's usually good at dealing with this kind of dataset. Also CNTK provides a few tools to solve this kind of problem. I'll report my results as soon as I have them.

**Comment by sayanpa** [comment]
Closing this thread. Please open new issues if further help is needed.
