### ISSUE TITLE
Bad link in documentation page?

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#1602]
On the page:

https://github.com/Microsoft/CNTK/wiki/Reader-block

Near the bottom, to learn more about the Text Format Reader I click on:

CNTK Text Format Reader

it brings me to:

https://github.com/Microsoft/CNTK/wiki

So... where is doc on the Text Format Reader?

Thanks

**Comment by JohnCraigPublic** [comment]
I cannot find the documentation page for TextFormatReader -- where has it gone?

**Comment by sayanpa** [comment]
We have new manuals here: 
https://github.com/Microsoft/CNTK/tree/master/Manual

Brainscript docs can be found [here](https://docs.microsoft.com/en-us/cognitive-toolkit/How-do-I-Read-Things-in-BrainScript).

Apologies for the trouble since we are restructuring our documentation site.

It has been a while this link is up. I am closing this one, please do reopen this one or a new issue if you need more help.
