### ISSUE TITLE
General Question: Balancing Training Data

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#1620]
In image classification with N classes:  Should the training data contain the same number of examples for all N classes?  It seems that I've read that it is good practice.  Why?  What are the dangers of using non-balanced training data?

**Comment by avader906** [comment]
Please post your general questions to [Stackoverflow](https://stackoverflow.com/questions/tagged/cntk) / [Quora](https://www.quora.com/topic/Microsoft-Computational-Network-Toolkit-CNTK) / Reddit and/or consult other media for statistics of unbalanced datasets.

**Comment by sayanpa** [comment]
Closing this issue since there was a suggestion and no further communication on this thread. Please reopen the issue with details if you need a follow up.

Some amount of class imbalance is acceptable with deep models and provided sufficient data is available for training all categories. The specific numbers of what is acceptable class imbalance and how much data for each class is sufficient is rather problem dependent and the model specific details.
