### ISSUE TITLE
training_session.train does not end after specifying max_samples

### ISSUE THREAD

**Issue by aFuerst** [Microsoft/CNTK#1641]
When specifying max_samples for training_session if you do not specify epoch_size for the MinibatchSource used in it it will never return to the executing script, will stop printing progress reports for training the network, and continue to use CPU and GPU resources as if it were still training. This halt occurs after it completing training on whatever max_samples was set to.

If epoch_size if specified as anything but cntk.io.INFINITELY_REPEAT then the training will halt after going through the specified amount of samples.

```
ts = c.train.training_session(trainer=trainer, mb_source=reader_train, max_samples=1000,
                              mb_size=schedule, progress_printer=progress_printer, restore=True,
                              progress_frequency=training_progress_output_freq, var_to_stream=input_map,
                              checkpoint_config=CheckpointConfig(filename=os.path.join(model_path, model_name)),
                              cv_config=CrossValidationConfig(source=reader_train, mb_size=minibatch_size))
```

```
    return MinibatchSource(ImageDeserializer(path, StreamDefs(
        labels=StreamDef(field='label', shape=num_label_classes),
        features=StreamDef(field='image', transforms=transforms)
    )))  # ,  epoch_size=c.io.FULL_DATA_SWEEP)
```

**Comment by eldakms** [comment]
In your configuration you are specifying a reader_train as a CrossValidation source. after the training which is limited by max_samples - we run cross validation. Because you cross validation source never stops - the training session never returns.

Please use a different cross validation source from the one you use for training. In the next version we will add max_samples to the CrossValidationConfig as well.

I'm closing the issue for now.

Thank you for reporting!
