### ISSUE TITLE
The nuget package uses bad semantic version string, so the package manager wants to "upgrade" beta15 to beta9

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#1653]
Please, use proper semantic versions.

**Comment by zhouwangzw** [comment]
This is because Nuget V2 only supports Semanatic Versioning 1.0.0, which does not support numeric value sorting within pre-release labels. The Semantic Versioning 2.0.0 is only supported by Nuget 3.5. As we also want Nuget V2 to use CNTK Nuget packages, we have not upgraded them. 

Good news is that RC is coming soon, so you would not run into this issue again. 
Sorry for the inconvenience.

**Comment by zhouwangzw** [comment]
We have released 2.0RC1, which should fix the version problem.

**Comment by zhouwangzw** [comment]
I am closing the issue. Please feel free to re-open it if needed.
