### ISSUE TITLE
Missing libs in CNTK version 2.0 RC 1

### ISSUE THREAD

**Issue by chdinh** [Microsoft/CNTK#1697]
The binary package (CNTK for Windows v.2.0 RC 1 CPU only) do apparently only ship the dlls; libs are not anymore bundled.

Is there somehow a chance to download the libs without having to build CNTK?

Thank you.

**Comment by mahilleb-msft** [comment]
@chdinh - Thanks for your feedback, we're investigating this.
In the meantime are the Nuget packages an option for you? See https://github.com/Microsoft/CNTK/wiki/NuGet-Package...

Best, Mark

**Comment by avader906** [comment]
@mahilleb-msft including dll header files and libs (within binary distribution) is the default use case for the majority of users

**Comment by mahilleb-msft** [comment]
@avader906 thanks for your feedback. The (unintended) omission of the libraries in the drop will be fixed in the next release. For 2.0.rc1 it is possible to get the libraries via the Nuget. Without Nuget tooling, you can still download the Nuget packages from Nuget.org and unzip them.

**Comment by avader906** [comment]
@mahilleb-msft  thank you for your prompt note and instructions

**Comment by avader906** [comment]
@mahilleb-msft Mark, pardon my ignorance but it doesnt seem trivial to download the nuget package in zip form with something like wget
```
How to download a package?
The short answer is don't, at least not manually. NuGet provides a faster better way to incorporate a library into your project. 
```

**Comment by zhouwangzw** [comment]
@avader906 You can use the follow link for wget:
wget https://www.nuget.org/api/v2/package/CNTK.CPUOnly/2.0.0-rc1

If you can use Nuget in your projects, it is recommended to use the Nuget tooling instead of download. If not, download can give you the libraries you want. 
As Mark said, the libraries will be available in the binary download package in the next release very soon.

**Comment by avader906** [comment]
@zhouwangzw thank you for your instructions. the download page also has the direct link - no matter the notice it displays.

in terms of our processes, we typically would not be using nuget. we have automated build environment and introducing dependencies and package managers adds unnecessary complexity for none of the practical (to us) convenience.

C++ wiki page has all the instructions in terms of dependencies and C# could be updated to include the manual cntk lib reference inclusion too.

**Comment by zhouwangzw** [comment]
@avader906 Thanks. The Wiki page https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows contains how to manually add CNTK managed library to your project as follows:

If you do not want to use NuGet Package, you can add Cntk.Core.Managed-<VERSION>.dll as reference to your project. The Cntk.Core.Managed dll and all dependent dlls can be found in the CNTK binary release package on the CNTK Releases page. Please make sure that the path to Cntk.Core.Managed dll and its dependencies (see list at the end of this page) are included in the search path of dlls for your application.

Please let us know if you have questions or suggestions to improve the documentation.

Thanks,

**Comment by avader906** [comment]
@zhouwangzw instructions on that Wiki page are not only incomprehensible but out of date too. when it comes to C#, the only clear instruction to get the Lib to work is to use Nuget

**Comment by zhouwangzw** [comment]
@avader906 Thanks for your feedback. Would you mind to let us know which information is missing, and which is out-of-date?

We recommend users to use Nuget since it is a common and easy way to install libraries in C#/.NET. And as mentioned in the response above, we also provide information how to use the library without Nuget. If you are looking for example, our test [CNTKLibraryCSEvalExamplesTests ](https://github.com/Microsoft/CNTK/tree/master/Tests/EndToEndTests/EvalClientTests/CNTKLibraryCSEvalExamplesTest) uses the library directly without Nuget. If you have any questions, please let us know.

Thanks,

**Comment by avader906** [comment]
@zhouwangzw it all depends on the standards required for something to be called documentation.

information is not easily accessible, and where it is - often outdated. there are many examples throughout. as focused shifted to Python, it looks like all docs pertaining to Brainscript are out of date. in terms of C# - there is no concise documentation. a good start would be to have a small, easily understood tutorial model that is evaluated and API explained in-depth.

**Comment by zhouwangzw** [comment]
@avader906 The Nuget package supports both C++ and C# projects. For C#, the Cntk.Core.Managed-2.0rc1.dll is built with released dlls, so the debug build does not work. Sorry I have not mentioned it before. (CNTK.CPUOnly.2.0-rc1.nupkg\build\net45\CNTK.CPUOnly.targets defines which dlls are copied from which location). The debug dlls in the Nuget package is used by C++ projects.

For C# API, currently we have C# API document [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Managed-API), and some [examples](https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CNTKLibraryCSEvalCPUOnlyExamples/CNTKLibraryCSEvalExamples.cs) which showcase how to evaluate a pre-tained model in different use cases, e.g. creating batch/sequence/batchOfSequence input, using dense/one-hot vector/sparse data, parallel evaluation, and loading model from file or memory buffer. We are working on a turorial for inference too. We are very appreciated if you want contribute. 

Thanks,

**Comment by avader906** [comment]
@zhouwangzw thank you for your prompt reply. Why not include both the debug and release version of the API DLL wrapper for C# - is there a specific technical issue given that all dependencies are supplied with -d- versions? 

- For examples, one would try to have consistent code style and expose the functionality one step at a time. This probably was not the top priority of the person coding unit tests - to which you refer as examples.
- The C#document is a list of API calls, maybe the next step is to break-it down and detail+ code snipplets as had been done with Python.
- Yes, I would gladly contribute.

**Comment by zhouwangzw** [comment]
The same C# CNTK Managed assembly can be used for building both release and debug version of your C# application, so there is no need to provide different version of C# assemblies. But for C++ projects, the ABI for debug and release build is incompatible, so that you have to use right libraries/dlls for your build: debug vs debug, release vs release. This is the reason why we include both debug and release version of C++ libraries and dlls, but only the release version of C# assembly. For users who want to debug into CNTK code itself, compiling with CNTK source is probably the best choice.

Wrt. examples, we do have end-to-end [examples](https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CNTKLibraryCSEvalCPUOnlyExamples/CNTKLibraryCSEvalExamples.cs), which cover the complete workflow for a specific use case. For example, EvaluationSingleImage() there shows how to evalute a ResNet model (Examples/Image/Classification/ResNet/Python/Models/TrainResNet_CIFAR10.py), EvaluationBatchOfSequencesUsingOneHot() for evalauting a RNN model with one-hot vector as input,  and EvaluateMultipleImagesInParallel() showcases how to evaluate multiple images in parallel. 

It would be great that you could provide an example showing how to inteact with 32bit clients through named pipe server. As an open source project, we really rely on community to make CNTK better. Thank you for your contribution!

**Comment by avader906** [comment]
@zhouwangzw re providing release assembly only - it is a choice and it is not immediately evident. "only the release version of the assembly is provided, it uses release versions of the dependencies within the package" - would make a nice addition to the C# API wiki along with other information you have kindly supplied to this thread.

**Comment by zhouwangzw** [comment]
Thanks for the suggestion. I will add it to the Wiki page.

**Comment by zhouwangzw** [comment]
I have added it to the page https://github.com/Microsoft/CNTK/wiki/NuGet-Package

The CNTK NuGet packages may be installed on a Visual C++ or .NET project (C#, VB.Net, F#, ...). The Nuget package contains both debug and release versions of C++ library and dlls, and the release version of C# assembly and its dependent dlls. Once installed the project will contain a reference to the managed dll and the required dependent binary libraries will be copied to the output directory after building the project.

**Comment by zhouwangzw** [comment]
I am closing the issue. Please feel free to re-open it if needed.
