### ISSUE TITLE
function.eval details question

### ISSUE THREAD

**Issue by aFuerst** [Microsoft/CNTK#1698]
What are the differences between these two way of evaluating images? They subtract different means from the input data but it doesn't say where they are determined, and each re-arrange the order of pixels being sent to the network. The first one mentions PIL loading data differently than the network expects but I can't find anything more about this elsewhere. When I try either of these approaches to do my own evaluations I always get 50% error rate and it thinks all my samples are the same.

https://github.com/Microsoft/CNTK/wiki/Evaluate-a-saved-convolutional-network

rgb_image = np.asarray(Image.open("foo.jpg"), dtype=np.float32) - 128
bgr_image = rgb_image[..., [2, 1, 0]]
pic = np.ascontiguousarray(np.rollaxis(bgr_image, 2))

https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_201B_CIFAR-10_ImageHandsOn.ipynb

    image_mean   = 133.0
    image_data   = np.array(PIL.Image.open(image_path), dtype=np.float32)
    image_data  -= image_mean
    image_data   = np.ascontiguousarray(np.transpose(image_data, (2, 0, 1)))
    
    result       = np.squeeze(pred_op.eval({pred_op.arguments[0]:[image_data]}))

**Comment by mawah** [comment]
Hi @aFuerst,

I asked some similar questions in the past; here's what I've gleaned.

The response was that CNTK is built on OpenCV, which loads the images with shape `(color_channel_num, image_width, image_height)`. For a color image, color channel 0 is blue, color channel 1 is green, and color channel 2 is red -- aka BGR order.

PIL (and many other packages) load images with shape `(image_width, image_height, color_channel_num)`. For a color image, color channel 0 is red, color channel 1 is green, and color channel 2 is blue -- the expected RGB order.

Many models are trained using a CNTK MiniBatchSource (thus OpenCV) to load the images, but during model evaluation, it may be easier to use PIL to load the image data. You can see in the "Evaluate-a-saved-convolutional-network" example that after loading with PIL:
- the color channels are flipped from RGB to BGR order
- the indices are transposed from `(image_width, image_height, color_channel_num)` to `(color_channel_num, image_width, image_height)` by the `np.rollaxis()` function.

The "CNTK_201B_CIFAR-10_ImageHandsOn.ipynb" example seems to have omitted the RGB to BGR conversion: maybe this is why they are reporting a high classification error rate. (An 18-layer ResNet would have an expected error rate more like 8%.) I've brought that problem up before in a [separate Git Issue](https://github.com/Microsoft/CNTK/issues/1487).

Re: the mean subtraction, the best performance is achieved by matching the mean subtraction method used in training to the one used during evaluation. In the "CNTK_201B_CIFAR-10_ImageHandsOn.ipynb" example, however, two different methods of mean subtraction are used during training and evaluation. During training, `xforms.mean()` is used to subtract the position-specific, color channel-specific mean intensities (calculated across the whole training image set) that were pre-calculated and stored in an XML file (`mean_file`). During evaluation, this behavior is approximated by subtracting a fixed value -- 133, presumably chosen because it is close to the overall mean intensity -- from the pixel intensities at each position and in each color channel. To be fair, it's sort of a hassle to load and subtract the data from the XML file; my own attempt is available [here](https://github.com/Azure-Samples/hdinsight-pyspark-cntk-integration).

**Comment by aFuerst** [comment]
Wow, thanks! It's awesome to see a great explanation of what's going on with the image loading. 

So the optimal route for error reduction when evaluating networks is to subtract the computed image mean before sending the data to be evaluated? Is there a method to computing the single value mean? I took the mean of image mean data but that value didn't improve the error rate.

**Comment by mawah** [comment]
Hi @aFuerst,

Actually I am not claiming that any one method for mean subtraction is better than another. What I'm saying is that you should use the same method for both training and evaluation, rather than mix-and-match.

How did you modify the example notebook that you mentioned earlier? Is the same type of mean subtraction now used for both training and evaluation? Has the RGB->BGR ordering issue been corrected? Maybe you could post a link to it somewhere and I'll take a look.

**Comment by aFuerst** [comment]
I subtracted the mean image from the training data that was also used during training to test new samples that drastically improved the accuracy. Your example was very helpful as well! Thank you
