### ISSUE TITLE
How to write out errs to a file during the training process?

### ISSUE THREAD

**Issue by Birky** [Microsoft/CNTK#1756]
I would like to write out the errs to a file during the training process to be able to analyse the training process. However, I cannot figure it out how.  I am trying to solve it on 01_OneHidden.cntk. I already tried the "write" action, but the results are not what I want. If I understand it correctly, the "write" action works on an already trained model, but I would like to write the values of the node (errs) during the training process. 

I also tried to define outputPath and outputNodeNames for the "train" block, but it is obviously does not work.

What is the solution for my requirement?

For better understanding, I want to write out the following node
`errs = ClassificationError (labels, out.z)`

the same way as it is in the command prompt window, but into a file
![image](https://cloud.githubusercontent.com/assets/12012176/25088157/6ddf7f1c-2374-11e7-82aa-1d65b257d882.png)

Is it possible?

Regards,
Birky

**Comment by avader906** [comment]
@Birky you can use the Powershell to extract per Epoch ce and errs from CNTK log files. 

It seems you do not use validation - only training, so please omit the step 3. 

It is possible to monitor these values in real time - either using Python instead of Brainscipt (and tensorboard) or fetching one of the libraries (i recall one in F# out there) that monitors and parses the CNTK logs in realtime.

1) Redirect output to a log file via Brainscript *stderr* command (modify paths accordingly):
```
RootDir = "mydriveletter:/mypath"
OutputDir = "$RootDir$/OutputDirectory"
stderr = "$OutputDir$/myLog"
```
2) Create and run in your OutputDirectory the following powershell script (after training completes):
```
$Out =  @() 
((Get-Content mydriveletter:\mypath\OutputDirectory\myLog -Raw) -split '\n(?=Finished Epoch)') | % {
    $x = $_ -split '\r'
    $ln = New-Object PSOBJECT -Property @{
         type  = [regex]::Match($x[0],'Training|Validate')
        epoch = [regex]::Match($x[0],'[-+]?([0-9]*\.[0-9]+|[0-9]+).+?(?=(of))')
        errs    = [regex]::Match($x[0],'(?<=errs = ).[-+]?([0-9]*\.[0-9]+|[0-9]+)')
        ce    = [regex]::Match($x[0],'(?<=ce = ).[-+]?([0-9]*\.[0-9]+|[0-9]+)')
        #note: below are other commonly parsed for values depending on the model:
        #ep    = [regex]::Match($x[0],'(?<=ep = ).[-+]?([0-9]*\.[0-9]+|[0-9]+)')
        #se    = [regex]::Match($x[0],'(?<=se = ).[-+]?([0-9]*\.[0-9]+|[0-9]+)')
        #rmse    = [regex]::Match($x[0],'(?<=rmse = ).[-+]?([0-9]*\.[0-9]+|[0-9]+)')

    }

    $Out += $ln
    remove-variable ln
}

foreach ($item in $Out) 
{
    $line = $item.epoch.Value + "," + $item.type.Value + "," + $item.ce.Value + "," + $item.errs.Value
    #examples of other types of CSV value rows
    #$line = $item.epoch.Value + "," + $item.type.Value + "," + $item.ce.Value + "," + $item.ep.Value
    #$line = $item.epoch.Value + "," + $item.type.Value + "," + $item.se.Value + "," + $item.rmse.Value
    Add-Content mydriveletter:\mypath\OutputDirectory\trainingstats.csv $line;
}
```
This will create trainingstats.csv CSV file of the following format:
```
Epoch Number, {Training or Validate}, ce, errs
```
Example:

1 ,Training,3.72790515,0.65427434
1 ,Validate,2.64465327,0.82338007
2 ,Training,1.24513876,0.45104839
2 ,Validate,3.14025363,0.80003929
2 ,Training,1.25749039,0.45342234
2 ,Validate,3.12236197,0.80003929
2 ,Training,1.28327154,0.45936279
...

3) You can import it to Excel and sort by Epoch+Type to get only Training or Validate values
