### ISSUE TITLE
Supported version of MPI

### ISSUE THREAD

**Issue by yzhang87** [Microsoft/CNTK#180]
I was wondering what is the supported openmpi version for CNTK. We are trying to setup MPI on the cluster and the default ubuntu mpi seems like an older version. But if it works, it is easier to setup (only need to do apt-get when we get a new machine).

**Comment by Alexey-Kamenev** [comment]
Hello,
In general, we strongly recommend installing those versions which are specified in our [Wiki](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux).
In that particular case of OpenMPI, the version that is installed by Ubuntu apt-get is very old and there were several important bug fixes made since then.

**Comment by alexeyo26** [comment]
I also found that Ubuntu apt-version misses a couple of libraries CNTK needs. So I join Alexey's comment above and recommend using the procedure in our Wiki (that directs you to installing from sources, but's really straightforward)

Thank you,
Alexey

P.S. I will close the issue now,
