### ISSUE TITLE
Errors using CNTK Library Eval example

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#1815]
Using the posted example for using CNTK Library for Eval using C++.  

Firstly, the line:

auto modelFuncPtr = CNTK::Load(L"01_OneHidden", device); 

complained that "Load" is undefined.  Should I replace with "FunctionPtr" ??

Having done that, trying to compile, I get a bunch of errors in CNTKLibrary.h all complaining about "max()"
saying "not enough actual parameters in max()"

Is your example out of date, or am I doing something wrong?  I have 2-0-rc1 installed and used NuGet to download version 2-0-rc1 of CNTKLibrary in VS2015 update3.

Thanks.

**Comment by JohnCraigPublic** [comment]
I updated to 2-0-rc2 via NuGet -- but still: if I include CNTKLibrary.h file in my project, even if I don't call any functions from it, I cannot build my project due to many errors complaining about "max()" that appears multiple places in CNTKLibrary.h

Using VS2015 update3.  Using C++ in x64 and Release. 

Ideas?

**Comment by JohnCraigPublic** [comment]
...and by the way, I am now replacing  "CNTK::Load" with "CNTK::Function::LoadModel" in your example.  I don't think this is related to my problem with the *.h file though.

**Comment by JohnCraigPublic** [comment]
It looks like the problem is because I have:
#include <afxwin.h>   
because I am using a few MFC collection types in my code....

So, is not possible to use MFC with CNTKLibrary ?     

Is there a way to let them coexist?   If not, maybe mention it in the documentation somewhere that they don't play together...

**Comment by zhouwangzw** [comment]
CNTKLibrary is using STL. It seems that your problem is related to using STL in Windows Program which can cause Min/Max conflicts, as described [here](https://support.microsoft.com/en-us/help/143208/prb-using-stl-in-windows-program-can-cause-min-max-conflicts). The solution is to add "#define NOMINMIX" before #include directives, e.g. in all of your “stdafx.h” files. 

#define NOMINMAX
#include <windows.h>

ps. The evaluation examples are update-to-date and I have just tested the samples in RC2 binary package using RC2 Nuget without any problem. 

Hope it helps. 
Thanks

**Comment by JohnCraigPublic** [comment]
zhouwangzw - thanks, that was a very helpful hint.  Its starting to work now!
