### ISSUE TITLE
Value nan

### ISSUE THREAD

**Issue by fct-edilberto** [Microsoft/CNTK#1857]
I obtain value nan in classes and Mean AP

```
AP for       clase1 = nan
AP for          clase2 = nan
C:\Users\imolinero\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib
\nanfunctions.py:675: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)
Mean AP = nan
DONE.
```

**Comment by fglavota** [comment]
Any solution for this? I'm getting the same.

**Comment by pkranen** [comment]
The reason is that you output does not contain a predictions for any of the classes, i.e. all bboxes are assigned to background. In consequence the recall is nan (division by zero), therefore the AP for the single classes is nan and also the Mean AP. You'll need to tune the parameters or your data set to get predictions for the classes. We'll address the division by zero and return zero instead of nan.
