### ISSUE TITLE
performance problems with gcc 4.9.3

### ISSUE THREAD

**Issue by ianupright** [Microsoft/CNTK#188]
With the very latest code as of March 1st, it now compiles fine with gcc 4.9.3.  However, in my testing of the PennTreebank example, for some reason when I switch to my build with 4.9.3, as opposed to 4.8.5, when running under CPU, it runs into a performance problem that seems to be in the rough ballpark of 100x slower.. i.e. things run to a crawl, even though the CPU is fully utilized.

Until this issue is resolved, I strongly recommend adding in some sort of extra check to ensure the build fails on gcc 4.9.3, even though Issue #176 recently fixes an issue which allowed it to build on 4.9.3, or until 4.9.3 can be tested more and verified that it is working correctly.

**Comment by ianupright** [comment]
I can confirm that when running the model under GPU, gcc 4.9.3 seems to run the same speed or a small fraction faster than 4.8.5 so it appears this problem is exclusive to CPU models.

**Comment by Alexey-Kamenev** [comment]
We will take a look, but it seems to me there might be some problem with OpenMP. The only idea I have for now is to try limiting number of CPU threads by using `numCPUThreads` config parameter, for example:

`numCPUThreads=8` 
and see if that helps.

**Comment by frankseide** [comment]
Another possibility to look out for is that a bug fix may have changed behavior of rvalue references. std::move does not always work the way I expect, and part of that has in the past been due to compiler errors. Move assignments are used heavily in CNTK with matrix views. Maybe a compiler fix now forces some moves to be copies? Should be easy to find through randomly breaking in the debugger a few times and checking whether most of the time we end up in memcpy().

**Comment by mradmila** [comment]
Did any of these suggestions help?

**Comment by mahilleb-msft** [comment]
Closing since there wasn't any update.
