### ISSUE TITLE
Need some info/doc on CNTK::Function::LoadModel

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#1889]
I need a better understanding of how memory allocation and deallocation works with a call like:

FunctionPtr ER = CNTK::Function::LoadModel(L"C:/mymodel", device);

Models can be large, and as I ramp to real-world usage, I think I need to be more careful about the size of stuff in memory.  

So, questions:

0) Can you point me to documentation on "LoadModel" ?
1) In the above, do I need to actively do something later to "release" the memory, or this just happens automatically when the FunctionPtr variable goes out of scope?  Looks like its automatic.
2) If my FunctionPtr variable is a global, and never goes out of scope, in that case, can I do something to recover the memory when I'm finished using the model?
3) In one application I load 10 models into memory -- each model is about 250MB -- but if I look at the memory consumption of my process, I don't see that its consuming 2500MB, it looks more like its just 250MB - like the size of only the most-recently loaded model.  I don't understand that.  The application runs fine, so all models must be loaded and accessible, but I thought the windows task manager would show a memory footprint of 2500MB or so -- but it doesn't...  Can you explain that?
4) These models are large, and my application might need 100 or more separate models, each of 250MB size or so.   So.... I need to distribute 25 GB to my users!   I need to send them a set of DVDs?  Hmmm...
Maybe I need to see if a smaller model can do the trick for me, but, you guys in the community, is there something I am missing or need to consider?
5) In trying to speed up the running time of my application, I have learned that the bulk of the time is in the call (above) to LoadModel.  I used to routinely load the model each time I want to run it -- but then I noticed loading may take 2.5 seconds, whereas the actual eval takes 0.2 seconds or so.  Hence, I want to just 'pre-load' the model once and use many times.  But now I have the issue of big models sitting in memory all the time.  Comments?

Thanks!

**Comment by bencherian** [comment]
FunctionPtr is a smart pointer (It's just a typedef'd std::shared_ptr<Function>) so when it goes out of scope it should release any associated memory...if you have a global variable `FunctionPtr ER` and you call assign the output of `LoadModel` to `ER` 10 times, you won't use 10x the memory because the prior model assigned to `ER` will have no more references.

How are you generating the models? If they are actually checkpointed training objects the model files will be much larger than needed for evaluation because they contain all the relevant training history as well as the actual model parameters.

**Comment by JohnCraigPublic** [comment]
bencherian - for my case of loading 10 models, I do have 10 different globals (ER1, ER2, ER3,...)

On model size: I'm generating them with BrainScript.  They are essentially AlexNet models.  The transcript says that AlexNet (for the dimensions I use: 245x245x1) has about 45 million parameters.  If each parameter is stored in 4 bytes, that's 190 MB -- so the model size I'm seeing ( about 225 MB ) seems to be in the ballpark.

I'd love you to tell me there is something I'm missing and all I have to do is 'compact' my model somehow......

**Comment by zhouwangzw** [comment]
My thoughts to your questions: 
0) Please see the page [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Native-Eval-Interface) for C++ Eval related API documentation. 
1)  As @bencherian mentioned, memeroy will be released if no refeerence to the FunctionPtr is active any more. 
2) If you finish use the model, you can reset the FunctionPtr or assgin it to nullptr to release the memory (if it is not referenced elsewhere). For example: 
 ```
FunctionPtr model = Function::LoadModel(...)
 .... 
 model = nullptr;  // the memory used by model will be released if this is the only reference.
```
3) Is 250MB the file size of the model or the memory usage after loading from file? You can check the memory increasement when you load each model separately, and then compare the case when you load all 10 models. 
4) It seems 250MB is model file size? Sorry, I do not have good answer for how to distribute >100 models with your application to users. 
5) Yes, LoadModel takes time, since it reads file from disk and then builds and validates the compuation graph. You can pre-load models to make eval fast, but of course more memory is needed. Depending on your requirements, you may want to use some smart memory pool management techniques to balance memory pressure and response time. 

My 2 cents.
 Thanks,

**Comment by JohnCraigPublic** [comment]
zhouwangzw - thanks a lot for your comments.

**Comment by JohnCraigPublic** [comment]
Related: Perhaps my use of AlexNet is overkill for my problem.  Perhaps I could use a smaller network with fewer parameters and get similar performance, but with a smaller model size.  Question: is there a logical way to start with AlexNet, and make changes to it to reduce its size?  Suggestions for how to do this?  Or better to just try some other, smaller network instead of AlexNet?

**Comment by KeDengMS** [comment]
Please refer to other image classification examples like ResNet. We are also working on adding inceptionV3.

**Comment by cha-zhang** [comment]
Seems this issue is resolved. I'm closing it now. Feel free to reopen it if needed. Thanks!
