### ISSUE TITLE
Input images in Fast R-CNN

### ISSUE THREAD

**Issue by kyoro1** [Microsoft/CNTK#1901]
1) When training a CNTK FAST R-CNN model with my own photos with [tutorial page](https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN#train-on-your-own-data), the input [image size is defined as 1000 for both height and weight](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/fastrcnn.cntk):

```sh
ImageH = 1000
ImageW = 1000
```

Does it mean that the model is interpreted as a kind of extension of original AlexNet?
As far as I know, the original input image size is 224x224x3(or 227x227x3).

2) If 1. is yes, can we assume that we will distinguish more detailed images rather than the original AlexNet?

**Comment by JohnCraigPublic** [comment]
If you are using a pre-built AlexNet, then the dimensions of the images you use must match the size that the AlexNet was computed for.

Bigger images probably mean "distinguishing more detail" in some sense, and also make the Neural Network much bigger - the number of parameters you are training and the size of the resulting model file grow with the image dimensions used.

**Comment by kyoro1** [comment]
Thanks @JohnCraigPublic . As you mentioned above, I thought like `If you are using a pre-built AlexNet, then the dimensions of the images you use must match the size that the AlexNet was computed for.`

I'm confused that [BrainScript](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/fastrcnn.cntk) says the script use pretrained AlexNet model itself as in `network     = BS.Network.Load ("../../../../../PretrainedModels/AlexNet.model")`. So, input image size should be 224x224(or 227x227).

On the other hand, the input image size would be 1000(width)x1000(height) as in the part of `imageShape `

Which image size is applied?

```py
ImageH = 1000
ImageW = 1000
ImageC = 3
  : 
    BrainScriptNetworkBuilder = {
        network     = BS.Network.Load ("../../../../../PretrainedModels/AlexNet.model")
        convLayers  = BS.Network.CloneFunction(network.features, network.conv5_y, parameters = "constant")
        fcLayers    = BS.Network.CloneFunction(network.pool3, network.h2_d)

        model (features, rois) = {
            featNorm = features - 114
            convOut  = convLayers (featNorm)
            roiOut   = ROIPooling (convOut, rois, (6:6))
            fcOut    = fcLayers (roiOut)
            W        = ParameterTensor{($NumLabels$:4096), init="glorotUniform"}
            b        = ParameterTensor{$NumLabels$, init = 'zero'}
            z        = W * fcOut + b
        }.z

        imageShape = $ImageH$:$ImageW$:$ImageC$         # 1000:1000:3
        labelShape = $NumLabels$:$NumTrainROIs$         # 21:64
        ROIShape   = 4:$NumTrainROIs$                   # 4:64

        features = Input {imageShape}
        roiLabels = Input {labelShape}
        rois = Input {ROIShape}

        z = model (features, rois)
        
        ce = CrossEntropyWithSoftmax(roiLabels, z, axis = 1)
        errs = ClassificationError(roiLabels, z, axis = 1)
        
        featureNodes    = (features:rois)
        labelNodes      = (roiLabels)
        criterionNodes  = (ce)
        evaluationNodes = (errs)
        outputNodes     = (z)
    }
```

**Comment by pkranen** [comment]
For Fast R-CNN we clone the AlexNet model in two parts, the `convLayers` and the `fcLayers`. For the `convLayers` the input size does not have to match the original resolution of 224x224, since convolution and pooling are just strided over the input volume. Hence, we can change the input resolution, e.g. as in our case to 1000x1000. (The number of weights for the conv filters that you train stay the same, they are just applied at more spatial positions and hence more computations are needed.) The resulting convolutional feature map `convOut` is then of course also larger than the one from the original AlexNet. `convOut` is fed into the ROIPooling layer along with the region proposals (ROI). The ROIPooling layer then cuts out that part from the convolutional feature map that corresponds to the ROI and applies max-pooling to resize it to the desired output size of 6x6xdepth in our case, which is exactly the input volume size that is expected by the `fcLayers` from the original AlexNet.

**Comment by kyoro1** [comment]
@pkranen Thanks:)
