### ISSUE TITLE
How to change variables for Fast R-CNN in changing pretrained model

### ISSUE THREAD

**Issue by kyoro1** [Microsoft/CNTK#1905]
In case that we use Fast R-CNN with default setting, prepared script use AlexNet as PreTrainedModel in `A2_RunWithPyModel.py`.

```py
# model specific variables (only AlexNet for now)
base_model = "AlexNet"
if base_model == "AlexNet":
    model_file = "../../../../../PretrainedModels/AlexNet.model"
    feature_node_name = "features"
    last_conv_node_name = "conv5.y"
    pool_node_name = "pool3"
    last_hidden_node_name = "h2_d"
    roi_dim = 6
```

Then, how do we set up with other PreTrainedModel like ResNet18, ResNet152 or others in using Fast R-CNN? 
In the sample above, `feature_node_name = "features"` and `last_conv_node_name = "conv5.y"` for AlexNet, then, how do we set those parameters like `feature_node_name` or `last_conv_node_name` from pretrained model in CNTK.

(Of course, I understand these variables are prepared only for AlexNet, but it'd be glad if I know which variables should be changed and how I can change them.)

**Comment by pkranen** [comment]
How to use a different base model for transfer learning is described at [https://github.com/Microsoft/CNTK/wiki/Build-your-own-image-classifier-using-Transfer-Learning#using-a-different-base-model](https://github.com/Microsoft/CNTK/wiki/Build-your-own-image-classifier-using-Transfer-Learning#using-a-different-base-model), the same applies here for Fast R-CNN. Note that ResNet is currently not an option for Fast R-CNN in CNTK since the ROIPooling layer does not yet support average pooling. You could use VGG for example (see also this [pull request](https://github.com/Microsoft/CNTK/pull/1895)).
