### ISSUE TITLE
Grayscale image in C# evaluation

### ISSUE THREAD

**Issue by Keyvanrad-Github** [Microsoft/CNTK#1913]
Hi,

I'm building a network for gray-scale images in my dataset.  when I use the model in C# like the evaluation scripts in CNTKLibraryCSEvalCPUOnlyExamples, resize and ParallelExtractHWC functions assume the image must be in rgb and therefore the outputs are not valid. How can I fix this problem?
In another word, are any evaluation script in C# for gray-scale image (like MNIST) to help me?

Thanks,
Mohammad Ali

**Comment by tobyclh** [comment]
What you need is a new model that takes only 1 channel
if that's too much work, you can try to popularize all 3 channels with intensity value and see if that is any good

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)

**Comment by Keyvanrad-Github** [comment]
Thanks tobyclh, using all 3 channels with intensity value is a good idea but the time is important for me and your method takes 3 times slower than using one channel. I have not any problem in using gray-scale images in brain script but the problem is in evaluation in C#.

**Comment by pkranen** [comment]
As I understand your issue you already have a trained model that expects images with a single channel as input, correct? To feed gray scale images with a single channel into your model modify the `EvaluationSingleImage(...)` method in `CNTKLibraryCSEvalExamples.cs` as follows: if your input images are not already gray scale convert them after you create the bmp from file (line 68). You can see examples of how to convert to gray scale [here](https://web.archive.org/web/20110827032809/http://www.switchonthecode.com/tutorials/csharp-tutorial-convert-a-color-image-to-grayscale). Next you need only need the first third of the list that is returned by `ParallelExtractCHW()`, since you only need one channel. One way to achieve this is to modify `ParallelExtractCHW()` in line 25:
```
            var features = new byte[imageWidth * imageHeight];
```
and line 40:
```
            Parallel.For(0, imageHeight, (int h) =>
            {
                Parallel.For(0, imageWidth, (int w) =>
                {
                    features[channelStride + imageWidth * h + w] = rgbValues[mapPixel(h, w, 0)];
                });
            });
```
Let us know if this answers your question.

**Comment by pkranen** [comment]
Closing this issue, feel free to reopen if questions remain.
