### ISSUE TITLE
Old models predict different results on CNTK 2.0 rc3

### ISSUE THREAD

**Issue by ivan-alles** [Microsoft/CNTK#1921]
I have a lot of convnet classifiers for images trained with CNTK 1.7 Brainscript, which is built under VS 2013. I evaluated them with EvalDll. 

Now I switched to CNTK 2.0 rc3 and VS 2015, using Cntk.Eval-2.0rc3.dll. Many (but not all) of my models predict now different results on the same data.

Retraining all the models by the new CNTK is not an option, there are too many.

How else could I solve this issue?

**Comment by cha-zhang** [comment]
How big is the difference? It could be due to various reasons, do you have a simple model we can test with?

**Comment by ivan-alles** [comment]
For example, an old binary classifier predicted [-1, 3], and now it is something like [4, 1.5]. 

How can I give you the model and data? I could prepare a VS 2013 and VS 2015 projects with example model and data, is it ok?

**Comment by cha-zhang** [comment]
Yes, that'll be great. We will definitely take a look.

**Comment by ivan-alles** [comment]
I created a self-contained package with the models, samples, code and official CNTK 1.7 files. There are VS 2013 and 2015 solutions and projects. One sample behaves differently in these versions. I also have problems with even older models (described here [https://github.com/Microsoft/CNTK/issues/865](url). See my comments in the main file upgrade_to_cntk_20.cpp. 

Link to the zip-archive: [https://drive.google.com/open?id=0Bw6ARl6knOSHQ2ZjM1NobmN6OWc](url)

**Comment by cha-zhang** [comment]
Thanks! We will look into that.

**Comment by zhouwangzw** [comment]
We did some investigation and found the reason. At the end of last year, we tuned Convolution Engine CPU implementation to generate the same result as that using CuDNN, so that the model trained with GPU will produce the same result as that on CPU-Only device. However, this unfortunately led to different results for models trained with earlier CNTK versions on CPU. We are sorry for that. If it is not possible for you to re-train your models but you want to upgrade to Release 2.0, I can try to provide your a work-around to create the same result for CPU-Only version, but this means that your code is branched from the main tree and you have to maintain by yourself.

Sorry for inconvenience!

**Comment by ivan-alles** [comment]
Thank you for your effort. I've already found a solution. I create a C-only wrapper for my old patched CNTK 1.7 built with VS 2013. I use this wrapper for the old models. 

New models are created with CNTK 2.0 and python, and are evaluated with the new CNTK C++ API.
