### ISSUE TITLE
TensorBoard implementation error

### ISSUE THREAD

**Issue by min6434** [Microsoft/CNTK#1923]
I want to use tensorboard to visualize graph, learning progress and so on.
So I followed the tutorial but the result shows an error.

raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'ProgressWriter' object has no attribute 'append'

How can I solve this?
```
    # progress writers
    progress_writers = ProgressPrinter(tag='Training', num_epochs=max_epochs)
    tensorboard_logdir= 'log'
    tensorboard_writer = None
    if tensorboard_logdir is not None:
        tensorboard_writer = TensorBoardProgressWriter(freq=10, log_dir=tensorboard_logdir, model=z)
        progress_writers.append(tensorboard_writer)
   
    trainer = Trainer(z, (ce, pe), [learner], [tensorboard_writer])
```

**Comment by bencherian** [comment]
`Trainer` takes a list of `ProgressWriters` as an argument. You seem to be arbitrarily mixing lists and raw objects in your code. If you don't want to output both tensorboard log data and print log messages you can just remove the offending line. Otherwise make progress_writers a list and then use that list in the construction of trainer (see below for example). For future reference questions like this are probably better suited to (and will likely get a quicker response on) StackOverflow. Github Issues are more intended for problems you are facing with the actual package (e.g., bugs and feature enhancements).

```Python
# progress writers
progress_writers = [ProgressPrinter(tag='Training', num_epochs=max_epochs)]
tensorboard_logdir= 'log'
tensorboard_writer = None
if tensorboard_logdir is not None:
    tensorboard_writer = TensorBoardProgressWriter(freq=10, log_dir=tensorboard_logdir, model=z)
    progress_writers.append(tensorboard_writer)

trainer = Trainer(z, (ce, pe), [learner], progress_writers)
```
