### ISSUE TITLE
Documentation - BlockMomentumSGD - model aggregation stats

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1954]
BlockMomentumSGD produces the following output:
```
(model aggregation stats): 110-th sync point was hit, introducing a ***x***-seconds latency this time; accumulated time on sync point = ***y*** seconds , average latency = ***z*** seconds
```
among other stats. can anyone point to what they mean? latencies are high if parallel training is run on dissimilar nodes - is that an indication of one of the nodes waiting for synch point (in given number of samples) among all nodes before proceeding further?

**Comment by sayanpa** [comment]
Here is my understanding:
x = time it takes to execute a node
y = time it takes for all the nodes to finish
z = average time taken to execute all the nodes

Given this issue is open for two months. I am going to close it with the assumption that the answer is satisfactory. If clarification needed, please reopen or open a new issue.
