### ISSUE TITLE
ImageHandsOn.cntk     EXCEPTION occurred: Plugin not found: 'ImageReader.dll'

### ISSUE THREAD

**Issue by huishaoli** [Microsoft/CNTK#1973]
when I run the the ImageHandsOn.cntk. It tells me  Plugin not found: 'ImageReader.dll'. I can't find 'ImageReader.dll' in any folder,could you please tell me how to creat the 'ImageReader.dll' or where to find it. Thank you!

**Comment by cha-zhang** [comment]
Did you install OpenCV?

**Comment by wolfma61** [comment]
I'm closing this due to lacking feedback. 
Please also not that library names have changed before the release of CNTK2 (see https://docs.microsoft.com/en-us/cognitive-toolkit/cntk-shared-libraries-naming-format), ImageReader.dll doesn't exist anymore under this name. Your error messages hint at an older version of CNTK.
