### ISSUE TITLE
is there any other way to use multiple GPU?

### ISSUE THREAD

**Issue by DabiaoMa** [Microsoft/CNTK#1982]
It seems like in order to use multiple GPU, we have to create an object of class "MinibatchSource". But to create it, we have to create a "deserializer".

While could anyone show me how to create "MinibatchSource" or maybe there is another method available?

**Comment by bencherian** [comment]
If using Python you should extend `UserMinibatchSource` as [described in the documentation.](https://cntk.ai/pythondocs/extend.html#user-defined-minibatch-sources). You need to implement the `next_minibatch` method so that it returns data appropriately for multiple workers (unlike the example implementation which does not support multiple workers.)
