### ISSUE TITLE
advice about CTC

### ISSUE THREAD

**Issue by DabiaoMa** [Microsoft/CNTK#1995]
I have just realized that to use cntk version of CTC, we have to provide segmented labels which do not take advantages of CTC.

Maybe the authors could consider to merge Baidu's Wrap-CTC with cntk, just as what mxnet and theano has done.

**Comment by vmazalov** [comment]
You don't need segmented labels to use CTC. The current CTC example is referencing segmented labels file just for demonstration (simply because it's already in the repo): https://raw.githubusercontent.com/Microsoft/CNTK/master/Tests/EndToEndTests/Speech/Data/glob_0000.mlf

During training the label boundaries are ignored.
