### ISSUE TITLE
A question on Tutorial 204

### ISSUE THREAD

**Issue by meijiesky** [Microsoft/CNTK#2047]
In Tutorial 204, attached below is part of the program to create the model. I am having some trouble understanding  (C.layers.Label('encoded_h'), C.layers.Label('encoded_c')). Why are there two label layers? If we want to get the output of the encoder, I suppose we only need to add one label layer at the end.

Moreover, I run the whole program. After I load the model, it works when I try model.encoded_h but model.encoded_c seems not to exist. It shows on the console that AttributeError: 'Variable' object has no attribute 'encoded_c'.

My another concern is whether the output of model.encoded_h is the encoded vector that is going to be sent to the decoder.

Can anyone help me with this? Thank you so much!

# create the s2s model
def create_model(): # :: (history*, input*) -> logP(w)*
    
    # Embedding: (input*) --> embedded_input*
    embed = C.layers.Embedding(embedding_dim, name='embed') if use_embedding else identity
    
    # Encoder: (input*) --> (h0, c0)
    # Create multiple layers of LSTMs by passing the output of the i-th layer
    # to the (i+1)th layer as its input
    # Note: We go_backwards for the plain model, but forward for the attention model.
    with C.layers.default_options(enable_self_stabilization=True, go_backwards=not use_attention):
        LastRecurrence = C.layers.Fold if not use_attention else C.layers.Recurrence
        encode = C.layers.Sequential([
            embed,
            C.layers.Stabilizer(),
            C.layers.For(range(num_layers-1), lambda:
                C.layers.Recurrence(C.layers.LSTM(hidden_dim))),
            LastRecurrence(C.layers.LSTM(hidden_dim), return_full_state=True),
            (C.layers.Label('encoded_h'), C.layers.Label('encoded_c')),
        ])
    .........

**Comment by wdarling** [comment]
Hi, you're right that if you want the output of the encoder that you only need a single label. The actual hidden state that we think of as a 'thought vector' or as 'output' of the LSTM is `encoded_h`. That is the one that is sent to the decoder when you are using attention and those vectors (`encoded_h` has a dynamic axis of course) are the vectors that the attention model attends to, creates a weighted sum of, and uses to create an augmented version of the decoder's hidden state. So, why is there also the `encoded_c`?

In an LSTM, while the "output" is the hidden state that we call `encoded_h`, there is also another set of values that are being updated: the memory cell, which we call `encoded_c`. At each time step, first the memory cell is updated, and then the actual output is basically the memory cell applied to a forget gate and the output of that operation is the hidden state. Now, when you're NOT using attention, the way that the decoder works is that it is initialized by setting its initial state to the final state of the encoder. Since we want it to match the exact state of what the encoder looked like at that point, we need both the hidden state `encoded_h` and the memory cell `encoded_c`. This is also why when we set up the `LastRecurrence` that we set the flag `return_full_state=True`. If we didn't, then the LSTM recurrence would only return the hidden state. Consequently, if you're not using attention, then you never make use of the memory cell `encoded_c` later on, and the graph gets rid of the node and therefore you can't find it. If you do want to take a look at it, turn off attention, and it will be used, and then you'll be able to find it.

**Comment by meijiesky** [comment]
Thanks. You are very helpful!
