### ISSUE TITLE
Aligning the terminology used by CNTK with usual ML practices

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2056]
CNTK has its own terminology, and it's does not feel fully aligned with the rest of the world.

For example:

* a _sequence_ (CNTK) is typically called an _instance_
* a _sample_ (CNTK) is typically called a _feature_
* _input stream_ (plural, CNTK) is typically a _feature column_ (arguably TF terminology) or a _feature_
* the _criterion_ (CNTK) is typically called the _goal_ or the _loss_.
* the _evaluation_ (CNTK) is typically a _metric_

Two authoritative sources for machine learning terminology:
* http://www.deeplearningbook.org/
* http://martin.zinkevich.org/rules_of_ml/rules_of_ml.pdf

There are probably more examples to be found. Changing the terminology later on will be an even greater pain than it is today. Yet, the CNTK solution would significantly gain in transparency by adopting established terminology.

**Comment by ujjwal-researcher** [comment]
@vermorel 
I think that while there are these differences, the CNTK terms make a lot of sense and there are good reasons to keep them. 
It would be better to make a note of terms used in CNTK literature, but removing these terminology would be catastrophic or at least imprudent. A note of these terms would be very helpful.

I do agree with you on the issue of _sequence_ (CNTK) vs instance. But I would also like to give you my opinions in a little detail on the terminology examples you have posed.


- _Criterion_ (CNTK) makes sense because, it is the basis on which a network is trained. While the term _goal_ is also very sensible, I have never liked the term loss too much. This is because _loss_ as a term does not make much sense and does not give an intuitive understanding of what is being done. 

- _Input stream_ (CNTK) is also a much better terminology than feature column. The term _feature_ would make sense usually in _regression_ based tasks or in cases where some pre-extracted set of numbers are provided as an input to a CNN. However in the context of computer vision where images are provided as an input, the term _feature_ does not make much sense and infact contradicts with the usual view of the term feature. In the case of CNNs, they function as feature extractors and hence the output of a CNN should be called as a feature, not the input. The _input stream_ term however is much more sensible. It implies a flow of data coming into a network and hence this term is independent of the context in which it is used.

- _evaluation_(CNTK) is another sensible term. _Metric_ refers to a measure. In CNTK _metric_ is used to refer to the quantity which measures a network's performance. This is what is reported by `ProgressWriter`. The use of _evaluation_ by CNTK to refer to the process of computing forward pass over a network is a natural way in which the process is clarified.

- _sample_ (CNTK) is more sensible than feature due to the same reason as described two points above.

- _sequence_ (CNTK) is a point where I do agree with your comment. I think calling it an _instance_ is a much more prudent thing to do. Sequence (CNTK)  restricts the natural usage to speech or NLP applications while instance makes it  application independent.

I think it is important to make CNTK a more independent library in terms of its take on machine learning practices and use of sensible terms (while describing them !!) as against going after the popular terminology is much more important.

**Comment by vermorel** [comment]
@ujjwal-researcher Thank you very much for this excellent piece of feedback. The content of your post would deserve a page in the public CNTK documentation. It would really help a lot.

**Comment by ujjwal-researcher** [comment]
Thank you very much if you found it helpful  :)

**Comment by ldmtwo** [comment]
Thank you both for clarifying and translating the confusion. This would be most appropriate on the getting started page.

**Comment by sayanpa** [comment]
Incorporated your changes into our introductory CNTK 101 tutorial.
