### ISSUE TITLE
G2P: how to output top N scores and corresponding sequences

### ISSUE THREAD

**Issue by irrawaddy28** [Microsoft/CNTK#2105]
I tried running the G2P.cntk given in the CNTK/Examples directory. Training went fine. For the test data, I want to output both the top N scores and the corresponding phoneme sequences. However, the write action outputs a "*.decodeOut" file whose contents look something like this:

**~T ~M ~M I ' '
~T ~M ~M I ' ' ' ' ~OW**

What is the meaning of this? How can I get the top N scores and sequences? (I use beamDepth=3 for beam decoding)

Changes to the CNTK.core.bs file to tag the scores as output nodes didn't help
_expandedPathScoresOut = Pass(expandedPathScores, tag='output')
topPathScoresOut = Pass(topPathScores, tag='output')_

**Comment by frankseide** [comment]
This is not currently supported, and may also not give you the expected result. If you consider what a beam decoder does: It maintains a set of hypotheses, expands them from step to step, prunes the set to the locally best N hypotheses, maintains a backpointer to from which beam depth each entry came from, and at the end traces back the backpointer chain.

In order to get N-best hypotheses, you would need to trace back the top N final hypotheses. The traceback is realized by a multiplication with a N-hot NxN matrix. You would have to modify the code to perform the traceback on N hypotheses in parallel.

This may not give you good results though--I would expect the top N paths to merge a few steps before the end, so that your hypotheses will end up all beginning with the same string, and only differ in the last few tokens.
