### ISSUE TITLE
Is there any sample code show how use precomputed embeddings

### ISSUE THREAD

**Issue by liyzhang** [Microsoft/CNTK#2114]
I loaded embeddings from a file (a 2293 x 300 matrix) and pass it to the embedding layer. when I do the training how shall I do the embedding look up? 

at https://www.cntk.ai/pythondocs/layerref.html#embedding, there's some sample code
input = Input(87636, is_sparse=True)   # word sequence, as one-hot vector, sparse format
embEn = Embedding(300, weights=np.load_txt('embedding-en.txt'))(w) # embedding from disk

which module shall I import to use Input? 
input seems not used, is it an error?
what is w at the end of 2nd statement?

**Comment by cha-zhang** [comment]
Please check our sequence to sequence example: 
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_204_Sequence_To_Sequence.ipynb

**Comment by liyzhang** [comment]
looks like the embedding in the tutorial is also learnt

if my feature vector contains two items, { wordvector_sequenceId, custom_feature}, and I supply it to the embedding layer, will the embedding layer automatically use the first to look up the embedding? how the customized feature flow to the rest of the layers. Any tutorial on it?

**Comment by n17s** [comment]
The embedding lookup is typically done by having a dictionary mapping words to indices and another dictionary for the reverse mapping.

The `Input` in the example you refer to is just an `input_variable`; this is just a typo. Also the `w` should have been `input`.

There's no tutorial on using precomputed embeddings. There's an example in a not-yet-published branch where some words have their embeddings learned and some have their embeddings fixed. You can access it [here](https://github.com/Microsoft/CNTK/tree/nikosk/bidaf/Examples/Text/BidirectionalAttentionFlow). It is quite big to follow but if you manage to follow it you can learn a lot.

If your feature vector contains two things, you should probably slice it so that you can feed one part to the embedding and another one to a dense layer. You can also create two separate input_variables if you are willing to reprocess your data.

**Comment by n17s** [comment]
Closing. Feel free to reopen.
