### ISSUE TITLE
Keras and SKLearn Multi-GPU Support on CNTK

### ISSUE THREAD

**Issue by hwchong** [Microsoft/CNTK#2155]
Hello, would anyone have a snippet explaining how to utilise multiple-GPUs to train a DNN using Keras as the front-end? Alternatively if that's not possible, would it be possible to parallelise k-fold cross validation training on multiple GPUs using SKLearn on top of Keras and CNTK?

**Comment by cha-zhang** [comment]
To use multi-GPU to train with Keras model, you will need CNTK's data reader and trainers. 

@souptc, could you create a simple example to show how this can be done?

**Comment by souptc** [comment]
Sure, I will try to make an example first.

**Comment by rsharnag** [comment]
@souptc : Waiting for an example for this. Thanks.

**Comment by cha-zhang** [comment]
It's already posted: 
https://docs.microsoft.com/en-us/cognitive-toolkit/Using-CNTK-MultiGPU-Support-with-Keras

**Comment by ViaFerrata** [comment]
Thanks a lot for the detailed example! 
However I wonder, how this works if one would like to use keras with `fit_generator` instead of `fit`?

Do you have to kind of divide the dataset in the generator, which means that you pass a start&end parameter to the gen?
I.e. draw image 1-1000 from the gen with rank 1, 1001-2000 with rank 2 etc. ?
