### ISSUE TITLE
Scale up evaluation to larger image

### ISSUE THREAD

**Issue by zoli1984** [Microsoft/CNTK#2157]
Hello,

I have traind my CNN for 32x32 images. The network is consist of conv and pool layers, and in the end one fully connected layer to make 2 output classes.  I would like to eval a 320x320 picture in a following way:

From the large image I get 32x32 pieces. This pieces are not disjunct, the have 24 * 32 pixels common part. So from 320x320 picture I will have [(320-32)/8+1] * [(320-32)/8+1] small pictures (37 * 37=1369 pictures with 32x32 size)

I would like to eval this 1369 pictures with my network. I can do it with 1369 different evals. But the performance is important for me, and I would like to make it faster.

I have 3x3 filters and 3x3 poolings. Because I have 24*32 common parts I eval this parts multiple times in 1369 evals, however the result is always same.

Is there any support in framework to "scale up" eval function for larger images with optimized calculations? For example eval the 320x320 picture and get 1369 * 2 outputs to avoid redundant calculations.

Best regards

**Comment by ujjwal-researcher** [comment]
Solution 1 
--------------
Before invoking CNTK for evaluation, you can run an intermediate function which will do the `32 x 32` extractions for you. Then you can follow by creating a `MiniBatchSource()` and doing evaluation in the normal manner. 

Solution 2
--------------

This solution requires you to modify the codebase of CNTK but it is doable if you are ready to spend some time over it. You need to implement this extraction of `32 x 32` pieces through a transformation function. There is an option of `multiview10` cropping which is different from what you want, but shares a similarity in the fact that it leads to extraction of `10` patches from the image instead of one. On similar grounds you can create a new cropping-mode for your purpose and this can be used for your evaluation. 
This solution is more convenient (albeit a little involved) because you do not need to do the extraction before the evaluation. 
The relevant files can be found in  https://github.com/Microsoft/CNTK/blob/master/Source/Readers/ImageReader/ImageTransformers.cpp and in the corresponding parent folder.

**Comment by pkranen** [comment]
Thanks ujjwal for your proposals. While they would probably work, they still both compute all the common parts from the overlaps for each 32x32 tile again. A simpler and more efficient solution would be to use ROI pooling for this as in [Fast R-CNN](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/A2_RunWithPyModel.py#L112), see also this [tutorial](https://docs.microsoft.com/en-us/cognitive-toolkit/object-detection-using-fast-r-cnn). For your case you would use a 320x320 image as input and use the strided 32x32 regions as 'hardcoded' regions of interest. Also in your case you could leave the trained classification head when cloning the fc layers since you don't change the class labels.
