### ISSUE TITLE
BS.Sequences.*Fold* functions problem (on signature of _Fold)

### ISSUE THREAD

**Issue by Blealtan** [Microsoft/CNTK#2172]
I was looking for a similar interface to Python API's `cntk.layers.sequence.Fold` in BrainScript reference but failed. Later on I found this in `CNTK.core.bs`:

```
# fold left/right: Reduce entire sequence by applying binaryOp, e.g. FoldL (Plus, 0, input)
# LINQ calls this Aggregate; and may or may not specify the seed value; and allows a predicate
FoldL (binaryOp, x0, x) = _Fold (PastValue,   binaryOp, x0, x)
FoldR (binaryOp, x0, x) = _Fold (FutureValue, binaryOp, x0, x)
_Fold (binaryOp, x0, x) = [
    acc = binaryOp (x, if Loop.IsFirst (x) then x0 else PastValue (acc))
    out = Last (acc)
].out
```

I tried to use `FoldL` but it failed with

```
EXCEPTION occurred. while evaluating: D:\cntk\cntk/cntk.core.bs(877): function expects 3 positional parameters, 4 were provided
```

Then back to the code snippet, it's obvious that the signatures of _Fold in its definition and usage are different!

However those functions are not mentioned in BrainScript's Function Reference page; I wonder if those are functions intended for use, or they are just under development while mistakenly came with release 2.0? Looking forward to some explanation.

(In the meantime I'll go on with manual working around with `PastValue` ;)

**Comment by liqunfu** [comment]
@Blealtan. Fold(L,R) are not called from anywhere in the script. You probably can try to correct _Fold's signature to take a Op and call it instead of the "PastValue". It is recommended to work with Python in order to take full advantage of current and future development of CNTK. There are Python interfaces that you cannot find counterpart in BrainScript. I will close this issue for now. Thanks.
