### ISSUE TITLE
MPI missing in docker image

### ISSUE THREAD

**Issue by Stonesjtu** [Microsoft/CNTK#2191]
Pulled the newest docker image by `docker pull microsoft/cntk` and then tried to run with `mpiexec` to get multi-GPU support.
But the MPI binaries are not installed in the official docker image.
And I also tried to install an `openmpi` from ubuntu package manager, but it can't start as expected.

**Comment by liqunfu** [comment]
@Stonesjtu 
May you do this first? (No need to install openmpi)
export PATH=$PATH:~/openmpi/bin

**Comment by Stonesjtu** [comment]
@liqunfu
Thanks for your solution, an additional error says that `mpi4py` is missing.
I can solve it by `pip install mpi4py`, but it should be better if you can make the mpi version available out of the box. That's what docker means.

**Comment by mahilleb-msft** [comment]
@Stonesjtu - could you clarify where the "mpi4py is missing" message is coming from? I.e., what are your repro steps.
Assuming you activated CNTK (source "/cntk/activate-cntk") the MPI libraries should be in path, but mpiexec is not. This should be fixed by @liqunfu, and we'll add it to the default configuration in the future.

**Comment by mahilleb-msft** [comment]
@alexeyo26 - we should extend the PATH in the DockerHub images to include mpiexec...

**Comment by alexeyo26** [comment]
The fix is in master. For Docker Hub images it will be in the next release (v.2.2)
