### ISSUE TITLE
matching between two sequences in cntk

### ISSUE THREAD

**Issue by rajarsheem** [Microsoft/CNTK#2217]
I have two mini-batch of sequences :
```
a = C.sequence.input_variable((10))
b = C.sequence.input_variable((10)) 
```

Both ```a``` and ```b``` has variable-length sequences.
I want to do matching between them where matching is defined as: match (eg. dot product) token at each time step of ```a``` with token at every time step of ```b``` .

How can I do this?

**Comment by rajarsheem** [comment]
@sayanpa Any thoughts on this. Please tell me if you need more information about the scenario .

**Comment by sayanpa** [comment]
Can you extend CNTK 202 model, to build a input->model->output representation for both input a and b. Then do a cosine distance between the two. This is similar to DSSM.

**Comment by rajarsheem** [comment]
Ok. But I was going to compute scores between every word of  a and b. Is that possible right now ?

**Comment by meijiesky** [comment]
@rajarsheem If a and b are of the same length, you can use C.classification_error. Refer to https://cntk.ai/pythondocs/cntk.metrics.html.

**Comment by rajarsheem** [comment]
Hey, let me give an vivid yet simple example:   (it is similar to the gated-attention in R-NET model)
a = [ [1, 2, 3] , [4, 5] ]
b = [[6, 7], [8]]
So, for the first examples of a and b,
match(b->a) = [6*1+ 6*2 + 6*3, 7*1 + 7*2 + 7*3] .
Same thing will happen for the corresponding second examples in the mini-batch.

**Comment by rajarsheem** [comment]
At the base level, a score is getting computed S(i,j) = score between ith element of a and jth element of b where score can be (addition, dot etc.)

**Comment by n17s** [comment]
If the score is as in your example then you can just do 
```
C.sequence.reduce_sum(a)*b
```
This would be much faster than a generic solution.

**Comment by rajarsheem** [comment]
Tried to do the same:
```
a = C.sequence.input_variable((1))
b = C.sequence.input_variable((1))
c = C.sequence.reduce_sum(a) * b
c.eval({a: [[1, 2, 3],[4, 5]], b: [[6, 7], [8]]})
```
but got:
Operation 'ElementTimes': Operand 'Input('Input21', [#, *], [1])' has dynamic axes, that do not match the dynamic axes '[#]' of the other operands.

**Comment by n17s** [comment]
Right, I should have elaborated a little more. First, your sequences are of different lengths and therefore you need to specify two dynamic axes, otherwise the same axis is used for both `a` and `b` and CNTK will complain that they have the same axis but different lengths. Second, you will need to broadcast the sum along `b`. Here's something that works for me:
```python
axisa = C.Axis.new_unique_dynamic_axis('a')
axisb = C.Axis.new_unique_dynamic_axis('b')
a = C.sequence.input_variable(1, sequence_axis=axisa)
b = C.sequence.input_variable(1, sequence_axis=axisb)
c = C.sequence.broadcast_as(C.sequence.reduce_sum(a), b) * b
c.eval({a: [[1, 2, 3],[4, 5]], b: [[6, 7], [8]]})
[array([[ 36.],
       [ 42.]], dtype=float32), array([[ 72.]], dtype=float32)]
```

**Comment by rajarsheem** [comment]
Hi, this works like a charm! Thanks! I didn't know about the fact that it was using same axis for both a and b.

I wanted to, however, make it a little bit complicated. What if, instead of summing the elements of a, I wanted to keep the score between a_i and b_j as it is  ? For eg.,
match(b->a) = [ [[6 * 1, 6 * 2, 6 * 3], [7 * 1, 7 * 2, 7 * 3]], [[8 * 4, 8 * 5]] ].
One motive to do that might be _weighted sum_ of a where the weights are, say, softmax([6 * 1, 6 *2, 6 * 3]).

**Comment by n17s** [comment]
A generic solution involves the following steps
```
static_b, mask = C.sequence.unpack(b, neutral_value).outputs
scores = your_score(a, static_b)
```
The first line will convert the b sequence into a static tensor with one more axis than b. Because of packing, some elements of this tensor will be invalid(in your example the element next to the 8) and those will be indicated by the `mask`. The `neutral_value` will be placed as a dummy value in the static_b tensor wherever data was missing. Depending on your score you might be able to arrange for the `neutral_value` to not affect the final score (e.g. if your score is a dot product a 0 would be a good choice, if it involves a softmax -infinity or something close to that would be a good choice). The second line can now have access to each element of a and all the elements of b. For a dot product `static_b` is a matrix and one element of `a` is a vector so a matrix vector multiplication will result in a sequence whose elements are all inner products between the corresponding element of a and all elements of `b`.

**Comment by n17s** [comment]
Closing. Feel free to reopen.

**Comment by rajarsheem** [comment]
I didn't get much time to get back to this yet. Will probably reopen if the issue persists with me.
Btw, as a suggestion, how about more docs and tutorials on sequences ?
