### ISSUE TITLE
How to open/use Output .dnn files

### ISSUE THREAD

**Issue by byjackchen** [Microsoft/CNTK#228]
Hi,
Can anyone please explain how should I interpret the output files under the output folder. After run the examples, I am not able to see any .txt file under the output folder. But there are a lot of .dnn. files. I am totally new to this and have no ideas about how to open/use the output files. Thanks!
![image](https://cloud.githubusercontent.com/assets/12945899/13721422/6b730a7e-e7ec-11e5-8723-917060e87463.png)

**Comment by summerQing307** [comment]
you can use the dump command

**Comment by 1132520084** [comment]
In the action "write", set up the outputNodeNames.

**Comment by KolyaIvankov** [comment]
Hey, @byjackchen have you found a solution to your problem? Facing just the same newbie issue of incorporating the calculated model into my project.

**Comment by frankseide** [comment]
The .dnn files are binary model files. You get multiple as a result of checkpointing (which allows to restart in case your job crashes e.g. due to a full disk or a reboot), where the numeric index is the epoch index. The final model is the one without numeric suffix.

Loading model parameters from a model into an external program is a little involved. The current solution is the dump command, which dumps the names of all nodes, plus their values if they are learned parameters. The [first tutorial](https://github.com/Microsoft/CNTK/wiki/Tutorial) has an example. You would have to define an action and execute it:

    DumpNodeInfo = [
        action = "dumpNode"
        printValues = true
    ]

then say

    command='DumpNodeInfo'

This will give you a text file that contains all model parameters. You will then still need some effort to separate them into individual model parameters.

We have been discussing internally to make this easier. Specifically a variant that writes out all model parameters into separate files, where each file has a very simple structure that is easy to ingest from your own code, e.g. Matlab or a Python program. But this has not been implemented so far.

**Comment by dongyu888** [comment]
Actually, you can already dump one or multiple nodes’ information to files. Check https://github.com/Microsoft/CNTK/wiki/Top-level-commands and search for dumpNode.
