### ISSUE TITLE
Using cntk in Unity problem

### ISSUE THREAD

**Issue by wendy7707** [Microsoft/CNTK#2283]
I tried to use cntk in unity, but I tried to run "using Microsoft.MSR.CNTK.Extensibility.Managed", it always shows error"Missing MSR in Microsoft", and I always change the AnyCPU to X64. Please help me to fix this problem, thanks!

**Comment by tobyclh** [comment]
Couldn't get back to you since you asked me on some unrelated repo,
My version of UnityCNTK was made half a year ago with ~ CNTK 0.8. 
you might have to sort out some dependencies problems suggested here.
https://docs.microsoft.com/en-us/cognitive-toolkit/Archive/EvalDLL-Evaluation-on-Windows
On top of that unity dll has its own settings that you might have to fix (don't have them in my head anymore)
I will try to go back to it in winter if my papers go through just fine! Good luck

**Comment by cha-zhang** [comment]
Have this been resolved if you upgrade to the latest version?

**Comment by ebarsoumMS** [comment]
Please activate if the issue still there.
