### ISSUE TITLE
Reproductivity on Faster R-CNN

### ISSUE THREAD

**Issue by kyoro1** [Microsoft/CNTK#2302]
When plural executing Faster R-CNN modules with `run_faster_rcnn.py`, the results like `mAP` were different even with the same input images and other parameters.

In checking `FasterRCNN_config.py`, it seems to be able to set `__C.RND_SEED = 3` as random seed. Then, do we have to set other settings in order to obtain the same results for the same input data?

**Comment by spandantiwari** [comment]
Yes, there are some non-deterministic elements in the computation in FasterRCNN which is you are not seeing run-to-run reproducibility. Setting `RND_SEED `helps, but that does not cover all the elements. For example, the pooling operation, that uses cuDNN under the hood, is non-deterministic. Also, there are a couple of sorting operations (e.g. in proposal_layer.py) that are non-deterministic. It is one of the open items that we plan to address (no ETA, though). You can fix the first issue by setting `forceDeterministicAlgorithms=true` at the top or in the config. But you may still see some differences due to the second one.
