### ISSUE TITLE
Error with __init__() function in "proposal_layer.py" when running Faster RCNN example

### ISSUE THREAD

**Issue by Thanh-Hung-Nguyen** [Microsoft/CNTK#2334]
File "C:\CNTK-master\Examples\Image\Detection\FasterRCNN\..\utils\rpn\proposal_layer.py", line 24, in __init__
    super(ProposalLayer, self).__init__([arg1, arg2, arg3], attributes=layer_config, name=name)
TypeError: __init__() got an unexpected keyword argument 'attributes'

**Comment by spandantiwari** [comment]
This looks like possibly a mismatch between the CNTK version and the fasterRCNN example version. Are you running the example from the latest master? If you are then you need to build and install CNTK from the latest master. There have been several changes in the example since release 2.1. Alternatively, you can wait a couple of days for release 2.2 that is coming out soon (early next week) and install that the try running the example. Please reopen this issue if this is still a problem.
