### ISSUE TITLE
Why cudnn is not called in GPU version when profiling?

### ISSUE THREAD

**Issue by xhzhao** [Microsoft/CNTK#239]
I build an GPU version with TitanX, and download a benchmark for CNTK(https://github.com/Alexey-Kamenev/Benchmarks).
When i use nvprof command to analyse the cost time in detail, there is no cudnn calls.
[profile_1.txt](https://github.com/Microsoft/CNTK/files/175326/profile_1.txt)

Then i write some trace code in the source file, and found out that the convolution engine is not CudnnConvolutionEngine , but DefaultConvolutionEngine.
![image](https://cloud.githubusercontent.com/assets/17486215/13802966/fa44fc7a-eb7b-11e5-9787-87297523b658.png)

the log is:

[AlexNet_Train_batchsize_256.txt](https://github.com/Microsoft/CNTK/files/175332/AlexNet_Train_batchsize_256.txt)

![image](https://cloud.githubusercontent.com/assets/17486215/13803010/4ca180d8-eb7c-11e5-8766-a8ca31f6b4c6.png)

**Comment by frankseide** [comment]
Looks like the benchmark scripts are out of date. It is now required to explicitly select the cudnn engine. The Examples in the CNTK repo have been updated, the AlexNet one is at Examples/Image/Miscellaneous/ImageNet/AlexNet. In both .ndl files, you will now find additional parameters "imageLayout=...", and some parameters are now defined as ImageParameter.

@Alexey-Kamenev, are the files under Examples otherwise identical to the benchmark, or have there been other changes?

**Comment by xhzhao** [comment]
I add the new parameter to ndl file:
    features = ImageInput(ImageW, ImageH, ImageC, tag = feature, imageLayout = "cudnn")
but an error in runtime:
[AlexNet_Train.txt](https://github.com/Microsoft/CNTK/files/175380/AlexNet_Train.txt)

**Comment by frankseide** [comment]
You will need to set it in all nodes that are relevant. Please try to locate the two .NDL files (Macros.ndl and AlexNet.ndl) in Examples/Image/Miscellaneous/ImageNet/AlexNet and search for imageLayout and ImageParameter, and apply all these changes to the two benchmark .NDL files. Then it should work.

**Comment by xhzhao** [comment]
@frankseide ,Thanks, i fixed this issue.
