### ISSUE TITLE
Issues with seq2seq for different input and output vocabulary

### ISSUE THREAD

**Issue by isaias-sanchez-cortina** [Microsoft/CNTK#2424]
Hi, 
I'm trying to use the [seq2seq tutorial 204 ](https://github.com/Microsoft/CNTK/blob/v2.1/Tutorials/CNTK_204_Sequence_To_Sequence.ipynb) for an output vocabulary different to the input vocabulary.
However, setting _label_vocab_dim_ to a different value from _input_vocab_dim_ fails at several points. 
In particular, within the definition of the _Unfold_ generator in the definition of the model for testing:

> RuntimeError: Binary elementwise operation PastValue: Left operand 'Output('ReconcileDynamicAxis2616338_Output_0', [#, labelAxis], [63])' shape '[63]' is not compatible with right operand 'Output('Block2616333_Output_0', [], [21173])' shape '[21173]'.

I've tried several approaches without success. 
I would appreciate any clue on what I'm missing, or on what changes should the code undergo.

Thank you very much.

**Comment by sayanpa** [comment]
I assume you are talking about CNTK 204 seq2seq tutorial. Here is a link to the dynamic axes reconciliation:
https://stackoverflow.com/questions/42823664/reconciledynamicaxis-reconcile-dynamic-axis-in-cntk-2-0-python-api/46453354#46453354

**Comment by isaias-sanchez-cortina** [comment]
I don't see how the dynamic axis are involved in this error.  If they are, I wouldn't know how to apply reconcile_dynamic_axes to do so.  What should I change in the tutorial in that case?
  Else, the issue is that the static shapes do not match. Maybe, at some point it was used  input-related vars instead of label-related. 
I've been working intensely for a year with the CNTK toolkit; but still, simple things still reach far from my grasp. I would really appreciate if you may provide with more concrete hints or exact code changes.
Thank you in advance :D

**Comment by KeDengMS** [comment]
@isaias-sanchez-cortina [this debug manual](https://github.com/Microsoft/CNTK/blob/v2.1/Manual/Manual_How_to_debug.ipynb) might help you understand the error better.

**Comment by sayanpa** [comment]
Interestingly, ran itto this issue myself for not seq2seq but for a different network with two different vocabulary as input. I went the long winded way of debugging into the code and I also had access to @KeDengMS to help me. Later on it turned out I had incorrectly passed the sequence_axis information for the two vocabularies. Moral of the experience: Reading the debug manual helps.  Hope it helps you too.

The debug manual captures this in the first guideline.
q_axis = C.Axis.new_unique_dynamic_axis('q')
a_axis = C.Axis.new_unique_dynamic_axis('a')
q_input = C.sequence.input_variable(shape=10, is_sparse=True, sequence_axis=q_axis, name='q_input')
a_input = C.sequence.input_variable(shape=10, is_sparse=True, sequence_axis=a_axis, name='a_input')

model_layers_distinct_axes = create_model_layers(q_input, a_input)
print(repr(model_layers_distinct_axes))

**Comment by sayanpa** [comment]
Having not received any responses since Oct 4, closing this issue. Please reopen a new issue if you need further help.
