### ISSUE TITLE
Multiple CTF files for different subsets of train and test data

### ISSUE THREAD

**Issue by frankibem** [Microsoft/CNTK#2482]
Does CNTK allow multiple CTF/CBF deserializers each with different subsets of training data? My dataset is large so I used 4 processes to write different subsets to the CTF format into separate files - each file is approximately 17GB and I planned to convert to CBF later. To test this, I tried creating a MinibatchSource with the following code:

```
def create_reader(num_procs=4):
    streamdefs = StreamDefs(label = StreamDef(field='label', shape=digit_dim, is_sparse=True),
                            pixels = StreamDef(field='pixels', shape=frame_dim, is_sparse=False))
    
    deserializers = []
    for i in range(num_procs):
        deserializer = CTFDeserializer(os.path.join('./ctf', 'train_{}.ctf'.format(i)), streamdefs)                                                 
        deserializers.append(deserializer)
    
    return MinibatchSource(deserializers, randomize = True, max_sweeps = cntk.io.INFINITELY_REPEAT)

```

However, I get the following error message: 

> Could not reconcile data between different deserializers. Keys of logical sequences do not match.

How do I interpret this? Is there some other means to achieve the desired effect? (note that I am able to create a MinibatchSource for individual CTF files successfully).

**Comment by eldakms** [comment]
Composition of deserializers makes sense only when deserializers provide input for different nodes in your network. I.e. one deserializer provides features, the other - labels. The feature and the label though coming from different deserializers should have the same sequence key, so that they can be correlated and put in the same minibatch (i.e. feature is coming from ImageDeserializer, label - from CTFDeserializer). That's where the error is coming from.

In your case you actually want to split a single stream (ctf file) into several. Currently this is not supported. You need to merge all you training data in one file and create a single deserializer for it (or as you pointed out have several minibatch sources, but this is more cumbersome). Is there any problem reading from a single file?

Thanks!

**Comment by frankibem** [comment]
No, there's no problem reading from a single file. Creating the separate files in parallel was significantly faster so I was interested in knowing if it was possible to read directly from them as well. I'll go ahead and merge them into one.

On an unrelated note, I plan to train on the azure dsvm for Linux, but I'm not sure which storage option to use to enable me to download it into multiple vms. Do I go with azure blob or file storage? Or is there some other recommended way of going about that.

**Comment by eldakms** [comment]
All readers only work with files, so you won't be able to use blobs directly, data should be available locally.
Maybe it will be useful to have a look at Azure shipyard here:
https://github.com/Azure/batch-shipyard/tree/master/recipes/CNTK-GPU-OpenMPI

**Comment by frankibem** [comment]
I'll look into that. Thanks for your quick responses!
