### ISSUE TITLE
CNTK directs console output to stderr

### ISSUE THREAD

**Issue by alexeyo26** [Microsoft/CNTK#25]
Currently CNTK directs all console output to stderr rather than stdout. Was it for a reason?

**Comment by stolcke** [comment]
I think only “payload” output (such as rec output) should go to stdout.  All other errors, warnings and informational messages should go to stderr.

Andreas

**Comment by alexeyo26** [comment]
Andreas, you said and **informational messages**. (to stderr). I believe this is exactly what we have now. Moreover, if I invoke, e.g., Simple2d example, nothing goes to stdout. If that's the way we believe it should be, fine. Just wanted to clarify.

**Comment by frankseide** [comment]
Any actual output data should go to stdout, while messages, informational or errors, should be on stderr. I don’t think we have any data output at present. But I can imagine writing to stdout instead of a file e.g. for integrating with pipe-based tools like Kaldi. Since that may be binary data, we should keep stdout pristine.

**Comment by alexeyo26** [comment]
To the best of our knowledge CNTK adheres to the UNIX model:

- data to stdout
- messages to stderr

Issue closed
