### ISSUE TITLE
No module named CNTK

### ISSUE THREAD

**Issue by EngineerKhan** [Microsoft/CNTK#2535]
CNTK 2.2 CPU version is installed on my system. It runs properly when I run it using Python 2, but whenever I select Python 3 kernel in JuPyter, it gives me strange error that "module CNTK not found". Can anyone kindly help me there? I have Python 3.5.2 installed for Python 3 and installed CNTK with default settings.

**Comment by bencherian** [comment]
The wheel you installed is presumably for a specific Python version...which did you install it for? You would need to install CNTK in each python installation. 

If you did install it for both python versions, there could also be an issue with where you are running your notebook from. What OS are you running? There are other issues with Anaconda environments being used by other programs on Windows because CNTK installs DLLs into the root folder of the conda environment and most programs only add Library\bin to the search path instead of actually activating the environment. I'd suggest install jupyter notebook in your working environment and starting it from the same environment so that it has the entire standard set of directories added to the path.
