### ISSUE TITLE
GlobalAveragePooling with FreeDimensions not working as expected

### ISSUE THREAD

**Issue by lonnes** [Microsoft/CNTK#2544]
Hello, 

If I do 
`gap_layer = C.layers.GlobalAveragePooling()(C.input_variable((3, C.FreeDimension, C.FreeDimension)))`
I get an error saying "RuntimeError: Convolution: Kernel shape can't be Unknown." 

But doing something like
`C.reduce_mean(C.input_variable((3, C.FreeDimension, C.FreeDimension)), axis=[1,2])`
returns the expected function, with an output of dimensions [3 x 1 x 1]. 

Shouldn´t both operations be equivalent?

**Comment by cha-zhang** [comment]
Are you using the latest master?

**Comment by spandantiwari** [comment]
We recently enabled free static axes support for GlobalAveragePooling layer. If you are not on the latest master, could you please sync with the latest master and try this. Let us know if you still some issues.

**Comment by lonnes** [comment]
Hi, Cha and Spandan

 I´ve just tried with the line 
```
gap_layer = C.layers.GlobalAveragePooling()(C.input_variable((3, C.FreeDimension, C.FreeDimension)))
``` 
using the code from the latest master and got the same error.  I´ve compiled from scratch and installed the generated wheel in a python environment. I see the current version as 2.2+.

**Comment by lonnes** [comment]
Just an update, I´m still seeing this in 2.3.

**Comment by robertomest** [comment]
I just tested on 2.4 and got the same error.

**Comment by spandantiwari** [comment]
@robertomest @lonnes - Let me root cause this issue and get back.

**Comment by lonnes** [comment]
Thanks Spandan! This is issue is blocking us from using FreeDimension with ResNets.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by spandantiwari** [comment]
@lonnes  Here’s the issue in a nutshell. ``GlobalAveragePooling`` is implemented as a special case of pooling (average pooling) where the kernel shape are defined by the ``FreeDimension``, because it is typically the same shape as the image itself. While CNTK ``pooling`` op supports ``FreeDimension`` for input tensor shape, it does not support ``FreeDimension`` for kernel shape. The kernel shape must be known beforehand. With ``GlobalAveragePooling`` that cannot be known. Hence the error using ``FreeDimension`` with ``GlobalAveragePooling``.

Supporting ``FreeDimension`` for kernel shape is not high on our priority right now. But I think at least the error reporting needs to be improved. 

The ``reduce_mean`` API should work with ``FreeDimension``. Could you please try using that and let us know if there are any issues (new issue or reopen this one)?

**Comment by lonnes** [comment]
Hi Spandan. Yes, we´ll try using `reduce_mean` in place of GlobalAveragePooling in fully convolutional architectures (like resnet) and let you know how that happens. Couldn´t we change the `GlobalAveragePooling` operation in Python to reflect the `reduce_mean` call? Otherwise, popular architectures like Resnets will not work with `FreeDimension`.

**Comment by spandantiwari** [comment]
Hi lonnes - You have a good point, and I agree that GloablAveragePooling with FreeDimension is needed. It is on our to-do list, but some other items are taking priority right now. Wrapping reduce_mean could be a short-term solution, though there are other use cases where supporting the unknown pooling kernel size could help. If you have a write a working version using reduce_mean, consider submitting a PR. Thanks.
