### ISSUE TITLE
Does BatchNormalization work with C.FreeDimension inputs? 

### ISSUE THREAD

**Issue by nitrif** [Microsoft/CNTK#2618]
It seems that BatchNormalization doesn't work with inputs of C.FreeDimension size:
![image](https://user-images.githubusercontent.com/18011695/32772258-9b7b5f2a-c925-11e7-8021-d0351575a20c.png)

Providing the network to the learner results with the following exception:
ValueError: Cannot create an NDArrayView using a view shape '[?]' that has unknown dimensions for any of its axes.

[CALL STACK]
    > CNTK::NDArrayView::  DeepClone
    - CNTK::NDArrayView::NDArrayView<double>  
    - CNTK::NDArrayView::  NDArrayView
    - CNTK::Value::  IsValid (x2)
    - CNTK::Variable::operator std::shared_ptr<CNTK::Function>  
    - CNTK::Value::  IsValid
    - RtlRunOnceExecuteOnce
    - InitOnceExecuteOnce
    - _crtInitOnceExecuteOnce
    - CNTK::Value::  IsValid
    - CNTK::Variable::  Value
    - CNTK::Parameter::  SetValue
    - CNTK::  FSAdaGradLearner
    - CNTK::Internal::  ZeroesWithDynamicAxesLike (x2)

Thanks,
Nikola

**Comment by nitrif** [comment]
The inputs are images:
features = C.input_variable((3, C.FreeDimension, C.FreeDimension), np.int, name="input_features")
while i call BatchNormalization with map_rank=1.

**Comment by KeDengMS** [comment]
Parameter needs to be fixed size or Inferred. FreeDimension means the dimension can change for different minibatch. I think you have two solutions:
1. Pad your input to a fixed size instead of using FreeDimension, so Parameter would have its size determined
2. Change your code so that BatchNormalization happened in a place where variable shape is not affected by FreeDimension in input
