### ISSUE TITLE
C# wrapper - unmatched bracket found in parameters

### ISSUE THREAD

**Issue by Brigthinx** [Microsoft/CNTK#264]
Hello,

I have successfully run 01_OneHidden example which generated trained model. After that I wanted to evaluate the model from C#. I managed to build and run the C# wrapper however I am getting error in model.Init(config); command. In C++ the exception is thrown in m_eval->Init(stdConfig);. The error says "unmatched bracket found in parameters". I tried all different config files but non has worked. Not sure if I am doing something wrong or if there is an issue in code.
Appreciate your help.

Jan

**Comment by rold2007** [comment]
I remember having the same issue. I'm not 100% sure how I resolved it but I think it had to do with a mismatch of compilation configuration. If you C# code is in Debug, use the debug CNTK DLL (managed + unmanaged), same with Release.
My C# code works, so if this does not solve your problem let me know I'll look at what else it could be.

**Comment by Brigthinx** [comment]
Thanks for the answer. I have two projects in my solution - EvalWrapper and CSEvalClient. Both have Debug_CpuOnly set. I tried to change it to different cofigurations for both projects (debug, release), rebuild the solution but still the same error.

**Comment by rold2007** [comment]
@Brigthinx I tried to replicate your problem as I'm sure I had it before but I wasn't able yet. Could you answer these questions so that I can try to replicate it ?

Have you modified any configuration (.cntk, .ndl) file ?
Which version of the code are you using ?
Have you tried debugging the problem ? The error message can be seen in [\Source\Common\Include\Config.h around line 400](https://github.com/Microsoft/CNTK/blob/master/Source/Common/Include/Config.h#L400).

**Comment by Brigthinx** [comment]
@rold2007 Sure. Initially I did not modify any config files but then tried to modify it since I thought that the problem is in the files. Whatever modification I did to the files I was still getting the error. 
Not sure how to get the version of the code. I downloaded the zip file on Mar 13th.
I did try to debug the code but I cant go deeper than to m_eval->Init(stdConfig); which throws the error.
Maybe some of these information about my setup might help: I didnt install Cuda since I dont have a graphic card that supports it. I am running Windows 7 64bit on Apple Airbook. I have Visual Studio 2013 Update 5. After downloading the solution I opened the main cntk solution and removed all projects except CSEvalClient and EvalWrapper. And that is what I am trying to make work.
Thanks for the help.

Jan

**Comment by rold2007** [comment]
@Brigthinx Thanks for these details, I was able to replicate your problem, but then I recompiled something and wasn't able to replicate it. The way I did was that I mixed the debug_cpu version of CSEvalClient.exe and EvalWrapper.dll with the release version of the other CNTK dll, just like it happened to me a while ago.
Note that the release binaries you are using are very old (February 8th 2016) considering that since then a LOT of commit (bug fixes) have been done. I really suggest that you get the latest source code and work from there.

**Comment by Brigthinx** [comment]
@rold2007 Great idea. I downloaded the latest version and it works! Thanks a lot for your help.

**Comment by rold2007** [comment]
@Brigthinx That's good to hear! Do you mind closing this issue now that it is resolved ? I'm only a CNTK user so I don't have such rights.

**Comment by mahilleb-msft** [comment]
Closing...
