### ISSUE TITLE
Would you consider a Mac version?

### ISSUE THREAD

**Issue by chikiuso** [Microsoft/CNTK#2658]
Would you consider a Mac version? thanks.

**Comment by KeDengMS** [comment]
We are planning to add more support for Mac. In the meanwhile, can you use docker image instead?

**Comment by DHOFM** [comment]
@KeDengMS That sounds great to me, too. Do you have a schedule plan for Mac OS native support ? Apple supports AMD GPU (Mcbook Pro ansd so on) - will there be GPU support ? That said, Mac OS will support eGPUs ( Beta since High Sierra) - so external NVIDIA GPUs could be connected through Thunderbolt 3. Will you support them ?

**Comment by KeDengMS** [comment]
We'll move to CMake to support build source on Mac OS at minimum. As for GPU, as long as CUDA is supported, I don't see any blocking issues for CNTK to use internal or external GPUs on Mac OS. AMD GPUs would require more work as its API is different from CUDA.

**Comment by mx-iao** [comment]
Closing, track #1947
