### ISSUE TITLE
CNN for speech recognition

### ISSUE THREAD

**Issue by mravanelli** [Microsoft/CNTK#270]
Hi,
I'm trying to do an experiment with CNTK using Convolutional Neural Networks (CNNs) for speech recognition purposes. 

In the release there are many examples of CNNs for vision purposes, but I haven't found yet any example for speech. Unfortunately the use of CNN in speech can be a little bit different. 

For instance in my case the features are 40 fbank + 40 delta + 40 delta delta (similar to the kaldi recipe local/nnet/run_cnn.sh in kaldi-trunk/egs/rm/s5). Moreover, due to the splicing of 5 frames before and 5 frames after the current one, the input CNN features form a very big vector like this:

`(40 fbank, 40 delta, 40 delta_delta)_frame(N-5),......(40 fbank, 40 delta, 40 delta_delta)_frame(N),.....(40 fbank, 40 delta, 40 delta_delta)_frame(N+5),
`

The point is that considering these typical features, I have to force the network to change filter every 40 features to avoid to filter with in the same weights different types of feature.  In other words, I cannot filter with the same filter weights, both fbank features and delta features.

In kaldi (see local/nnet/run_cnn.sh  and kaldi-trunk/utils/nnet/make_cnn_proto.py) this is managed by the parameter "PatchStride", where  "PatchStride=N"  means that every N features the network  is forced to change filter.

Is there something similar in CNTK? 

Mirco

**Comment by frankseide** [comment]
Yes... nearly at least. First, you need to declare a tensor shape for your input. I.e. instead of InputValue(1320, ...), use
```
features = InputValue (40, 3, 11)
```
This will give you a [40 x 3 x 11] tensor object.

If you want 3 separate filter chains for static, delta, and delta-delta, you can RowSlice it:
```
features = InputValue (120, 11)
staticFeatures = RowSlice (0, 40, features)
deltaFeatures = RowSlice (40, 40, features)
deltaDeltaFeatures = RowSlice (80, 40, features)
```
and then operate on them separately. You can always RowStack() them back together where you need.

If in the above you would use 3 different filters (which is what I would do), it is no different from using a 2D convolution applied to a single [40 x 11 x 3] stream, where static/delta/delta-delta are jointly filtered like the R/G/B dimensions of images. This is a bit more tricky: You need to use Transpose(), but that will only flip the first 2 axes (internally, TransposeDimensionsNode can swap any two axes, but we'd just have to add code to the NDL parser to expose that). I think the solution to the riddle is something like this:
```
features = InputValue (120, 11)
feat1 = Transpose (features)  # 11 x (40*3)
feat2 = Reshape (feat1, 1320, imageWidth = 11, imageHeight = 40, imageChannels = 3, imageLayout='cudnn') # 11 x 40 x 3 
feat3 = Transpose (feat2) # 40 x 11 x 3
```
(Never mind the names of the imageXXX parameters to Reshape().)

Now you can apply 2D convolution to 'feat3' which can run over frequency (first dimension) or time (second dimension) while treating the 3 channels as triples.

Disclaimer: The above is what we call "Outlook code" at MS, it may have some errors.

**Comment by mirco86** [comment]
Hi Frank,
tomorrow I will try it and I will let you know if it works. However,
considering the popularity of CNNs for speech recognition it would be good
to add an example (maybe a simple example with TIMIT) in the official
release.

Mirco

**Comment by tz579** [comment]
@frankseide Your explanation also helps me a lot. There is one question coming up for me: In either the Wiki pages or in the CNTKBook, there are no such nodes as "Transpose" and "Reshape", but I have seen some usage and references for those nodes for months, which have confused me a lot. Are those nodes still in testing? I see that the "Full-NDL-Function-Reference" page in the wiki is pretty new (updated only 9 days ago).

**Comment by smajida** [comment]
@frankseide @mirco86 
I have a hundreds of 10k sample audio files with label  binary vectors of 100 length. 
How I can train a simple CNN with CNTK on this data? unfortunately, most of examples are for images which are 3 channel matrices and not 1-channel vector data.

**Comment by frankseide** [comment]
There is no fundamental difference. All you need to do is declare both your input data and your filter kernels to be of appropriate tensor rank (1) and dimension. @Alexey-Kamenev, would you mind confirming that 1D convolution is fully supported, and maybe show what the dimension specification would look like?

**Comment by FreedMana** [comment]
@tz579 Maybe your guide book is incomplete?try this one `https://github.com/Microsoft/CNTK/tree/master/Documentation/CNTK-TechReport/lyx`.
Still there are some other nodes i can't find , like some parameters about parallelTrain.

**Comment by tz579** [comment]
@frankseide My bad! The Reshape node has been there in CNTKBook for a long time and I did not notice that. Still there is no Transpose node in CNTKBook, and the description for InputValue seems outdated, as it only tells us to give "Rows, Cols" rather than more robust input pattern like "InputValue (40, 3, 11)" in your example above.

Thanks a lot for your explanation about everything!

**Comment by wolfma61** [comment]
check out version 2.0 or later, in addition tutorial/sample section
