### ISSUE TITLE
genCNN

### ISSUE THREAD

**Issue by ianupright** [Microsoft/CNTK#273]
I would cut off my left arm for an implementation of this on CNTK.   Anyone able to do it?  What would be the fee?  :-)

http://arxiv.org/pdf/1503.05034v2.pdf

**Comment by frankseide** [comment]
I would like to understand what is stopping CNTK from doing this today. Would you mind giving us a TL;DR? Since you already read it, it will probably be faster than I spend the time to understand it in detail. :)

**Comment by frankseide** [comment]
Figure 2 claims it is a recursive model which CNTK cannot handle (I think), but since the recursive input only connects to the first input, this seems to be a "tail recursion" which can be implemented as an iteration (recurrent network). Indeed, Figure 1 just shows a recurrent model, which we can handle. Just from Figures 1 and 3.3, we may be able to handle it. Want to give it a try?

**Comment by ianupright** [comment]
Yes.. I thought it might be reasonably possible.  I guess it is missing a hierarchical softmax too, but perhaps NCE would suffice.  I'll see if I can allocate the time to make an attempt at it.

**Comment by frankseide** [comment]
Hierarchical softmax for class models? CNTK can handle that with the ClassBasedCrossEntropyWithSoftmax() criterion (using a somewhat quirky data format to work around the varying class sizes).

**Comment by ianupright** [comment]
I missed that.. thanks!
