### ISSUE TITLE
Issue about function forward in class Function

### ISSUE THREAD

**Issue by woskii** [Microsoft/CNTK#2773]
I am trying to read the source code of CNTK. 
In the function “train_minibatch()” in "class Trainer", it calls function ”forward()“ in "class Function". But in "class Function"(location: Source\CNTKv2LibraryDll\Function.cpp),it calls another "forward“ function with four arguments which seems to be in the "class Primitive Function"(location: Source\CNTKv2LibraryDll\PrimitiveFunction.h) and "class Composite Function"(location: Source\CNTKv2LibraryDll\CompositeFunction.h). But they are all virtual functions without specific implementation, and these two classes are all child classes of "class Function" without child class.
So what's going on in “train_minibatch()”? I am very confused. Any help would be appreciated. Thanks in advance.

**Comment by eldakms** [comment]
Python train_minibatch is just a wrapper around C++ Trainer.cpp::TrainMinibatch, which calls Function::Forward and then Backward.
Because Function::Forward is virtual it ends up in the actual implementation, which is Composite. So look at the implementation of the CompositeFunction::Forward (line 1906) and Backward. These functions create the computational network and perform forward backward prop. Hope this helps.
