### ISSUE TITLE
fixing gpu_nms proc for proposal_layer 

### ISSUE THREAD

**Issue by kyoro1** [Microsoft/CNTK#2776]
Hello @spandantiwari , I found out that we couldn't acquire correct results in using `gpu_nms` for Faster R-CNN scripts. Can you share the correcting schedule to us? If not, we cannot proceed distributed learning for Faster R-CNN with CNTK.

https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/utils/rpn/proposal_layer.py

Ref. https://github.com/Microsoft/CNTK/issues/2426

**Comment by spandantiwari** [comment]
@kyoro1 - if you have a repro showing wrong results with gpu_nms, share that. 

>  If not, we cannot proceed distributed learning for Faster R-CNN with CNTK.

Why can't you proceed? You are aware of the cpu_nms option. In fact, you submitted a PR for your distributed training using the cpu_nms option. As you are aware, that PR was failing a test and therefore it had to be reverted. If you like, we can help you debug the test failure. In any case, is there some thing else blocking you?

**Comment by kyoro1** [comment]
@spandantiwari Is it your opinion to change `cpu_nms` option? I've never heard of it from you, even when everyone sent it to you... i.e. I don't have confidence to change it without any supports.

**Comment by spandantiwari** [comment]
> Is it your opinion to change cpu_nms option?

I am not sure I understand your question here. You mentioned in the opening post that you "couldn't acquire correct results" with gpu_nms and that is blocking you. That is why I recommended trying the cpu_nms option instead which might unblock you. Also, if you have a brief repro of the gpu_nms issue share that so that will help us fix it. 

> I've never heard of it from you, even when everyone sent it to you... 

Again, I am not sure why you say this. I replied back to your e-mail dated 10 Nov 2017 with subject "RE: Enhancement of distributed learning of Faster R-CNN" with the exact steps needed to enable cpu_nms. For reference this is the excerpt from my e-mail laying out the exact steps:

> Subject: RE: Enhancement of distributed learning of Faster R-CNN
So you would need to make two manual changes:

> 1.	In proposal_layer.py on line # 158 add an argument to the ‘nms()’ call as follows: use_gpu_nms=False

> 2.	Make sure that in FasterRCNN_config.py on line # 146, you have: __C.USE_GPU_NMS = False

Based on this you had updated your PR. So, I believe you have "heard about" this before. 

Give it a try if this is blocking you.
