### ISSUE TITLE
step function for recurrence with multiple state

### ISSUE THREAD

**Issue by NO-0044** [Microsoft/CNTK#2858]
I am trying to use custom step function for Recurrence. But I ran into some problems when I tried to use function which have multiple outputs. For example:
```
def test_func(x,y,z):
    return x+z,y*z
```
And I tried to use it like in tutorial with:
```
x = C.input_variable(**Sequence[Tensor[1]])
x0 = np.array([[1],[2],[3]])
test = Recurrence(test_func,initial_state=(Constant([1]),Constant([1])))
y = test(x)
y(x0)
```
I found that the `return_full_state` must be set as `True`, otherwise there will be error:
```
RuntimeError: Function 'Composite(Combine): Input('Input5518', [#, *], [1]) -> Output('Plus5645_Output_0', [#, *], [1])': The output Variable 'Output('ElementTimes5628_Output_0', [#, *], [1])' shape '[1]' does not match the SampleLayout shape '[]' of the corresponding ComputationNode in the network.
```
But according to the document, I think it should return the first value by default. Is this right way to use custom step functions?

**Comment by KeDengMS** [comment]
You need to wrap up the step function with as_block to make it a primitive function. By default, CNTK operations in Python are composite functions, i.e. its inputs come from the foremost of the connected graph instead of it's immediate inputs. Please try function.[arguments](https://www.cntk.ai/pythondocs/cntk.ops.functions.html?highlight=arguments#cntk.ops.functions.Function.arguments) on primitive function and composite function to find out the difference

We have a work item to have a more strict check on step function in RNN to make this error more meaningful in future.

**Comment by delzac** [comment]
Hi @KeDengMS 

I tried wrapping the step function with C.BlockFunction since according to the documentation it "wrap the content into an :func:`~cntk.ops.as_block`", which is your suggested solution. But it didn't work for me.

Below is the code
```
import cntk as C
from cntk.layers import Recurrence
import numpy as np


def build_model():

    @C.BlockFunction(op_name="stepfunction", name="inner")
    def inner(a, b, x):
        return x + a, x + b

    m = Recurrence(inner, name="Recurrence")
    return m

a = C.sequence.input_variable(10)
model = build_model()
b = model(a)

i = np.random.random((1, 10, 10)).astype(np.float32)
print(b.eval({a: i}))
```

If i get the following error when i run the code on cntk v2.5.1:
RuntimeError: Function 'Composite(NoOp): Input('Input3', [#, *], [10]) -> Output('Recurrence', [#, *], [10])': The output Variable 'Output('inner', [#, *], [10])' shape '[10]' does not match the SampleLayout shape '[]' of the corresponding ComputationNode in the network.


Any suggestion on how this can be solved?

**Comment by tangyuq** [comment]
Please try: 
    def inner(a, b, x):
        return x + C.sequence.broadcast_as(a, b), b + x

The real cause might be that the two constant initial states are being casted into two different sequence_axis. You should be able to make this work in your previous version without the as_block. 

In addition, the ordering of the CNTK function arguments might not be guaranteed. If you encounter further issues, you might want to try: 
    def create_step_func():
        aa = C.placeholder(10, name='aa')
        bb = C.placeholder(10, name='bb')
        xx = C.placeholder(10, name='xx')
        step_func = C.combine(xx + C.sequence.broadcast_as(aa, bb), bb * xx)
        @C.Function
        def _inner(a, b, x):
            arg_map = {'aa': a, 'bb': b, 'xx': x}
            args = [arg_map[p.name] for p in step_func.arguments]
            res = step_func(*args)
            return res[0], res[1]
        return _inner
This trick is the same as the as_block trick which offers the means to force the order of the cntk.Function arguments to match that of the Python function.

**Comment by delzac** [comment]
Hi tangyuq, thanks for the suggestion.

I'm wondering why does it have to be so complicated in order to write your own step function? If i were to slightly modify my step function, it will start raising errors again.

For example,

```
# This will not work
@C.BlockFunction(op_name="stepfunction", name="inner")
    def inner(a, b, x):
        return a + b, x

# This will work
@C.BlockFunction(op_name="stepfunction", name="inner")
    def inner(a, b, x):
        return a + b, x + 0

# This will not work
    def inner(a, b, x):
        return a + b, x + 0

# This will work
    def inner(a, b, x):
        return a + b, x
```

At this point, constructing a step function seems like an art. I don't remember cntk2.2 having this kind of issues (i could be wrong).

**Comment by KeDengMS** [comment]
This problem has nothing to do with dynamic axis. You can modify the step function without broadcast_as and get it to pass:
```
    @C.BlockFunction(op_name="stepfunction", name="inner")
    def inner(a, b, x):
        #return x + C.sequence.broadcast_as(a,b), x + b
        return x + (a + b*0), x + b
```
I debugged it a bit and it seems has something to do with the V1 DelayedValueNode wrt. multiple outputs. As a workaround, please make sure the placeholders other than the first ones are being used in the first output of the step function.

**Comment by delzac** [comment]
Got it! Thanks for the explanation! :)

**Comment by delzac** [comment]
@KeDengMS Any possible timeline to share if/when the bug will get resolved?

> 
> 
> This problem has nothing to do with dynamic axis. You can modify the step function without broadcast_as and get it to pass:
> 
> ```
>     @C.BlockFunction(op_name="stepfunction", name="inner")
>     def inner(a, b, x):
>         return x + (a + b*0), x + b
> ```
> 
> I debugged it a bit and it seems has something to do with the V1 DelayedValueNode wrt. multiple outputs. As a workaround, please make sure the inputs other than the first one are being used in the first output of the step function, and all outputs use the last input (sequence input to RNN).
