### ISSUE TITLE
Normalization input data with global mean and std

### ISSUE THREAD

**Issue by shyTNT** [Microsoft/CNTK#2911]
Hi.,

I am working on normalizaion with global mean and std of all input data. With ndl, we have the following code:

    **MeanVarNorm(x)
    {   
                xMean = Mean(x)
                xStdDev = InvStdDev(x)
                xNorm=PerDimMeanVarNormalization(x,xMean,xStdDev)
     }
     ...
     features=Input(featDim, tag="feature")
     labels=Input(labelDim, tag="label")
			       			       
     # define network
     featNorm = MeanVarNorm(features)
     L1 = BFF(featNorm ,hiddenDim,featDim)**

And I am planning to refine it with python. 

    **def mean_variance_normalize(x):
           mean = cntk.reduce_mean(x)
           x0 = x - mean
           std = cntk.sqrt(cntk.reduce_mean(x0 * x0))
           inv_std_dev = 1 / std
           return cntk.per_dim_mean_variance_normalize(x, mean, inv_std_dev)
     ...
     "Layers definition"
     features = sequence.input_variable(feature_dim)
     norm_fea = mean_variance_normalize(features)
     f = Dense(512, activation=relu, name='dense1')(norm_fea)**

Actually, I wonder whether Mean(x) can get a global mean for all input features. Does cntk.reduce_mean() work in same way?

**Comment by KeDengMS** [comment]
By global mean and std of all input data, do you mean all input data in one minibatch? If that's the case, you can try [batch_normalization](https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=batch_normalization#cntk.ops.batch_normalization)
Otherwise, you need to have a network to run through all input data and compute the mean/variance, then use per_dim_mean_variance_normalize().

**Comment by shyTNT** [comment]
Thanks. I computed the mean/variance of all input data and then used per_dim_mean_variance_normalize().
