### ISSUE TITLE
PyTorch -> CNTK

### ISSUE THREAD

**Issue by arijit17** [Microsoft/CNTK#2915]
(sorry this is not an issue, just a question asking for opinion) 

I would like to re-write some code from PyTorch to CNTK. Is it easy to relate PyTorch and CNTK? Do I need to be aware of some special things?

I did translate TensorFlow and CNTK codes before, and I found there is rather 1:1 correspondence. 
But I know Tensorflow reasonably well ... but now I do not want to put an effort in learning PyTorch :-)

**Comment by robertomest** [comment]
CNTK is quite similar to Tensorflow in the sense that both work by building a graph and then executing it. Pytorch is different because it uses tape based automatic differentiaton, which means that things usually happen right where you put it (as opposed to being added to a graph that will be executed later). If you are used to the build-then-execute style, it feels a bit different to use Pytorch.

**Comment by arijit17** [comment]
Thanks for the hint!
