### ISSUE TITLE
Windows 10 Computer dies suddenly with 3 or 4 GPUs (but not 1 or 2)

### ISSUE THREAD

**Issue by dmagee** [Microsoft/CNTK#3016]
I'm training a large model using a (brand new) 4x GPU machine and cntk..exe. With 1 GPU or two everything works fine and cntk can train for hours without anything bad happening. If I move to 3 or 4 GPUs (mpiexec -n 3 or 4). I'm getting the situation where sometimes the computer (windows 10)  just shuts down suddently (black screen) and re-boots. Looking in the windows logs there is nothing relating to driver crashes (or anything else) before the re-boot. This seems to happen near the beginning or calling cntk (within a few seconds). Once learning has started for a whileI haven't seen it do this.  It is more frequent with 4 GPUs than 3.

Is it possible this is a software issue? My first thought was that it was a hardware issue (PSU maybe, although this is 1500W, so should be plenty). The vendor isn't convinced (yet) that it is a hardware issue.

**Comment by KeDengMS** [comment]
Some things to check:
1. For single GPU test, please run with manually specifying devices via `cntk.try_set_default_device(cntk.gpu(<0|1|2|3>))`, and make sure all GPUs are in good shape. If this is not 100% repro I guess you can skip this step.
2. CNTK could get all GPUs to run close to 100% utilization and push to the limit for venting/power supply. Please try a different job with less GPU utilization and see if the same problem happens. My suspicion is that your power supply may be the bottleneck. GPU usually take 250-300W each, and CPU about 100W each, plus motherboard/memory/disk, your system seems to reach 1500W in full workload. PSU quality varies from brand to brand, and it's safer to have a bigger margin (say, 1800W from PSU) if possible.
3. You may also try installing Ubuntu on this machine and see if the problem is related to OS/driver.

**Comment by rhy-ama** [comment]
@dmagee: here are some recommendations

1) Efficiency and number of 12V rails are as important, if not more important, than outright watts rating of the PSU. For instance, if PSU is multi-rail, you could be over-loading 12V x amps rating of that PSU rail if two GPUs are sharing (directly or indirectly) its current. If the PSU is single rail, you need to take into account it's efficiency rating (max wattage will be strictly less than 1500w, more often in practice ~1300w).

2) At high loads, with the rise of temperatures, both the efficiency of PSU and of GPUs drops, and they might draw more current than rated.

Immediate solutions are
a) Alter / switch around 12v molex and PCI-e wiring as well as try changing PCI/e slots assignment for GPUs
b) Remove co-processor (if any), unused memory / HDs (if any) - anything that you do not need for training
b) Install MSI Afterburner application (assuming you are using windows platform as indicated by cntk.exe) and
- configure fan override to max for each GPU
- limit power draw of each GPU to 80%

If b) works, you can increase power draw limit closer to 100% until you find the level that does not overload the PSU

BR

**Comment by KeDengMS** [comment]
Seems like non-CNTK issue.
