### ISSUE TITLE
Does the documentation suggest multiple dynamic axes are possible?

### ISSUE THREAD

**Issue by nmfisher** [Microsoft/CNTK#3057]
Quote from https://github.com/Microsoft/CNTK/blob/master/bindings/python/doc/sequence.rst:

> The outermost level is the batch axis. The document level should have a dynamic axis because we have a variable number of candidate documents per query. The innermost level should also have a dynamic axis because each document has a variable number of words...With rich enough training data it is possible to have another level of nesting, namely a session, in which multiple related queries belong to.

I read this to mean that multiple/nested dynamic axes are possible, but I haven't seen any actual method for achieving this.

Are nested dynamic axes possible, or is the documentation wrong?

**Comment by KeDengMS** [comment]
You can have 2 sequence axes by using sequence.unpack() to create a free dimension for one of the sequence axes. [This](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/layers/models/attention.py#L94) is an example.

**Comment by nmfisher** [comment]
Thanks - I should have been a bit clearer. I did see the "unpack and broadcast" method you suggested, but I interpreted the documentation to mean it was possible to create sequence-over-sequence tensors (e.g. sentences in a document, words in a sentence).  

I assume this is not possible, so the solution would be to create separate input sequences and unpack/broadcast as needed.

Closing for now but if this is incorrect, please re-open or edit as necessary.

**Comment by VHellendoorn** [comment]
@nmfisher I wondered the same thing and found your question. The solution you propose is interesting: do you a working example of how this could be used for a nested model?

**Comment by nmfisher** [comment]
Not exactly - due to memory constraints, I ended up padding one "free" dimension to a fixed length, so there was no need to have strictly nested sequences.

What I am using now looks more like this (paraphrased, not guaranteed to be error-free):

def create_model():
    word_lstm = Recurrence(LSTM(dim),return_full_state=False)
    sentence_lstm = Recurrence(LSTM(dim),return_full_state=False)

    @Function
    def model(inputs:WordSequence[Tensor[num_sentences]]):
            word_lstm_outputs = lstm(inputs)
            word_lstm_outputs = C.ops.sequence.unpack(word_lstm_outputs, padding_value=0, 
    no_mask_output=True)
            sentences = C.ops.transpose(word_lstm_outputs, perm=(1,0,2))
            sentences = C.ops.to_sequence(sentences)
            return sentence_lstm(sentences)
    return model

This represents a document as a sequence of tensors, where the nth element in the sequence is a tensor with entry m containing the vocabulary index of the nth word in the mth sentence.

I did try what was originally proposed, which from memory looked something like this:

def create_model():
    word_lstm = Recurrence(LSTM(dim),return_full_state=False)
    sentence_lstm = Recurrence(LSTM(dim),return_full_state=False)

    @Function
    def model(word_seqs:WordSequence[Tensor[1]], sentence_seqs:SentenceSequence[Tensor[1]]):
            word_lstm_outputs = lstm(inputs)
            word_lstm_outputs = C.ops.sequence.unpack(word_lstm_outputs, padding_value=0, 
    no_mask_output=True)
            sentences = C.sequence.broadcast_as(word_lstm_outputs, sentence_seqs)
            return sentence_lstm(sentences)
    return model

That would give each document two representations - a sequence of word vocab indices, and a sequence of sentence indices (which is basically just equivalent to np.range(num_sentences) to capture the sequence length).

However I did experience some weird issues when training this version (or at least something similar to it) - I was getting NaN outputs, which I suspect was because the sequence "reset" flag was not being pushed between differently-sized batches. I don't have enough evidence/reproducability/time to open up a specific issue on this though.

Not sure if this answers your question - if not, it might help if you give me a bit more context around what you're looking to do?

**Comment by VHellendoorn** [comment]
Thanks for your quick response! Both solutions are helpful, thanks for sharing them. The `broadcast_as` version is interesting: I suppose it would initialize every sentence `lstm` equally with the hidden states across all words in the whole document. I am interested in a character-word hybrid model, where each word vector is first embedded as a recurrence over its characters and then passed into the sentence "main-line" recurrent model, so this might not be quite applicable.

The first-presented solution makes sense, although the fixed-length constraint is a bit unfortunate as words can have very different lengths in my data. I tried a variant of this in which I created a custom step function for `Recurrence` that would run a character sequence model on the input, but the custom function signatures were not permissive. I don't think CNTK is the right tool for the job here, due to its rigid sequence treatment. Thanks for your pointers though!

**Comment by nmfisher** [comment]
Do you mind posting the variant you tried with the custom step function? I think it is possible to do what you want with CNTK - I'd like to try and get your version working to see to see if it runs into the same NaN issues I was experiencing.

**Comment by VHellendoorn** [comment]
Absolutely! The core of it looks like this:
```
def custom_step(hidden_dim):
	gru = C.layers.GRU(hidden_dim)
	char_rnn = C.layers.Recurrence(C.layers.GRU(hidden_dim))
	
	@C.Function
	def step(h, x):
		e = char_rnn(x)
		return gru(h, e)
	
	return step

x = C.sequence.input_variable((max_word_len, ascii_dim), name="x")
y = C.sequence.input_variable(vocab_dim, name="y")

step = custom_step(hidden_dim)
rnn = C.layers.Recurrence(step)
z = C.layers.Dense(vocab_dim)(rnn(x))
```
Now I'm not quite sure if the code inside the step function does the right thing; technically `x` should be a non-sequence variable in there, which makes sense for step functions, so that I could call `to_sequence`, then use `char_rnn` and maybe `reduce_sum`. But if you check the signature of `step`, it treats `h` and `x` as a `Sequence`. Of course, I tried adding a signature to `h` and `x` that makes them `Tensor`s, but then the call to `Recurrence` fails because that one passes un-typed variables to the now typed function `step`.

I also tried a series of steps like `unpack(x...) >> transpose >> to_sequence >> char_rnn` and then `unpack` again, but CNTK balked at the signatures that this would give me. It does look like this code is doing the right thing based on the tensor shape that comes out of `char_rnn`, but it may need further inspection. Hope it can help you at least.

**Comment by KeDengMS** [comment]
h and x in step function is treated as sequence, because the RNN loop would take time slices on them and run the slice through the step function. The above function does not seem to do the nested RNN as you'd thought.

For char rnn case, you can try something below to reset RNN state in char rnn stage:
```
import cntk as C
import numpy as np

# run char rnn
char_vocab_dim = 255
char_embed_dim = 50
char_rnn_dim = 10
char_idx_seq = C.sequence.input_variable(()) # char_vocab_dim indices
char_emb = C.layers.Embedding(char_embed_dim)(C.one_hot(char_idx_seq, num_classes=char_vocab_dim))
char_boundary = C.sequence.input_variable(()) # 1 to mark beginning of char, 2 for the end

def gru_reset(dim):
    cell = C.layers.GRU(dim)
    @C.Function
    def _func(dh, x_b):
        b = C.slice(x_b, 0, -1, 0)
        x = C.slice(x_b, 0, 0, -1)
        dh = C.element_select(C.equal(b,1), 0, dh)
        return cell(dh, x)
    return _func

char_rnn = C.layers.Recurrence(gru_reset(char_rnn_dim))(C.splice(char_emb, char_boundary)) # run GRU with reset on char boundary
char_rnn = C.sequence.gather(char_rnn, C.equal(char_boundary,2))

# run word rnn
word_dim = char_rnn_dim
word_hidden_dim = 10
word_rnn = C.layers.Recurrence(C.layers.LSTM(word_hidden_dim))(char_rnn) # you may use optimized_rnnstack for better perf

data_idx = [[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],
            [0,1,2,3,4,5,6,7],
            [0,1,2,3,4,5,6,7]]
data_bnd = [[1,0,0,0,0,2,1,0,2,1,0,2,1,0,0,2,1,0,0,2],
            [1,0,2,1,2,1,0,2],
            [1,2,1,0,0,2,1,2]]
feed = {char_idx_seq:data_idx, char_boundary:data_bnd}

print(word_rnn.eval(feed))
```

**Comment by VHellendoorn** [comment]
Thank you, that is a very helpful idea! It looks like CNTK can do this after all, thank you for proving me wrong :)
A small correction for others using this: replacing the `0` in the `_func` definition in the line: ` dh = C.element_select(C.equal(b,1), 0, dh)` with `C.constant(shape=char_rnn_dim)` fixes the `ValueError` (it makes the shape passed to `cell` consistent).

This might be a good thing to have for an Example/Tutorial; I'm going to make a working version of this anyways, let me know if there is a need for such a thing in the CNTK repo.

**Comment by KeDengMS** [comment]
Glad it helped. Yes the shape of 0 here should be the same as char_rnn_dim. Actually this is the initial hidden state value which can be set to a parameter if the model wants to train on it. You can also play with other varieties like bidirectional char rnn if needed.
CNTK is an open source effort and we'd love to have the community to provide new examples and tutorials. You can either send PR to CNTK, or create your own GitHub/blog to provide solutions.

**Comment by xiezhq-hermann** [comment]
Hi, thanks your great discussion, here a similar problem encounter me:
I'm working with a passage with different paragraph, and every paragraph have different length of words.
I need to do a series of complex operation in the paragraph (the same for every paragraph), and finally concatenate them all (all vector representation of paragraphs).
Could you please give me some hints? I found it's hard to do without a nested axis, the recurrent function is not so suitable.

**Comment by KeDengMS** [comment]
@xiezhq-hermann maybe [sequence.unpack](https://cntk.ai/pythondocs/cntk.ops.sequence.html#cntk.ops.sequence.unpack) is what you are looking for.
