### ISSUE TITLE
How to dump the value of labels?

### ISSUE THREAD

**Issue by wyjzz** [Microsoft/CNTK#311]
I use "write" action to output values of nodes,values of feather is correct.But values of labels output is correct .Just serveral ZERO.Why?

**Comment by frankseide** [comment]
Labels are stored in a one-hot representation. You should have exactly one "1" in that output amongst all those zeroes.

There is a way to tell CNTK to instead write the index of largest entry, and you can also specify a labelMappingFile so that it will print it in clear text. In the 'write' command's parameter section, please add something like this:
```
    format = [
        type = "category" # or "real"
        transpose = false # true will print one row per sample vector
        labelMappingFile = "$ModelDir$/vocab.wl" # optional mapping for type "category"
        #precisionFormat = "5.2" # optional printf format, e.g. this would be %5.2f for type "real"
        sequenceEpilogue = "\t// %s\n" # optionally inject the node name after the sequence
    ]
```
One problem is that this applies to all nodes simultaneously, i.e. since your features are not one-hot, your feature output will no longer be meaningful. You would have to run two separate "write" commands.
