### ISSUE TITLE
Multiple Backwards with one Forward

### ISSUE THREAD

**Issue by nosalorenz** [microsoft/CNTK#3133]
Hi,
I need to do backpropagation with many different rootGradientValues after doing a single Forward pass.
But at the second backward pass errors are thrown (wrong matrix shape), I guess this is because gradients are computed in place.
Is there a way to avoid backpropagation in place, or to copy the whole network? It is really a waste of time to do Forward again!!!
Thanks

**Comment by loripino21** [comment]
analyising where the error is thrown, one of the following nodes can cause the issue: SpliceNode or GatherNode or UnpackBatch

**Comment by loripino21** [comment]
After some hours digging into CNTK, I understood that there is a mechanism of Matrix reuse to spare memory. Nice. But there shoul be a way to disable it.
I tried CNTK::Internal::DisableGradientAccumulationOptimization() and CNTK::Internal::DisableForwardValuesSharing() and combination of the two with no luck.
BTW, CNTK::Internal::DisableForwardValuesSharing() causes problems to CNTK as Backward stops working even at first call.
Please help!

**Comment by loripino21** [comment]
Ok, Thanks, I will try it.
But is there some way to keep memory optimization as much as possible and Be able to do multiple backwards?
Even a suggestion to modify source code on my own would be very useful. I really need this.
Thanks!

**Comment by loripino21** [comment]
If I got it correctly, it would be enough to modify
`virtual void ReleaseMatricesAfterBackprop(MatrixPool& matrixPool) override`
implementation in ComputationNode.h to avoid to release Value matrix:
` ReleaseMatrixToPool(m_value, matrixPool);`
Is that correct?
This retains all possible optimizations (Gradient reuse, Value matrix release+reuse in fwd when not needed in backprop) but make possible multiple backprops by retaining exactly and only needed Values.
Any advice where and how to release them after all backprops? Otherwise they are not reused even in subsequent fwd/bwd cycles.
BTW there is a potential source of low performance in void ComputationNetwork::AllocateAllMatrices() :  
`// Root node's information will be used and should not be shared with others, also it's small (1x1)`
 That's not always true, for example in my case the output of the root function is a big matrix.

**Comment by KeDengMS** [comment]
The memory sharing structure is built when the graph is first evaluated, so if you don't release the memory back to pool, it just means the memory is not going to be shared, not actual memory leaks. I think if you don't release m_value to pool, it should do what you needed. Please try modify the code and let me know your findings.

**Comment by loripino21** [comment]
I thought about this another bit and since `ReleaseMatricesAfterBackprop(MatrixPool& matrixPool)` is overridden in many ComputationNodes, and also since Gradient matrix if released could be used for whatever reason, including storing the value of another subsequent node, I made a conservative choice and ended up avoiding the call to that method at all. So in ComputationNetworkEvaluation.cpp it became:
`                if ((n != trainRootNode) && n->NeedsGradient() && Globals::ShouldOptimizeMatricesAfterBackprop())
                    n->ReleaseMatricesAfterBackprop(m_matrixPool);`
I tried the code and by now all is working smoothly!

**Comment by loripino21** [comment]
No. there is something wrong. At second backward cycle a matrix full of 0 is returned! What could be wrong?

**Comment by loripino21** [comment]
Ok! There was an User Function in between, so the following lines in UserDefinedV2FunctionNode.h
` if (!inSEQMode || fr.timeIdxInSeq == 0)
        {
            m_currentBackpropStatePtr = nullptr;
        }`
were blocking the Backpropagation at second call. skipping them when necessary does the trick.
Now multiple bwd cycles yeld always the same result, everything is working!

**Comment by KeDengMS** [comment]
Glad to know it works! May I know the why you need to multiple backprop with one forward? If this is of value to other users, we may add a global option for the change you proposed.
