### ISSUE TITLE
[Bug Report] CNTK training bug of multi-dimensional LSTM (e.g. TF-LSTM)

### ISSUE THREAD

**Issue by kaituoxu** [Microsoft/CNTK#3136]
When I used CNTK to implement Time Frequency LSTM (TF-LSTM [1], a 2-D LSTM), I noticed that there maybe exist a training bug under NDL or BrainScript as this issue says (https://github.com/Microsoft/CNTK/issues/738)
And I found a solution for this bug in this commit: https://github.com/Microsoft/CNTK/commit/f34b7d78f0f9fbfe889934cf68909cc12fe9526c

The bug looks like: **when training TF-LSTM, the weight update is executed multiple times on the same node in one mini-batch training.**

The new bug I found is:
When I use this commit to solve the repetitive update problem and train TF-LSTM models, the loss curve of single-GPU training looks fine (loss decrease steadily), but **the loss curve of BMUF multi-GPU training has a lot of jitter**. 
My partial experiment also shows that the loss curve of ASGD multi-GPU training looks fine (loss decrease steadily).

I'm working on fixing this TF-LSTM multi-GPU training problem between BMUF and ASGD, and I'm reading the source code to confirm the existence of this repetitive update problem.

I think it's important to confirm the existence of this repetitive update problem and merge the solution into master branch, or we can not correctly train any multi-dimensional LSTM using CNTK NDL or BrainScript, such as F-LSTM[2], TF-LSTM, and Grid-LSTM[3].

[1] https://www.microsoft.com/en-us/research/wp-content/uploads/2016/11/TFLSTM.pdf
[2] https://www.microsoft.com/en-us/research/wp-content/uploads/2016/04/spectral_LSTM.pdf
[3] https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45401.pdf

**Comment by KeDengMS** [comment]
The reason I didn't merge that fix is that learnable parameters should not duplicate in the learnableNodes in the first place. I suspect the bug really comes from [here](https://github.com/Microsoft/CNTK/blob/master/Source/ComputationNetworkLib/ComputationNetwork.cpp#L549-L568), that when nodes being pushed to learnable parameters it’s not pushed in visited set. 

Python should not have the problem though as it passed a dictionary of Parameter to gradient, where the uniqueness of dict key should prevent it from being updated twice. Otherwise, we’ll have all sorts of problems in parameter sharing cases.

**Comment by KeDengMS** [comment]
Thanks for the detailed report. Could you send a PR for this fix?
