### ISSUE TITLE
CNTK, going forward

### ISSUE THREAD

**Issue by tempdata** [Microsoft/CNTK#3158]
Hi, I am wondering about the future of CNTK. Is CNTK still being used for training and inference? With new Windows ML and ONNX, please let us know the future roadmap of CNTK.

**Comment by KeDengMS** [comment]
I think if you view the computation graph as C++ source code, then you'll have analog as below:

CNTK/Caffe2/Pytorch/MxNet/TF --> IDE for writing C++ source code
ONNX --> the C++ standard
Windows ML/TensorRT/etc --> the C++ compiler and executor for the compiled graph on particular platforms

The vision is that model representation/training/inference should be decoupled from the toolkit user choose to compose their model. We will continue to improve CNTK, but a more important thing is to set up the standard and create a eco system on top of that standard for training and inference services. In the end, what matters the most to our customer is how convenient and fast they can try out different ideas with their own dataset in large scale.

Besides, with a standard of representing computation graph, different vendors can provide their optimization in either software or hardware, regardless of the toolkit selection. That's why lots of companies are involved in the ONNX effort.

**Comment by tempdata** [comment]
@KeDengMS  Thank you for the detailed response.
