### ISSUE TITLE
projection layer and delay issues in lstmp-3layer-opt.ndl

### ISSUE THREAD

**Issue by Turan111** [Microsoft/CNTK#323]
Hi,
I haven't found any projection operation in lstmp-3layer-opt.ndl config file. According to the name LSTMP_c1024_p256_x3 there should be projection layer with the dimension 256. Could you please clarify this question. 
And how to delay the output state label for example by 5 frames to take account future 5 frames as written in the Google paper. Is there any parameter for this?

**Comment by dongyu888** [comment]
Projection happens inside the macro. 

 

        Wmr = Parameter(outputDim, cellDim, init="uniform", initValueScale=1);

        output = Times(Wmr, mt);

outputDim is the projection dim (256). cellDim is LSTM cell dim (1024).

**Comment by Turan111** [comment]
Many thanks for your answer.
Now it is clear. but there should be a mistake in numbers.
Because from operations   
hiddenDim = 512
   
LSTMoutput1 = LSTMPComponent(basefeatDim, hiddenDim, cellDim, featNorm, cellDimX2, cellDimX3, cellDimX4);

    LSTMPComponent(inputDim, outputDim, cellDim, inputx, cellDimX2, cellDimX3, cellDimX4) = [

        Wmr = Parameter(outputDim, cellDim, init="uniform", initValueScale=1);
As we see outputDim is 512.

And what about delaying of the output state label. Should we do it in the mlf label file or there is a special parameter for this?

**Comment by dongyu888** [comment]
You can get a window of frames (e.g., 11) from the reader and inside your NDL file use RowSlice to get the right slice as the input feature.

**Comment by wolfma61** [comment]
I assume Dong answered this ... for further question please create new issue(s)

**Comment by Turan111** [comment]
Dear Mr. Dong,

I formed config files as following    
in CNTK config  
 features = [
            dim = 1320
            type = "real"
            scpFile = "$DataDir$/train.list"
        ]

And in the ndl file:
# define basic i/o
    basefeatDim = 120
    rowSliceStart = 1200 
    featDim = 1320
    cellDim = 1024
    cellDimX2 = 2048
    cellDimX3 = 3072
    cellDimX4 = 4096 
    hiddenDim = 512
    features = RowSlice(rowSliceStart, basefeatDim, Input(featDim));
    labels = Input(labelDim);
    featNorm = MeanVarNorm(features);
    # layer 1
    LSTMoutput1 = LSTMPComponent(basefeatDim, hiddenDim, cellDim, featNorm, cellDimX2, cellDimX3, cellDimX4);

But output model was with the input dimension 1320 instead of 120.  What is the problem?

**Comment by dongyu888** [comment]
Since features are read from your data, it should not be a function or macro. What you should use is:

 

basefeatDim = 120
rowSliceStart = 1200 
featDim = 1320
cellDim = 1024
cellDimX2 = 2048
cellDimX3 = 3072
cellDimX4 = 4096 
hiddenDim = 512
features= Input(featDim);
featureSlice = RowSlice(rowSliceStart, basefeatDim, Input(featDim));
labels = Input(labelDim);
featNorm = MeanVarNorm(featureSlice);
# layer 1
LSTMoutput1 = LSTMPComponent(basefeatDim, hiddenDim, cellDim, featNorm, cellDimX2, cellDimX3, cellDimX4);

 

By doing so, features will be consistent with the features you specified in the reader section and should have 1320 dim.
