### ISSUE TITLE
Cannot compile the source code under Win8 + VS2013 Update 5

### ISSUE THREAD

**Issue by leonardomgomes** [Microsoft/CNTK#324]
Hi, I am new to CNTK, so I followed the step-by-step setup on https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows

But, when I'm compiling code I got the following errors:
1>  nvcc fatal   : No input files specified

2>LINK : fatal error LNK1104: cannot open file 'MathCUDA.lib'

3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code 9009.

Does anyone have any idea how to solve this?
Thanks!

I attached the error log.

[compilation error CNTK.txt](https://github.com/Microsoft/CNTK/f
[compilation error CNTK.txt]%28https://github.com/Microsoft/CNTK/files/206468/compilation.error.CNTK.txt%29
iles/206467/compilation.error.CNTK.txt)
 as a txt file.

**Comment by leonardomgomes** [comment]
[compilation error CNTK.txt](https://github.com/Microsoft/CNTK/files/210733/compilation.error.CNTK.txt)

**Comment by wolfma61** [comment]
Hi -

looks like you are failing in the first step of the compilation, the cuda build.

not sure how to diagnose this remotely, couple of suggestions:
- make sure all the environment variables are set as mentioned in the setup part of the wiki and all the needed tools are installed

- try a CPUONLY build (see wiki), since this doesn't compile the cuda part of the library. what happens here

according to the error message the NVidia cuda compiler can't find its input file. 

There are some characters in your path which are 'non standard' or 'not necessarily recommended'... i.e. the '&'. I also see several inconcistencies in the output:
...C:\Users\L&L\Desktop\Léo\cntk\CNTK-master\Source\Math...
and 
...C:\Users\L  & L\Desktop\Léo\cntk\CNTK-master\x64  (& and 'spaces')

hope this helps

thx
Wolfgang

**Comment by mahilleb-msft** [comment]
Closing. Please create a new issue if you run into problems with building latest master.
