### ISSUE TITLE
Bypass storage of intermediate models

### ISSUE THREAD

**Issue by axonUH** [Microsoft/CNTK#329]
Hi,
I'm interested in switching off the storage of intermediate models. For instance, if I run the Simple2D Example (https://github.com/Microsoft/CNTK/tree/master/Examples/Other/Simple2d), the intermediate models are placed in the Output/Models folder. (I'm running CNTK using binaries in Windows7). The final model exists as simple.dnn and the intermediate models have simple.dnn.0, simple.dnn.1 etc. I would like switch off the storage of simple.dnn.0,  simple.dnn.1 etc. as I think they are not necessary for future activities. Is there someway to do this?

Thanks

**Comment by yzhang87** [comment]
try this: keepCheckPointFiles = false

**Comment by axonUH** [comment]
It was not the effect I was looking for. The default was false anyway. I turned it on to true and it gave me .ckp files for every epoch. I did set it to false and there was no effect. Thanks for the quick response anyway.

**Comment by dongyu888** [comment]
We have the option to delete checkpoint files but not the intermediate model files. This is because in many cases you will need to load old models for model selection, etc. 

It’s not too difficult to add this feature if this is indeed desired, by following the same pattern as the keepCheckPointFile option.

**Comment by axonUH** [comment]
Thanks for the information
