### ISSUE TITLE
Python GRU definition seems to be different from that in original paper

### ISSUE THREAD

**Issue by fwaris** [Microsoft/CNTK#3292]
https://github.com/Microsoft/CNTK/blob/e8f2db45e4e12878783d5093db2a0602daf7f32c/bindings/python/cntk/layers/blocks.py#L323

The line referenced above is written as:

 ht = (1 - zt) * ct + zt * dhs 

From reading the paper (https://arxiv.org/pdf/1502.02367.pdf and another reference (http://colah.github.io/posts/2015-08-Understanding-LSTMs/)

It seems that the line should be:

ht = ((1 - zt) * dhs) + (ct * zt)

I may be wrong but would not mind a 2nd opinion.

**Comment by VHellendoorn** [comment]
The difference between these equations is just which term (of dhs and ct) is scaled by (1 - zt) and which by zt. Since zt is sigmoid activated, swapping these two does not matter for the learning process; all it will do in the currently used formulation is learn to set it to 0 to overwrite parts of its memory and 1 to remember instead of the reverse.

**Comment by fwaris** [comment]
that makes sense. Thanks!
