### ISSUE TITLE
Unknown compiler version - please run the configure tests and report the results

### ISSUE THREAD

**Issue by IvanFarkas** [microsoft/CNTK#3344]
Getting annoying ```Unknown compiler version - please run the configure tests and report the results``` warning message in the build output due to **ancient old** _Boost 1.60.0 msvc 14.0_

Would it be possible to update the solution and documentation with **[Boost 1.67.0 msvc 14.1](https://sourceforge.net/projects/boost/files/boost-binaries/1.67.0/boost_1_67_0-msvc-14.1-64.exe/download)**, please?

As a matter of fact why CNTK solution is using these **ancient old** 3rd party libraries instead of non conflicting lates versions. please?

**Comment by KeDengMS** [comment]
Thanks for pointing it out. To upgrade dependencies we need to change our test environment, and since this bug is non-blocking, the priority is low.

**Comment by IvanFarkas** [comment]
Please make this a **priority**!

**Comment by mqudsi** [comment]
That's extremely rude of you, @IvanFarkas. A more constructive reply (and more likely to get you what you wanted) would be to explain why this is a priority for you, since going by all appearances, this is just an information message in the build output. Naturally it would be an extremely low priority item as compared to actual build errors or real bugs, so the onus is on you to provide a good reason.

In all cases, putting up with behavior like yours is why open source maintainers don't last very long.

**Comment by IvanFarkas** [comment]
@mqudsi Your tone is unacceptable and displays aggression and lack of intelligence!
This post was unanswered for almost a year now.
Who are you to lecture me?
Lead, follow or get the hell out the way boy!
If you cannot resolve this, go and do something else!

**Comment by abdulmounaim** [comment]
@IvanFarkas You don't talk to people who are doing you a favor like that, BOOMER!

**Comment by IvanFarkas** [comment]
It does not matter, as Bill Gates said recently.
It’s DEAD!!!
People who lack intelligence, usually blame that way and do me me know favors, please, but DO YOUR JOB!!!

**Comment by thiagocrepaldi** [comment]
CNTK has been deprecated

**Comment by latsa** [comment]
> "People who lack intelligence, usually blame that way and do me me know favors, please, but DO YOUR JOB!!!"
@IvanFarkas, people who lack intelligence might not be able to spell properly.

**Comment by IvanFarkas** [comment]
@latsa People who are completely stupid keep protecting a beaten dead horse!
