### ISSUE TITLE
System.ApplicationException on .NET Core with NuGet: 2.6.0-rc0.dev20180821

### ISSUE THREAD

**Issue by bhrnjica** [Microsoft/CNTK#3373]
I have converted my CNTK 2.5.1 based .NET library into .NET Core with the latest  NuGet: 2.6.0-rc0.dev20180821

Previously on CNTK 2.5.1 and .NET my application works ok, once I converted to .NET Core with CNTK 2.6-rc, I got this Exception.

> System.ApplicationException: 'This Value object is invalid and can no longer be accessed. This usually happens when a temporary Value object returned by the CNTK library is not cloned and accessed later after it has been erased by the library. The Value objects created inside and returned by the library from APIs like Forward, Backward etc. are temporary and are only guaranteed to be valid until the next Forward/Backward call. If you want to access the Values later, you must explicitly clone them.

The I realized that I defined global variable `validationData `(class member) which holds the MiniBatch data for validation, since I don't want to call GetNextMinibatch every time I want to run `trainer.TestMinibatch(validationData, device)`  on each epoch against the same data-set. 

Seems CNTK disposed this variable without my will.

**Comment by bhrnjica** [comment]
It cannot be determined when the `validationData` is disposed, since I have experienced different behaviors when using it in Console App or Windows Desktop App.  
Anyhow this exception can be solved by checking is data in the mini-batch valid. So in the above case  the `validationData` can be used safely like this:
`if (validationData == null || validationData.Values.Any(x=>x.data.IsValid == false)) `

**Comment by YanYas** [comment]
I'm using [VL](https://vvvv.org/documentation/vl) for a project with CNTK. I updated to 2.6.0 to see if I could train with ConvolutionTranspose() in .NET but this has opened up a bit of a problem because I use serialized data very little and rely on values created from data in Ram. This usually is cached used only when training. Now, however, just trying to create MiniBatchdata causes the value to vanish.

My fix has been to create a batch as I did previously, cache that value and then create an Alias of the cached Batch and then CopyFrom the cached Batch, using the Alias result as the source and the cached value as the input. 
var picture == 1000 words;

![vlml-mnist-create mbd](https://user-images.githubusercontent.com/9497052/46116167-98868800-c1f2-11e8-9408-ed98df72a05b.png)

I'm keeping my eye out for potential drawbacks, such as heavy memory use, but it would be preferable if the library behaved as it did before or it is explained why the change was necessary and advantageous.

**Comment by YanYas** [comment]
Actually, this still a problem, as my memory blows up. I cannot dispose of the value once it hits the TrainMiniBatch(). Trying to dispose of the value once it has been trained; the Dispose() is called but the data isn't removed from memory. Ideally, the data is disposed of in TrainMiniBatch().
