### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Microsoft/CNTK#34]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [PrintBuiltInfo](https://github.com/Microsoft/CNTK/blob/2462647f625213ffdd3ec97d3290c1f9a31d44f8/Source/CNTK/CNTK.cpp#L288)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action.") ⇒ [setupTimeout](https://github.com/Microsoft/CNTK/blob/2462647f625213ffdd3ec97d3290c1f9a31d44f8/Source/Common/CrossProcessMutex.h#L99)

**Comment by mahilleb-msft** [comment]
Yes, this would be better. Contributions would certainly be welcome :)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by frankseide** [comment]
Thanks for the suggestion. However, my hunch is that might be too much for our needs. Minimizing dependencies is also a property to strive for.

In my view, the built-in mechanism of C++ exceptions is perfectly fine for us. CNTK does not really have recoverable errors, with one exception of delay-loading of optional components (e.g. if no CUDA driver is present, we fall back to CPU mode), and the other being simple retry loops for network I/O. All other errors should simply log and fail fast due to our command-line tool nature. In such context, the only reason we ever catch exceptions is to add to their error message and rethrow, and log it at one centralized place.

One problem is how to deal with APIs that don’t throw, like fprintf(). If we need to replace those APIs, I would opt for replacing them with throwing ones. E.g. we already have an fprintf() variant that throws (fprintfOrDie()).

PrintBuiltInfo() is sort of a special case though, since its output is not critical. We could replace all fprintf() calls by fprintfOrDie(), but I am not sure whether the added code complexity (readers may not know what fprintfOrDie() means) is worth it in this particular place, because all we can do is catch an error that means “cannot write to stderr/log” and write that to stderr/log, which we won’t be able to do either.

Thanks!

Frank

**Comment by elfring** [comment]
>If we need to replace those APIs, I would opt for replacing them with throwing ones.

Would you like to delegate such a software maintenance task to any dedicated development tool?

**Comment by frankseide** [comment]
There is a trade-off between dependencies (=effort of getting all dependencies in place, learning curve, version management, IDE integration, and doing so in both Linux and Windows) vs. added value.

My 2 cents would be that probably that trade-off favors simplicity in our case (where most non-throwing APIs are already encapsulated).

**Comment by wolfma61** [comment]
there is ongoing work in this area, but we will not do a complete redesign
