### ISSUE TITLE
How to create custom operations?

### ISSUE THREAD

**Issue by chenzhekl** [Microsoft/CNTK#340]
Hello, I am a graduate student currently doing projects about deep learning. From time to time there is need to create custom operations for experiment. But I was unable to find any documentations. Could you help provide a guide?

**Comment by pedronahum** [comment]
Both MXNet and TensorFlow provide details instructions to create custom operations and/or custom layers. Any pointer here would be greatly appreciated.

**Comment by cha-zhang** [comment]
For Python custom layers using existing primitive functions, you could take a look at the layers library: 
https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/layers.py 
for examples. 

For primitive functions that CNTK doesn't offer, the V2 library allows users to implement their own primitive functions by deriving from an abstract base interface and proving implementations for the forward and backward methods. These functions can thereafter be composed with other built-in functions. You can do this at the C++ API level or the python level. This facility is currently under development and is expected to become available in 2-3 weeks. 

Note that extensions created at the python level will not be the most optimal due to the extra data copying from device to CPU memory and back. However, they are the simplest way to implement new primitive operations that cannot be expressed as combination of existing primitive functions and once proven to be useful, should be ported to the C++ layer for optimal performance.

**Comment by pedronahum** [comment]
Excellent, thank you. A couple of extra weeks are worth waiting then.
