### ISSUE TITLE
How to determine the parameters for AlexNet

### ISSUE THREAD

**Issue by rold2007** [Microsoft/CNTK#390]
I am trying to modify AlexNet to support a smaller input image size. I wonder if I should also modify the following parameters, and if so how should I determine the values to use. Seeing values such as 2.07 I guess that this was not chosen by a human.

Parameters:
    conv1WScale = 0.95
    conv1BValue = 0
    conv2WScale = 2
    conv2BValue = 1
    conv3WScale = 2.07
    conv3BValue = 0
    conv4WScale = 2.9
    conv4BValue = 1
    conv5WScale = 2.4
    conv5BValue = 1
    fc1WScale = 6.4
    fc1BValue = 1
    fc2WScale = 3.2
    fc2BValue = 1
    fc3WScale = 3.2
    fc3BValue = 1

**Comment by Alexey-Kamenev** [comment]
Hi David,
These values were chosen by a human and that human was me :) Sadly, that human also failed to document the process of obtaining these magic values - a mistake that I will try to correct in this reply and then in samples/Wiki.
When you use LearnableParameter with normal distribution for initial values, CNTK initializes it with 0 mean and standard deviation of: `0.2 * initValueScale / sqrt(NumColumns)` - this is described in our book, but not yet in the Wiki. In the original Krizhevsky paper they initialized all weights using stdev of 0.01. So to come up with correct values for each layer in case of CNTK, you would need to use the following formula: `initValueScale  = StdDev * sqrt(NumColumns) / 0.2`. So in case of the first convo layer (`conv1`) we get: `0.01*sqrt(11*11*3)/0.2 == 0.952...` The problem, of course, is that you have to compute these values for each layer separately.
Now, initializing weights of a deep neural network with fixed stddev is now considered a technique from bygone times. One of the most popular modern techniques is due to paper by our own [MSRA]( http://arxiv.org/abs/1502.01852). In short, this technique uses the following formula for computing stddev of initial weights for a convolutional layer: `stddev = sqrt(2 / n)` where `n` is the size of the kernel which happens to be number of columns in CNTK. This technique is used in other CNTK samples like ResNet where there is just one value for all convo layers which represents the scaling factor: `sqrt(2)/0.2 = 7.07`
I would probably recommend using the newer technique though I haven’t tried it myself on AlexNet.
Hope this helps.

**Comment by rold2007** [comment]
Thanks for the detailed answer !

**Comment by CPostelnicu** [comment]
From this explanation I understand how conv1WScale, conv2WScale ... conv5WScale are computed. 
My trouble starts with fc1WScale onwards. 

In particular:
- Why does fc1WScale assume NumColumns is 2x2x4096? 
- Why does the first fully connected layer (DNNImageReLULayer) expect a 6x6x256 size at the input?
- How are *BValue weights computed? 
- Why should we be computing and write down the exact values in CNTK model file in the first place (and not just write, for instance, "kW5 * kH5 * cMap4" instead of 2304 for the corresponding parameter at conv5 layer)?

I have tried to compute the output sizes of each layer myself , following the explanation given in the CNTK book at page 42 (the Chellapilla technique part). I assume zero padding when computing Or and Oc (because _zeroPadding_ is set to true in  Macros.ndl when computing the convolution). That gives me:
- conv1 output Or of (224-mod(11,2))/4 + 1 = 56.75 (?). 
- pool1 output Or of (57-3)/2. 
- conv2 output: 28x28x192
- pool2 output: 13x13x192 (Or = (28-3)/2 = 12.5)
- conv3 output: 13x13x384 (Or = (13 -mod(3,1))/1 + 1 = (13-1)/1 +1 ) 
- conv4 output: 13x13x256
- conv5 output: 13x13x256
- pool3 output: 5x5x256 (Or = (13-3)/2 = 5)
- DNNImageReLULayer output: 4096 x 1 (?)

Following this reasoning, even if I round up all the results I get (I can guess rounding up is not really something I should have to do, if I were doing the computations right), the input expected at the first fully connected layer becomes 5x5x256 (?!).  

As you can guess I am just getting started with CNTK and images. Any help would be much appreciated...
