### ISSUE TITLE
Is there a Sequence Reader for numerical feature vectors/ frames to be used with LSTM?

### ISSUE THREAD

**Issue by wgkgk** [Microsoft/CNTK#423]
Hi, I am using the binary version of cntk  (CNTK version 1.1). I want to build an LSTM or BLSTM system for speech (using numerical acoustic features). In CNTK book, the examples are given with language modeling and both sequential readers are for words.
1. Is there any way we can use UCIFastReader to read sequential/ frame wise data to be used for LSTM? or is there any examples on LSTM or RNN with numerical sequential features that I can find ? 
2. Can we use cntk to build BLSTM?

Thank you.

**Comment by slaweks17** [comment]
Hi,
I think you are supposed to use CNTKTextFormatReader for sequential data (incl numeric). I am actually using UCIFastReader (because training is faster), but to do that, I 
1) provide an additional forget signal (0 or 1) that is always 1 except the first record of a sequence
2) modified the LSTM so it takes this additional forget signal and multiplies the state by it.

Regards,
Slawek
