### ISSUE TITLE
CPU only + MKL build errors

### ISSUE THREAD

**Issue by quicktrick** [Microsoft/CNTK#447]
Hello!  Sorry again for newbie questions.  I'm trying to build CNTK on a Windows system without NVidia GPUs. And I've installed MKL.

1. I specified `USE_MKL` in the Preprocessor Definitions of Math project as described [here](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#mkl).
Besides I had to specify all the inherited values except `USE_ACML` individually.
2. I had to set a new environment variable 
`MKL_PATH=c:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.3.207\windows\mkl` 
and I had to specify it in Additional Include Directories instead of `ACML_PATH`.

But still I have a lot of errors.  Most of them are about missing file `math.lib`.  Where can I find it?
The others are about missing CUDA.

How to fix those errors?

**Comment by slaweks17** [comment]
Hi,
As a first step try to build Math project separately. Missing math.lib suggests you fail this step.

Cheers,
Slawek

**Comment by quicktrick** [comment]
Though @alexeyo26 in #442 suggested not install CUDA, cuDNN and CUB, CNTK in its current configuration doesn't build without those components, even in CpuOnly mode. So I installed them. After that MathCUDA project was built successfully.

Trying to build Math project I had to add `$(CUDA_PATH)\include` to Additional Include Directories (besides `$(MKL_PATH)\include`, that I had added previously instead of `$(ACML_PATH)\include`).

Anyway, there is an error while building the Math project.

`LINK : fatal error LNK1181: cannot open input file 'libacml_mp_dll.lib'`

What can I do with that? (It seems to me that I'm the first person trying to build CNTK on Windows with MKL. :))

**Comment by slaweks17** [comment]
Hi,

No, you are not the first one: I built it on a few computers, with various levels of troubles [😊]

Are you using Intel Composer? Make sure you set 'Use Intel MKL' to 'Parallel' in Configuration Properties->Intel Performance Libraries.


Regards,

Slawek

[cid:44039782-ce81-441f-836e-0df3099f15d9]


________________________________
Od: quicktrick <notifications@github.com>
Wysłane: 7 maja 2016 08:21
Do: Microsoft/CNTK
DW: slaweks17; Comment
Temat: Re: [Microsoft/CNTK] CPU only + MKL build errors (#447)


Though @alexeyo26<https://github.com/alexeyo26> in #442<https://github.com/Microsoft/CNTK/issues/442> suggested not install CUDA, cuDNN and CUB, CNTK in its current configuration doesn't build without those components, even in CpuOnly mode. So I installed them. After that MathCUDA project was built successfully.

Trying to build Math project I had to add $(CUDA_PATH)\include to Additional Include Directories (besides $(MKL_PATH)\include, that I had added previously instead of $(ACML_PATH)\include).

Anyway, there is an error while building the Math project.

LINK : fatal error LNK1181: cannot open input file 'libacml_mp_dll.lib'

What can I do with that? (It seems to me that I'm the first person trying to build CNTK on Windows with MKL. :))

**Comment by quicktrick** [comment]
Hi Slawek!

Thank you very much for your help!

I'm not using Intel Composer.  I set  'Use Intel MKL' to 'Parallel' in Configuration Properties->Intel Performance Libraries, but it didn't help.

There are explicit links to `libacml_mp_dll.lib` and `libacml_mp_dll.dll` in `Math.vcxproj`:

`<AdditionalDependencies>libacml_mp_dll.lib;Common.lib;%(AdditionalDependencies)</AdditionalDependencies>`
`<DelayLoadDLLs>libacml_mp_dll.dll; $(CudaDlls); %(DelayLoadDLLs)</DelayLoadDLLs>`

and also:

`<AdditionalLibraryDirectories>$(ACML_PATH)\lib;$(OutDir)</AdditionalLibraryDirectories>`

I can replace `$(ACML_PATH)\lib` with `$(MKL_PATH)\lib\intel64_win\' but what Intel's `.lib` and `.dll` files should I use instead of `libacml_mp_dll.lib` and `libacml_mp_dll.dll` ?

Thanks again!

Alex

P.S. С Днём Победы! :)

**Comment by slaweks17** [comment]
Hi,
In my case, I did specify directory where the AMD library was installed 
Additional Library Directories->C:\progs\AMD\acml5.3.1\ifort64_mp\lib\MT;$(SolutionDir)$(Platform)\$(Configuration)\
but this was just to make build happy. At the end, there was message during the build that the AMD library was not used.

Regards,
Slawek

**Comment by quicktrick** [comment]
Thank you Slawek!

Too many problems with MKL, the code isn't adapted to it yet. I've uninstalled MKL and installed ACML.  Everything works fine now.  Thanks again for your help!

Alex
