### ISSUE TITLE
CPPEvalClient.cpp  Unhandled exception

### ISSUE THREAD

**Issue by WalterGVT** [Microsoft/CNTK#452]
Hi,
I am trying to run the CPPEvalClient.cpp but during the call during the call  model->CreateNetwork(...) I obtain :

Unhandled exception at 0x00007FFE7FDF1F28 in CNTK_APP.exe: Microsoft C++ exception: 
Microsoft::MSR::CNTK::ExceptionWithCallStackstd::runtime_error at memory location 0x000000E06C3CE5D0

My source is the exact copy of CPPEvalClient.cpp where in order to avoid a compilation error I had to change   auto hModule = LoadLibrary(L"evaldll.dll");
with           auto hModule = LoadLibrary(LPCSTR("evaldll.dll"));  
(don't know why but now it compiles correctly).

note: 
My C++ project contains only CPPEvalClient.cpp.
I have not compiled CNTK, I'am using the binaries Ver-1-1 (which I copied in the debug folder of my project).
I set the modelFilePath to the correct path  ....\MNIST\Output\Models\01_OneHidden  of my pc.

Do you have any suggestion about this error ? 
Thank you.

Walter

**Comment by gaizkan** [comment]
Hi Walter,
I am assuming you copied the Eval.h and added it to your project.

I created a separate project (Win32 Console) and set the output dir to where the cntk binaries reside.
I copied the Eval.h from the latest repository (but it hasn't changed in a long time) to where the binaries reside
I then included the Eval.h from where the binaries reside into the project.
In the Property Pages for the new project, I created a new platform for the project (x64) based on the Win32 platform, and deleted the Win32 platform for the project.
I set the Output Directory (in the Property Pages) to where the binaries reside using a relative path from $(SolutionDir), in my case $(SolutionDir)..\cntk\cntk)
I then included 
`
#include "Windows.h"
`
In the `stdafx.h

**Comment by WalterGVT** [comment]
Thank you Gaizkan,
I have replicated exactly what you suggested and it works! 
In debug mode I have the same previous issue but in release is ok.

In debug mode :  
Unhandled exception at 0x00007FFE7FDF1F28 in CNTK_EVAL.exe: Microsoft C++ exception: Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error> at memory location 0x0000003FD3EFE7A0

No other messages.

It is not clear to me why this happens. Is it any project-setting  that allows me to run in debug mode? It would be very useful.
Thanks,
  Walter

**Comment by ucacaxm** [comment]
I have the same problem: I do not use the LoadLibrary part but instead I link with EvalDLL.lib/.dll on Windows.

I found that the argument passed to CreateNetwork(const string& ) is not correct at all. 
I added cout<<networkDescription in the CreateNetwork  and it prints nothing, the debugger should
a string with garbage. 
The argument may be passed to the DLL in the wrong format or wrong adress ?
maybe a problem of 32 vs 64 bits ?

I am surprise you create a  project with "Win32 platform" whereas CNTK is compiled only on 64 bits ?
Why using the code with LoadLibrary/GetProcAddress (which is not portable on Linux ?) ?
instead of linking with the lib which seems to me the more classical way to use an external lib.
?

Regards,
Alex

**Comment by jhalakpatel** [comment]
I faced the similar issue. Try to recompile the CNTK source with Release/Release_CPU_Only and use it. I worked for me.

**Comment by zhouwangzw** [comment]
@WalterGVT In Debug mode, you need to link the Debug version of EvalDll, and in release mode, you need the Release version of EvalDll. The latest nuget package 1.7 contains both debug and release version of C++ EvalDll.

@ucacaxm The "Win32" in VS refers to the platform using classical Windows API which has 32-bit and 64-bit variants, and unfortunately CNTK requires 64-bit. Regarding Dll binding, you can also link EvalDll.lib into your project, instead of LoadLibrary. The latest sample in 1.7 is now using library linking. 

Thanks!
