### ISSUE TITLE
Issue with ReconcileDynamicAxis in evaluating a sequence after training the model

### ISSUE THREAD

**Issue by raminia** [Microsoft/CNTK#462]
I followed an example in sequence classification in Tests\EndToEndTests\Text\SequenceClassification\Config\seqcla.cntk and modified it for my own data [n sequence of 26 inputs (features), 1 binary label (output)]

I trained the network usingthe configFile below. However, I faced an issue with evaluating the trained LSTM network against the train or test samples when running the _Write _block. It seems like the shape of the input and output does not match. The error is not very helpful and I'm not sure how to fix it. I have doubts about the structure of the network. Could this be because I defined the network improperly?

```
EXCEPTION occurred: l3p ReconcileDynamicAxis operation discovered that l3.act Sigmoid operation produced an MB layout that is incompatible with that of labels InputValue.

[CALL STACK]
    > Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::  ForwardProp
    - Microsoft::MSR::CNTK::ComputationNetwork::  ForwardProp
    - Microsoft::MSR::CNTK::ComputationNetwork::ForwardProp<std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>>
    - Microsoft::MSR::CNTK::SimpleEvaluator<float>::  Evaluate
    - DoEvalBase<float>
    - DoEval<float>
    - DoCommands<float>
    - wmainOldCNTKConfig
    - wmain1
    - wmain
    - __tmainCRTStartup
    - BaseThreadInitThunk
    - RtlUserThreadStart

~MPIWrapper
```

I have a very similar structure working in Tensorflow without issues but I need it to run under CNTK.
![image](https://cloud.githubusercontent.com/assets/2532252/15156229/e6b8c64c-169a-11e6-8d98-5fac588782b4.png)

Any ideas?

Config File:
```javascript

RootDir = "E:\cntk"
myDataDir = "E:\cntk"

ConfigDir = "$RootDir$"
DataDir = "$myDataDir$"
OutputDir = "$RootDir$/Output"
ModelDir = "$OutputDir$/Models"


# deviceId = -1 for CPU, >=0 for GPU devices, "auto" chooses the best GPU, or CPU if no usable GPU is available
deviceId = "auto"

command = Write #:train #: #:Write

precision = "float"
traceLevel = 1
modelPath = "$ModelDir$/cntkLSTM.dnn"
parallelTrain = true

Train=[
    action="train"
    run=BrainScriptNetworkBuilder
    
    BrainScriptNetworkBuilder=[
        
        Macros = [
            // define "last hidden state of sequence" in the LSTM (really for any sequence though)
            TakeRight (N, x) = BS.Sequences._Take(FutureValue, N, x)
            Last(x) = TakeRight(1, x)

        ]
        Layers = [
            EmbeddingLayer(input, vocabSize, embeddingDim, embeddingPath) = [
                embedding = Transpose(LearnableParameter(vocabSize, embeddingDim, learningRateMultiplier = 0.0, init = 'fromFile', initFromFilePath = embeddingPath))          
                lookup = GatherPacked(features, embedding)
            ].lookup
            # TODO: suggested change of parameter order: output dims first, inputDim=input.dim
            DenseLayer(input, inputSize, outputSize, activation) = [
               z = BFF(input, outputSize, inputSize).z
               act = activation(z)
            ].act
            # TODO: suggested change of parameter order: output dims first, inputDim=input.Dim optional, cellDim=outputDim optional
            LSTMLayer(input, inputSize, outputSize, cellSize) = [ 
               h = BS.RNNs.RecurrentLSTMP2 (outputSize, cellDim=cellSize, input, inputDim=inputSize).h
               #result = selector(lstm)
            ].h
        ]        
        
        // LSTM params
        lstmDim = 5
        cellDim = 5
        
        // model
        numLabels = 1        
        featureDim = 26     
                
        // set up features and labels
        t = DynamicAxis()
        features = Input(featureDim,dynamicAxis=t)   # Input has shape (1,t)
        labels   = Input(numLabels)          # Input has shape (numLabels,*) where all sequences in *=1
        
        // normalize features
        featNorm = MeanVarNorm(features)
        
        // use multiple layers of LSTM
        l1 = Layers.LSTMLayer(featNorm, featureDim, lstmDim, cellDim)
        l2 = Layers.LSTMLayer(l1, lstmDim, lstmDim, cellDim)
        l3 = Layers.DenseLayer(l2, lstmDim, numLabels, Sigmoid)
        out = Pass(l3, tag='output')   
        
        // Make sure the trainer understands that the time dimension of l3 is actually the same as that of labels. 
        # rearranging the data w.r.t. MBLayout or broadcasting across sequence items
        l3p = ReconcileDynamicAxis(l3, labels)
     
        // training criteria
        ce  = Logistic(labels, l3p, tag='criterion')  # Logistic(labels, Sigmoid(l3), tag='criterion') # CrossEntropyWithSoftmax(labels, l3p, tag='criterion')   // this is the training objective
        wer = SquareError (labels,l3p,tag='evaluation') # ErrorPrediction        (labels, l3p, tag='evaluation') # SquareError(labels, Softmax(l3), tag='evaluation') # ErrorPrediction        (labels, l3p, tag='evaluation')  // this also gets tracked
    
    ]
    
   SGD = [
    
        epochSize = 0
        #minibatchSize = 1000
        maxEpochs = 5
        momentumPerMB = 0:0.9
        learningRatesPerMB = 0.1   
        AutoAdjust=[
            reduceLearnRateIfImproveLessThan=0
            loadBestModel=true
            increaseLearnRateIfImproveMoreThan=1000000000
            learnRateDecreaseFactor=0.5
            learnRateIncreaseFactor=1.382
            autoAdjustLR=AdjustAfterEpoch
        ]  
	  
    ]
    
    reader = [
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/train_10s2_lb1.txt"            
        randomize = "none"
		 
        input = [            
            features=[
                alias = "F0"                
                dim = 26               
                format = "dense"
            ]
            labels=[
                alias = "L"                
                dim = 1           
                format = "dense"
            ]
        ]
   ]    
   outputPath = "$OutputDir$/output.txt"        # dump the output as text?
]

Write=[
    action="eval"
    run=BrainScriptNetworkBuilder
    modelFile = "$ModelDir$/cntkLSTM.dnn"    
    
    reader = [
			randomize = "none"
            readerType = "CNTKTextFormatReader"
            file = "$DataDir$/test_10s2_lb1.txt"            
            
            input = [            
                features=[
                    alias = "F0"                
                    dim = 26               
                    format = "dense"
                ]
                labels=[
                    alias = "L"                
                    dim = 1           
                    format = "dense"
                ]
            ]
            
   ]    
   outputPath = "$OutputDir$/output.txt"        # dump the output as text
]

```

The network validation passes as
```
Validating --> l2.h.lstmState._privateInnards.ht = ElementTimes (l2.h.lstmState._privateInnards.ot, l2.h.lstmState._privateInnards.ht.ElementTimesArgs[1]) : [10 x t1], [10 x t1] -> [10 x t1]
Validating --> l3.z.z.PlusArgs[0] = Times (l3.z.W, l2.h.lstmState._privateInnards.ht) : [1 x 10], [10 x t1] -> [1 x t1]
Validating --> l3.z.B = LearnableParameter() :  -> [1 x 1]
Validating --> l3.z.z = Plus (l3.z.z.PlusArgs[0], l3.z.B) : [1 x t1], [1 x 1] -> [1 x 1 x t1]
Validating --> l3.act = Sigmoid (l3.z.z) : [1 x 1 x t1] -> [1 x 1 x t1]
Validating --> l3p = ReconcileDynamicAxis (l3.act, labels) : [1 x 1 x t1], [1 x *] -> [1 x 1 x *]
Validating --> ce = Logistic (labels, l3p) : [1 x *], [1 x 1 x *] -> [1]
Validating --> out = Pass (l3p) : [1 x 1 x *] -> [1 x 1 x *]
Validating --> t = DynamicAxis() :  -> [1 x 1 x t1]
Validating --> wer = SquareError (labels, l3p) : [1 x *], [1 x 1 x *] -> [1]

Validating network. 76 nodes to process in pass 2.
```

**Comment by frankseide** [comment]
The error has to do with the two input streams (features, labels) having different lengths, or different time axes. For computing the criterion, features and labels must have the same time axis.

If I understand your setup correctly, they do. So in that case, please remove `t = DynamicAxis()` and `,dynamicAxis=t`. This way, both features and labels will share the same time axis (denoted as "*" in the Validation output). Please also remove the `ReconcileDynamicAxis()` call, and use l3 directly in the criterion.

Please let me know if that gets it to work. I suspect there is another problem in your setup, otherwise `ReconcileDynamicAxis()` would have been able to match; it seems that your input data file contains feature and label sequences of different length, so if it does not work, we'd need to look at that next.

Just for reference, in the original seqcla example, notice the .Last call which is used to select the last sample, which you removed because you don't need it.
```
l2 = Layers.LSTMLayer(l1, embedDim, lstmDim, cellDim, BS.Sequences.Last)
```

**Comment by raminia** [comment]
Thanks Frank,

That fixed the issue.  However, I'm not clear how the dynamic Axis and ReconcileDynamicAxis actually work. Does that match labels to features through sequence IDs? Does it matter when the label is presented along with the features.

**Comment by frankseide** [comment]
A minibatch is a collection of sequences, where each sequence can have a different length. The CE criterion computes a sample-by-sample loss value which is them summed up over the training corpus. This means that each feature sequence must have the same length as the corresponding label sequence. This sequence length is referred to as a dynamic tensor dimension. In the Validation output it is shown as "*". The corresponding features and labels are matched internally by being organized in memory in the same way (same packing).

However, there are scenarios where that is not the case, for example in sequence-to-sequence models or sequence classification. In those scenarios, users can explicitly declare dynamic time axes and give them names. The sample code you based your work off was such a case, where the input was a sequence, while the output was a single token. In this case, you must say something like
```
t = DynamicAxis()
```
and pass ```t``` as an optional argument ```dynamicAxis``` to the Input. This way, CNTK will know that these two representations are incompatible.

Now, there are occasions where you end up with two dynamic axes that are the same. In the sequence-classification example, the reader provides a 1-sample label, and inside the network the Last() function extracts a 1-sample output from the end of a sequence. CNTK can currently not know that these two are actually the same time axis. Hence you can use ```ReconcileDynamicAxis()``` to let it know. This will take a dynamic axis from one input (labels in this example) and the data from a second input (last hidden LSTM state), and combine them. Its output is now known to CNTK to have a compatible dynamic axis, so that you now can apply the CE criterion to it.

In this reconcile process, sequence ids are indeed used to match inputs, using a descriptor structure that describes all sequences in a minibatch and how they are packed (including padding; cf. ```Sequences.h```, ```MBLayout::m_sequences[]```). They are used by the fact that all entries in the m_sequences[] array are sorted by sequence id; and that two minibatch layouts with the same sequence lengths always have the same, hence column-by-column compatible, storage.

That's all.

**Comment by mikhail-barg** [comment]
@frankseide Thank you for the detailed explanation!
Could you please make a wiki page out of this message? Also currently `ReconcileDynamicAxis()` function is listed in the *Deprecated* section of [Full Function Reference](https://github.com/Microsoft/CNTK/wiki/BrainScript-Full-Function-Reference#deprecated),hassomething changed? What should be used instead of it?
