### ISSUE TITLE
write vs test command

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#475]
Hi, I'm trying to understand the purpose of the test command versus the write command.  If I have a write command in my config, is a test command necessary? Does it produce any additional output?  Conversely, if I omit a write command but include a test command will it save any output? 

The reason why I ask is that I'm building a deep network and want to evaluate performance at each layer. If I repeatedly {train, write using test data, add layer}, {train,...} is there any utility in adding a test command in each iteration?

**Comment by amitaga** [comment]
Hi,

The test command evaluates the network on the specified test data and logs the values of the specified eval nodes  - https://github.com/Microsoft/CNTK/wiki/Train%2C-Test%2C-Eval.

The write command writes the value of specified output nodes to a file. https://github.com/Microsoft/CNTK/wiki/Top-level-commands

They can be used together (see Examples\Other\Simple2d). In your scenario, test seems more appropriate if all you want is to evaluate the performance of the trained network at each stage.

**Comment by simra** [comment]
Thanks @amitaga, where are the test results logged?  The Test command doesn't seem to have any parameters related to output.

**Comment by amitaga** [comment]
To stderr.

**Comment by ant0nsc** [comment]
I would also love to have an improved `test` command. A couple of things that spring to mind:

- There should be a way of logging the test error outside `stderr`. If I only get it in `stderr`, and need to use test results in a pipeline, I'm stuck with having to parse the log format, which clearly could change any moment. An extra output file that only stores the eval critierion would do.
- Many of my tasks involve an in-depth analysis of prediction results once the test error seems promising. Currently, I need to first run `test`, then `write` on the same dataset - even though both do pretty much the same thing. Can `test` have an option to write node values while doing the forward propagation?

**Comment by frankseide** [comment]
@simra, BTW you can run a single `test` command to evaluate error metrics of multiple outputs.

**Comment by frankseide** [comment]
@ant0nsc, the two pieces of code are not trivial to merge, although they share a lot, of course. It may be easier to leverage the V2 Python APIs that we currently work on feverishly.

A workaround could be to first "write" out your inference result, and then "eval" it by reading it back in and scoring it with a dummy network. Create a new network inside the "eval" action that simply scores its input against the ground truth. Not ideal, but if you write out the inference result anyway, not too horrible or inefficient either, since you can run both actions with a single CNTK invocation (something like `command=writeToFile:evalFromFile`).

**Comment by mahilleb-msft** [comment]
Closing as anwered. Please re-open or file a new issue if necessary.
