### ISSUE TITLE
CNTKTextFormatReader Question

### ISSUE THREAD

**Issue by tzwjwcg** [Microsoft/CNTK#502]
Given the following Text Reader data:

100|F 1 2 3 4 |L 5
100|F 1 2 3 4 |L 5
100|F 1 2 3 4 |L 5
100|F 1 2 3 4 |L 5
101|F 1 2 3 4 |L 5
101|F 1 2 3 4 |L 5
102|F 1 2 3 4 |L 5
102|F 1 2 3 4 |L 5
...

And the following configuration - 
Randomize = ‘false’
SkipSequenceIDs = ‘false’
minibatchSize = 4

I have questions about the order in which the data will be presented for training an RNN.

1. All lines are presented in order as they appear.  BPTT occurs every fourth line.
2. All lines are presented in order as they appear.  BPTT occurs every fourth sequence number.
3. Something else?

**Comment by raaaar** [comment]
The input will be consumed in the original order. Since minibatch is limited to 4 samples, the reader will take as many lines from the input (which each line corresponding to an individual sample) as needed to satisfy this requirement. However, since sequences are consumed as atomic units, all lines that belong to a single sequence read in at once. In the snippet above, the first 4 lines (sequence number 100) will constitute the first minibatch, the following 4 lines (sequence numbers 101 and 102) -- the second, assuming that the length of the 102nd sequence in samples is 2. If that assumption is not correct (say, the ellipsis hides a few more lines that all belong to 102), all samples from 101 would got into the second minibatch and from 102 -- into the third.

**Comment by tzwjwcg** [comment]
Thank you.
