### ISSUE TITLE
Failed to lock GPU 0 for exclusive use

### ISSUE THREAD

**Issue by sofeikov** [Microsoft/CNTK#513]
Hi guys,

I've recently come across the problem stated in the issue title. For some reason cntk is not able to lock the only GPU I have for an exclusive use(whatever it means). Therefore it defaults to CPU calculations.

I have a feeling that this might only happen if you stop network training by Ctrl-C then probably some recourses are not being released properly. Why I think this way is because I did a lot of trainings in the beginning when I was playing around with toy examples and never seen this message before. During those experiments I always waited till the training is done. Now I interrupt the training process quite often and it might be the reason for the problem - not sure though.

The only way I found to resolve this is to reboot the machine. Is it a known problem? Are there any quick workarounds except machine restart?

Thanks

**Comment by wolfma61** [comment]
There have been many changes in CNTK since then. You should try using the latest bits, we found that this issue has mostly be resolved (although we have seen reports of locked GPU, especially after terminated training runs)
If you still encounter this issue, please report/reopen - ideally with a solid repro-scenario, but we know this is hard to come by ...
