### ISSUE TITLE
Request: Support of ResNet and GoogLeNet on CPU.

### ISSUE THREAD

**Issue by ldmtwo** [Microsoft/CNTK#530]
The title says it all. I have CPU code to greatly improve forward and backward convolution performance. Unfortunately, out of the top 4 on my list, I cannot run CNTK with CPU on the above two. AlexNet and VGG are working well enough. I figured it's better if I officially ask for these. 

 Also, can someone point me to the implementation specific algorithm used for these 3 functions? `ConvolutionForward, ConvolutionBackwardData, and ConvolutionBackwardKernel.` The part I struggle with is `mpRowRun`and `runs`. Where is this data set/created? What is the pattern of the data? I might be able to improve the code more if it was reduced to a naive/simple algorithm. I can either use BLAS, MKL-DNN (https://software.intel.com/en-us/articles/deep-neural-network-technical-preview-for-intel-math-kernel-library-intel-mkl) or code-gen if I know the logic. Thanks.

```
template <class ElemType>
void CPUMatrix<ElemType>::ConvolutionForward(const CPUMatrix<ElemType>& kernel, const CPUMatrix<int>& mpRowCol, const CPUMatrix<int>& mpRowIwht,
                                             const CPUMatrix<int>& mpRowRun, const CPUMatrix<int>& runs, CPUMatrix<ElemType>& output) const
{
#pragma omp parallel for
    for (int64_t sample = 0; sample < (int64_t)output.GetNumCols(); sample++)  {
        for (size_t row = 0; row < output.GetNumRows(); row++)   {
            int colBase = mpRowCol(row, 0);
            int ivBase = mpRowIwht(row, 0);
            assert(0 <= colBase && colBase < GetNumRows());
            ElemType sum = 0;
            int i0 = mpRowRun(row, 0);
            int skip = runs(i0++, 0);
            int size = runs(i0++, 0);
            int imask = i0 + size;
            for (int i = 0; i < size; i++)  {
                if (runs(imask + i, 0) == 0)                    continue;
                int dcol = runs(i0 + i, 0);
                assert(0 <= colBase + dcol && colBase + dcol < GetNumRows());
                sum += kernel.Data()[ivBase + skip + i] * (*this)(colBase + dcol, sample);
            }
            output(row, sample) = sum;
        }
    }
}
```

**Comment by Alexey-Kamenev** [comment]
There is already GEMM based implementation, look at Gemm engine. What you are looking at is reference engine which is simple (by design) and slow (as a consequence of being simple). Do not try to optimize reference engine. Support for MKL (that includes convolutions) is coming very soon.






On Wed, May 25, 2016 at 6:11 PM -0700, "LD" <notifications@github.com> wrote:












The title says it all. I have CPU code to greatly improve forward and backward convolution performance. Unfortunately, out of the top 4 on my list, I cannot run CNTK with CPU on the above two. AlexNet and VGG are working well enough. I figured it's better if I officially ask for these. 



Also, can someone point me to the implementation specific algorithm used for these 3 functions? ConvolutionForward, ConvolutionBackwardData, and ConvolutionBackwardKernel. The part I struggle with is mpRowRunand runs. Where is this data set/created? What is the pattern of the data? I might be able to improve the code more if it was reduced to a naive/simple algorithm. I can either use BLAS, MKL-DNN (https://software.intel.com/en-us/articles/deep-neural-network-technical-preview-for-intel-math-kernel-library-intel-mkl) or code-gen if I know the logic. Thanks.

template <class ElemType>
void CPUMatrix<ElemType>::ConvolutionForward(const CPUMatrix<ElemType>& kernel, const CPUMatrix<int>& mpRowCol, const CPUMatrix<int>& mpRowIwht,
                                             const CPUMatrix<int>& mpRowRun, const CPUMatrix<int>& runs, CPUMatrix<ElemType>& output) const
{
#pragma omp parallel for
    for (int64_t sample = 0; sample < (int64_t)output.GetNumCols(); sample++)  {
        for (size_t row = 0; row < output.GetNumRows(); row++)   {
            int colBase = mpRowCol(row, 0);
            int ivBase = mpRowIwht(row, 0);
            assert(0 <= colBase && colBase < GetNumRows());
            ElemType sum = 0;
            int i0 = mpRowRun(row, 0);
            int skip = runs(i0++, 0);
            int size = runs(i0++, 0);
            int imask = i0 + size;
            for (int i = 0; i < size; i++)  {
                if (runs(imask + i, 0) == 0)                    continue;
                int dcol = runs(i0 + i, 0);
                assert(0 <= colBase + dcol && colBase + dcol < GetNumRows());
                sum += kernel.Data()[ivBase + skip + i] * (*this)(colBase + dcol, sample);
            }
            output(row, sample) = sum;
        }
    }
}

**Comment by ldmtwo** [comment]
Can you point me to the Gemm based code? I thought it would be in CPUmatrix.cpp and the function above is what I saw running when I analyzed the performance. Could it be the image layout or something else in the .cntk file? Thanks.

**Comment by Alexey-Kamenev** [comment]
Please take a look at `GemmConvolutionEngine` in [ConvolutionEngine.cpp](https://github.com/Microsoft/CNTK/blob/master/Source/Math/ConvolutionEngine.cpp)

**Comment by mahilleb-msft** [comment]
I think the missing part would be Batch Normalization for training on CPU - @cha-zhang is this in the plans?

**Comment by ldmtwo** [comment]
I believe it was batch normalization and concatenation.

**Comment by KeDengMS** [comment]
[Fixed](https://github.com/Microsoft/CNTK/commit/1d3d1e8a2770b65a809f6bf7e6cde49047ffc0c6)
