### ISSUE TITLE
CNTK summarized experience 

### ISSUE THREAD

**Issue by leonardoaraujosantos** [Microsoft/CNTK#542]
Hi there,
During our test of cntk for 3 weeks we encountered numerous issues with the library, and we'd really appreciate it if you can respond to this list of questions and observations we have compiled:
1. Will the reader support faster schemas to access big datasets (e.g. LMDB)?
2. If we do parallel training the usage of the GPUs seems to be sub-optimal (They remain at 0% usage for long periods of time, probably waiting for disk I/O)
3. We encountered several crashes when using big datasets (2 million images per class, with 4 classes)
4. After a period of time the time to process the epochs start to grow, if we use a "iotop" we detect a lot of threads/process waiting to have disk read quota available, and the number of starving process grow over time

The reason I'm asking these questions is because we have reached a point where we must decide which library to use. CNTK is a really good candidate because it supports multi-gpu-machine calculations out of the box. As we all know, any DL experiment takes a lot of time. From this point of view it is very frustrating to face unpredictable issues and crashes during the experiments. We've got pretty modern hardware(4 Titan X, Xeon 36 cores, 1TB of RAM) and we still run into crashes. To be honest, I do not understand how other people are able to complete training process on more or less big data sets.

Thanks a lot for looking into this. We are really keen to use CNTK, but unfortunately it's not practical with the issues above. Hopefully you are already aware of them and plan to resolve them, in which case we should have no problems. Please just let us know.

**Comment by frankseide** [comment]
Thanks for your detailed feedback. CNTK is in fact used internally at Microsoft to train large models, such as a 2.2-billion sample DSSM model and 4+-billion sample speech models. This is done with stock CNTK as published, but on somewhat optimized hardware. It would be a great help for us to get to the ground of the issues you are observing.

To get started, for items 2., 3., and 4., would you mind posting the relevant log information? Specific questions:

2. What parallelization method are you using? You can use 1-bit SGD and BlockMomentum. If by any chance you have configured DataParallelSGD without 1-bit quantization, it will not be efficient and could explain what you observe.

3. Could you give more information on the nature of the crashes? Ideally, could you paste the last 20 lines of the log?

4. Could you post that iotop output? Could you also check whether the machine seems to have gotten into paging/if the process has seen steady increase of memory usage?

Thanks!

**Comment by Alexey-Kamenev** [comment]
Hi Leonardo,
Thank you for the feedback. About item 1: ImageReader currently supports only one container format, which is simple ZIP files. We recommend using STORE compression method when packing images into ZIP as png/jpeg files do not require any additional compression anyway.
According to our experiments, the biggest amount of time (at least when training nets on ImageNet datasets) is spent in decompressing JPEGs, not in actual disk IO. Some of our internal teams were able to solve the problem by pre-processing images (scaling/cropping) to a smaller size. As an example, training ResNet-18 on pre-processed ILSVRC-2012 dataset on 32 GPUs takes about 18 hours with little loss in accuracy (due to pre-processing) which is tolerable for most of the use cases (except competitions). See results and examples of ResNets [here](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Miscellaneous/ImageNet/ResNet).
As Frank said, it would be great to have a bit more information, like call stacks and details of the experiments.
Thanks.

**Comment by leonardoaraujosantos** [comment]
Hi, sure, the first crash that we detected was if some training image could not be read during training, I posted it's logs on this issue:
https://github.com/Microsoft/CNTK/issues/533

I'm trying now to train the same dataset on a ram disk (tmpfs), but meanwhile I will restart to do the training on disk get the iotop log

Again many thanks for the support

**Comment by FreedMana** [comment]
I have got some crashes too with bigger dataset. Sometimes i got "EXCEPTION occurred: requirerandomizedchunk: requested utterance outside in-memory chunk range" , or  it just corrupted  during paging in/out  without any error information.
Continuous attention to this issue. Thanks everyone.

**Comment by housebaby** [comment]
I also have a problem which I doubt is due to the large amount of data.
I was training acoustic model with large dataset  on 2 GPUs ( feature set 0: 809897066 frames in 3238440 out of 3255057 utterances) .
part of my config file is as follows:
parallelTrain=true
parallelTrain = [
                parallelizationMethod = "DataParallelSGD"
                parallelizationStartEpoch = 2
                distributedMBReading = true
               # Additional optional parameters are: useZeroThresholdFor1BitQuantization
                dataParallelSGD = [
                            gradientBits = 1
                ]
       ]

After training for some time, it stopped with following message:
-------------------------------------------------------------
Redirecting stderr to file exp_cntk//log/train_cntk_TrainDNN.logrank0
Redirecting stderr to file exp_cntk//log/train_cntk_TrainDNN.logrank1
--------------------------------------------------------------------------
WARNING: A process refused to die despite all the efforts!
This process may still be running and/or consuming resources.

Host: 10
PID:  62128

--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 62127 on node 10 exited on signal 9 (Killed).
--------------------------------------------------------------------------
./train_cntk2.sh successfuly finished.
------------------------------------------------------------------------------
The log file "exp_cntk//log/train_cntk_TrainDNN.logrank0 "ends with following message: 
feature set 0: requirerandomizedchunk: paging in randomized chunk 7388 (frame range [667055478..667145567]), 7389 resident in RAM
requiredata: 455 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 7389 (frame range [667145568..667236829]), 7390 resident in RAM
requiredata: 92 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 7390 (frame range [667236830..667327341]), 7391 resident in RAM

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
