### ISSUE TITLE
What is "%d out of %d nodes do not share the minibatch layout with the input data.\n"?

### ISSUE THREAD

**Issue by quicktrick** [Microsoft/CNTK#546]
Could anybody explain, please?  Do I have to do anything with that message in the output log?

**Comment by esun-w** [comment]
I have the same log as you ...but I do not konw why ...

**Comment by Codie-Petersen** [comment]
I usually get something along the lines of this:

 ```
4 out of 9 nodes do not share the minibatch layout with the input data.

Post-processing network complete.

Created model with 9 nodes on CPU.
```

So I would assume its not counting the nodes properly and getting a null reference instead, not entirely sure though. But since %d is for placing decimal variables in strings, I would assume that means that the decimal variable is not being set for whatever reason.

**Comment by Mikoor** [comment]
Hi, the same question here. Does it affect the minibatch performance? Or is there any way to configure the layers/input dimension so the warming disappear?

Thanks,
Miro

**Comment by mahilleb-msft** [comment]
This message isn't produced anymore, cf. https://github.com/Microsoft/CNTK/blob/master/Source/ComputationNetworkLib/ComputationNetworkEvaluation.cpp#L711.
Please updated to newer bits.
Thanks, Mark
