### ISSUE TITLE
CNTK.exe has stopped working

### ISSUE THREAD

**Issue by 2wins** [Microsoft/CNTK#554]
I was trying to apply the ResNet for CIFAR to my work when I encountered a problem which yielded the message "CNTK.exe has stopped working".
I'm sure that I suitably adjusted some parameters and paths.
The attached log file does not tell me any problems and thus I couldn't try anything.

[ResNet_Train_Test.log.txt](https://github.com/Microsoft/CNTK/files/300743/ResNet_Train_Test.log.txt)

**Comment by eldakms** [comment]
This was caused by OpenCV-3.0 on windows - it uses static variables with proper guards, that can lead to race conditions and crashes during initialization.

This problem should not be in the latest (starting from 1.5 if i'm not mistaken). We switched to opencv-3.1

If you bump into anything similar on the latest version, please feel free to reopen. 
Thank you!

**Comment by eldakms** [comment]
Sorry, starting from 1.6
