### ISSUE TITLE
Convolution on non-image input

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#564]
I'm trying to apply non-image input to convolution operation.

Basically, input is 80 dim vector and I feeded it into convolution layer:
 #ConvReLULayer(inp, outMap, inWCount, kW, kH, hStride, vStride, wScale, bValue)
 conv1 = ConvReLULayer(featNorm, 64, 5, 1, 5, 1, 1, conv1WScale, conv1BValue);

For this case, I got the following error messages:
.
.
.
Validating network. 203 nodes to process in pass 1.

Validating --> conv1.c = Convolution (conv1.W, featNorm.xNorm) : [64 x 5], [80 x *] -> [] FAILED

EXCEPTION occurred: Convolution operation currently only supports 1D or 2D convolution on 3D tensors.

[CALL STACK]
.
.
.

So, it looks like featNorm should be 80x1 instead of 80x*. Is there any function to change vector to matrix? Or can I use reshape function? 

I will be appreciating any comment on this.

**Comment by frankseide** [comment]
I think the problem are your kernel dimensions. The height (#rows) of a vector or matrix is the first dimension, but there is this confusing convention that the image height is the second dimension, not the first. That is because images are commonly stored row by row, whereas CNTK uses column-major representation.

To convolve an 80-dim vector with a 5-element filter, both should be column vectors, so you'd need `kW=5` instead of `kH`. With the recent update of our network-description language, once you switch over to the new BrainScriptNetworkBuilder, you would specify the kernel size as a vector (1:5), and then it would be more clear that (1:5) does not match (80).

So would you mind trying to swap your two tensor dimensions?

In case that does not do the trick, let me loop in my colleague @Alexey-Kamenev, who owns convolution, and another thing you can try is to explicitly declare your input as a rank-3 tensor:

    feat = ImageInput (80, 1, 1, imageLayout="cudnn")

BTW in [80 x *], the * stands for the batch dimension; so that is OK.

**Comment by funguy74** [comment]
First, I swapped width and height but the same error still happened. Second, I changed feat into ImageInput as in the code above and then finally convolution error disappeared. Currently, there's no issue on running. Thank you very much for your answers!

So, it looks like input to convolution function should be a rank-3 tensor. Regarding this, I have one more question on this. What is the difference between "ImageInput" and "Input" formatters? ImageInput is only changing vector into multi-dimensional vector? Or is ther any other meaning?

**Comment by frankseide** [comment]
The only difference between `ImageInput()` and `Input()` is how it interprets the dimension parameters. `Input()` expects the dimensions to be an array. `ImageInput()` has a notion of width, height, and channels, and maps them to a 3-dim array of dimensions. It also has a notion of two different data layouts we support (`cudnn` and `legacy`), which determine which image dimension gets mapped into which index.

        bool isImage = configp->Get(L"isImage");
        if (!isImage)
            Init(configp->Get(L"shape"), isSparse, axisName);
        else
            Init(ImageDimensions::AsTensorShape(configp->Get(L"imageWidth"), configp->Get(L"imageHeight"), configp->Get(L"imageChannels"), ImageLayoutKindFrom(configp->Get(L"imageLayout"))), isSparse, axisName);

BTW I don't think convolution is conceptually limited to rank-3 tensors. The old `Convolution()` operation was replaced by a backwards-compatible 2D version, and a more generic N-D version. You may be using the old one. I am reviewing Tutorial II at the moment (which covers convolution) and will get up to speed on that,. and clean/clear this up.

**Comment by funguy74** [comment]
I might need pull down latest one (last pull is on 4/8, so somewhat outdated). I really appreciate your kind explanation. It really helps a lot on my work. Thanks!
