### ISSUE TITLE
cosdistance of two matrices returns a scalar

### ISSUE THREAD

**Issue by guoli-ye** [Microsoft/CNTK#568]
I have 2 matrices, 128X1240. Based on CNTK book, I expect the output after CosDistance will be a vector of [1X1240]: each column pair of the two input matrices, do a cosdistance. But it just returns a scalar. Is it by design? If so, how could I achieve what I want efficiently?

The snippet log is below:

Validating --> net.convMasked[1].mask.input.z = CosDistance (net.convMasked[1].tinput, net.convMasked[1].tms) : [128 x 1240 x *], [128 x 1240 x *] -> [1 x *]

**Comment by dongyu888** [comment]
cosDistance is per sample based. If you want to get 1240 values each sample should be 128 dims and have 1240 samples. You may use reshape operation to convert 1240 into the sample number dim if this feature already works.

**Comment by guoli-ye** [comment]
Thank you, Dong. By searching on the code, I didn't find how to do it: "You may use reshape operation to convert 1240 into the sample number dim if this feature already works.".  Maybe the feature is not there yet?

**Comment by frankseide** [comment]
The built-in CosDistance() function has not yet been updated to support tensors. Once it does, it will take an axis parameter to do what you expect. Also, it will then support broadcasting so that you could compute the cosince distance between your 1240 columns with a single column. The alternative that Dong mentioned, Reshape() into time, is possible, but I think there is a simpler solution:

You can just write out the axis-1 CosDistance() as a formula in your network definition. For that, I recommend to switch to using BrainScript if you have not yet, which will makes it much easier. The key operators are

    x .* y

which performs an element-wise product, and

    ReduceSum (x, axis=n)

which sums up all elements along a specific axis (in your case, `axis=1`). This allows to write dot products along specified axes.

With this, the cos distance can be written as (warning: untested pre-coffee browser code, may have errors):

	Dot1 (x, y) = ReduceSum (x .* y, axis=1)   // [M x N x ...] --> [1 x N x ...]
	Norm1 (x) = Sqrt (Dot1 (x, x))
	CosDistance1 (x, y) = Dot1 (x, y) .* Reciprocal (Norm1 (x) .* Norm1 (y))

where the "1" at the end of the function names is meant to indicate to do this along axis 1. `Sqrt()` and `Reciprocal()` were added recently, so you will need latest master or the 1.5 binary we released few days ago.

This will generate about 10 nodes in your network, but I expect it to be only slightly less efficient than the built-in CosDistance() function in that the three element-wise products are written out to GPU RAM in full dimension. All operations after ReduceSum() are relatively cheap as they operate on 128 x smaller dimension.

BTW if your tensor rank is 1 (not in your case), `ReduceSum (x .* y)` can be written as `TransposeTimes (x, y)`, which will save that extra memory, and likely be as efficient as the built-in.
