### ISSUE TITLE
EXCEPTION occurred: Scalar expected, 'inWCount1' must be a constant or variable that resolves to a constant

### ISSUE THREAD

**Issue by MouHMY** [Microsoft/CNTK#578]
Dear CNTK-team,

In order to avoid filling a constant input weight count value, I tried to use the following snippet in my ndl file : 
...
DNN = [   
    # conv1
    kW1 = 5
    kH1 = 5
    inC1 = 1
    **_inWCount1 = Times(Times(kW1, kH1), inC1)_**
    cMap1 = 48
    hStride1 = 1
    vStride1 = 1
    # weight[cMap1, kW1 * kH1 * inputChannels]
    # ConvBNReLULayer is defined in Macros.ndl
    conv1 = ConvBNReLULayer(featScaled, cMap1, **_inWCount1_**, kW1, kH1, hStride1, vStride1, convWScale, convBValue, scValue, bnTimeConst)
...

But CNTK complained the bold italic line as follows:
"EXCEPTION occurred: Scalar expected, 'inWCount1' must be a constant or variable that resolves to a constant"

Is there anything wrong in my usage?
Thanks very much.

**Comment by frankseide** [comment]
This cannot be done with the `NDLNetworkBuilder`, but it can with the new `BrainScriptNetworkBuilder`. If you update your network to use BrainScript instead of NDL ([how to](https://github.com/Microsoft/CNTK/wiki/BrainScript-Network-Builder#Updating-from-NDLNetworkBuilder-to-BrainScriptNetworkBuilder), "Updating from NDLNetworkBuilder to BrainScriptNetworkBuilder"), you will then be able to write

    inWCount1 = kW1 * kH1 * inC1

**Comment by MouHMY** [comment]
I see. Thanks very much.
