### ISSUE TITLE
Scoring on Pretrained Resnet-18 model on ilsvrc'12 validation data

### ISSUE THREAD

**Issue by championoaks** [Microsoft/CNTK#593]
I am very new to CNTK and DL in general. Is there a sample config file I can use with the pretrained models available here https://www.cntk.ai/resnet/ResNet_18.model? Are these models trained for image classification?
Is it possible to use evaldll on this model and classify images?

**Comment by gaizkan** [comment]
The short answer is: yes, you can use evaldll to evaluate images with the model. The long answer is that in order to do this, you need to first transform the images accordingly to how CNTK transformed the images while training.
I will be putting together a sample on how to evaluate images using the .Net evaluation library relatively soon.
I will keep this issue open until then.
Thanks,
Gaizka

**Comment by gaizkan** [comment]
A sample for evaluating an image classification model has been added to the Examples in CSEvalClient using ResNet_18.
Thanks,
Gaizka
