### ISSUE TITLE
RowStack does not work with BrainScript

### ISSUE THREAD

**Issue by nguyenquyhy** [Microsoft/CNTK#594]
I am trying to use RowStack(Input1, Input2, Input3, Input4), but keep getting error: function expects 1 positional parameters, 4 were provided. Debugging shows that RowStack expect 1 "inputs" parameter, and I am not sure how to do that in the newly release CNTK.

**Comment by dongyu888** [comment]
use : as the separator.


Thanks,
Dong Yu (俞栋)Sent from my smart phone. Please forgive my typos.
<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Nguyễn Quý Hy <notifications@github.com> </div><div>Date: 6/15/16  04:22  (GMT-08:00) </div><div>To: Microsoft/CNTK <CNTK@noreply.github.com> </div><div>Subject: [Microsoft/CNTK] RowStack does not work with BrainScript (#594) </div><div>
</div>
I am trying to use RowStack(Input1, Input2, Input3, Input4), but keep getting error: function expects 1 positional parameters, 4 were provided. Debugging shows that RowStack expect 1 "inputs" parameter, and I am not sure how to do that in the newly release CNTK.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Microsoft/CNTK/issues/594

**Comment by frankseide** [comment]
Thanks for pointing this out. I updated the porting guide at [[https://github.com/Microsoft/CNTK/wiki/BrainScript-Network-Builder]].

**Comment by nguyenquyhy** [comment]
Thanks for the new information.
