### ISSUE TITLE
CNTK for Time series prediction

### ISSUE THREAD

**Issue by gowthamnatarajan** [Microsoft/CNTK#595]
Can we use LSTM for time series event prediction in CNTK? Can we include other static features other than the time series variable itself.

**Comment by frankseide** [comment]
CNTK supports LSTMs. With static features, you mean sequence-dependent features that are constant throughout that specific sequence, but vary across sequences? Yes, the [CNTKTextFormatReader](https://github.com/Microsoft/CNTK/wiki/CNTKTextFormat-Reader) supports this. You would have to express your data in its format.

**Comment by gowthamnatarajan** [comment]
Yes, like there is a time series variable but along with it is the month in which it occurred.

**Comment by frankseide** [comment]
Your task is a little like sequence classification, where we have a variable-length input and a single-token label. Since labels are just features, you can use the same mechanism to feed two feature streams, one variable-length and one single-token (plus one more variable-length stream for your target values). We have a test for this feature. You can find the training data file, which illustrates how to do it, [here](https://github.com/Microsoft/CNTK/blob/master/Tests/EndToEndTests/Text/SequenceClassification/Data/Train.txt).

Your network also needs a special provision. You must expand the single-token value (month) into a sequence of the same length as your variable-length input (and then feed augment it to every input feature; I assume that is your model). For that, you need the `Gather()` operation. This is used in the [sequence-to-sequence sample](https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceToSequence/CMUDict/Config/G2P.cntk). You would write something like this:

    monthBroadcast = BS.Sequences.BroadcastSequenceAs (inputSequence, month)

where `month` is your single-token input, and `inputSequence` is the variable-length feature sequence, which is passed in here to provide the length to which `month` should be duplicated.

Please keep asking if you run into issues with this.

**Comment by gowthamnatarajan** [comment]
Any example of a Echo state network with CNTK?

**Comment by gowthamnatarajan** [comment]
Any example of a Echo state network with CNTK?

**Comment by wolfma61** [comment]
We have added many additional samples, tutorials and notebooks. We are looking for contributions for more samples, tutorials!
