### ISSUE TITLE
RNN + CONV or RNN + DNN train

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#596]
When RNN (LSTM) is serially connected to convolutional layers or fully-connected layers, is there any issue to train them simutaneously in CNTK? For example, RNN is trained through BPTT and others are trained by standard BP. I'm wondering if CNTK structure (computational network) does not have any issue on this configuration.

**Comment by frankseide** [comment]
This should work out of the box. CNTK knows how to detect and handle sections of the network that need unrolling/BPTT.

If you are interested on how this works, please check out the first presentation on [this page](https://github.com/Microsoft/CNTK/wiki/Presentations), and skip to the deep-dive section of the talk (slide 35ff in the PPT).

**Comment by funguy74** [comment]
Thanks for the reference. My understanding of CNTK training is that for hybrid network like LSTM+DLL, CNTK automatically detects correct computational connection and therfore, LSTM do  BPTT by unrolling networks with minibatch size. By the way, DNN will do  normal BP with the same size of minibatch. Am I right?

Besides, I have an additional question from slides.

It looks like minibatch size is a kind of reference boundaries for past/futurevalue reset for bidirectional RNN (Is it right?). How about prediction time (not training)? How can CNTK reset future/pastvalue in the RNN for prediction or decoding?

**Comment by frankseide** [comment]
Yes, your understanding is correct.

CNTK analyzes which parts of the graph have "horizontal" (time) dependencies. Those are unrolled. In all others, all samples are independent and can thus be computed fully in parallel. For example, in an RNN like

    h = b + W * v + H * PastValue (h)

`b + W * v` will be computed as one big CUDA launch (which will also compute a few vectors in gaps garbage-in-garbage-out), whereas `H * PastValue(h)` is computed time step by time step (but still utilizing parallelism across multiple sequences in the same minibatch). It also computes the gradient into `H` in a big CUDA launch.

For sequences, the minibatch size is the maximum number of individual samples (total steps across multiple parallel sequences). The reader will pack one sequence after another into the minibatch until this limit is reached. So the actual minibatch size, measured in samples, will be a little smaller than the specified value.

The packing may concatenate multiple short sequences. When doing so, it will keep a record at where the splicing points are. There are then special conditions in the code to make sure that RNN state gets reset at these splicing points, and that no gradient crosses a splicing point or gets pulled in from a gap region. Effectively it means that any step that has a splicing point is not executed as a joint launch across all sequences, but sequence by sequence, where it does something different for those sequences that have the splice point there.

If you are interested, this special logic is implemented in the `class DelayedValueNodeBase` in [RecurrentNodes.h](https://github.com/Microsoft/CNTK/blob/master/Source/ComputationNetworkLib/RecurrentNodes.h), in `ForwardProp()` and `BackpropTo()`. The code is a bit more complicated than may appear necessary since it also has special conditions for truncated BPTT.

**Comment by funguy74** [comment]
Thanks for the great explanation. I understand that RNN state reset is not based on minibatch size but based on sequence boundaries (splicing points). By the same rule, for prediction(or decoding) time, state reset also would be based on input sequence boundaries, which makes clear to me.

For a sequence longer than minibatch size, I guess it will be truncated by minibatch max size and then state will be reset according to minibatch boundaries, right?

**Comment by frankseide** [comment]
Naw, there is a special rule. If a sequence is longer, we will still use it, forming a minibatch on its own. Some future version will have an option to alternatively skip them. But generally, your MB size should be >> sequence length (otherwise you won't get benefits from parallelization).

**Comment by funguy74** [comment]
Thanks for the answer. For more detail, I'll look into code you referenced. Thanks again.

**Comment by frankseide** [comment]
Cool. If you have more questions, please let us know. If you don't mind, would you be OK with me closing this Issue?

**Comment by funguy74** [comment]
Of course, I'll close this issue. Thanks a lot!
