### ISSUE TITLE
How can I get the weights of each layer and visualise the weights?

### ISSUE THREAD

**Issue by MaggieWang1011** [Microsoft/CNTK#624]
I have a convolutional neural network which contains two convolutional layer. I want to get the weights of each map in each layer and visualise the weights. How can I do it? 
I just started to learn deep neural network and I want to analyse the network to understand how it works. 
Thank you very much.

**Comment by dongyu888** [comment]
Use dumpnode command. Check https://github.com/Microsoft/CNTK/wiki/Top-level-commands

 

Thanks,

 

Dong Yu (俞栋)

**Comment by ant0nsc** [comment]
Piling on to that. I'm taking the standard AlexNet example, and would like to analyze why the networks goes berserk for some inputs. Multiple issues here:

 - Issue 1: There is currently no way of dumping convolution kernels, this is already reported as #302 

 - Issue 2: I cannot specify multiple nodes in one go. For the "Write" command, I can do "h1_d:h2_d", but when I use "h1.W:h2:W" it tells me that there is no such node. That is clearly inconsistent.

- Issue 3: "Dump" refuses to write anything multidimensional. Needless to say that this limits its usefulness dramatically.

 - Issue 4: The filename that is chosen automatically is not consistent with the filename chosen by the "write" command. Write uses Prefix + nodename, Dump uses Prefix + nodename + ".txt. Actually I'd prefer "write" to also use a ".txt" suffix because extensions like "h2.d" do confuse some programs.

**Comment by wolfma61** [comment]
This issue has been dormant for a long while, please check out the latest CNTK release. If you still run into problems, please open a new issue.
