### ISSUE TITLE
Concatenate output of two layers to make one input

### ISSUE THREAD

**Issue by RayFireh** [Microsoft/CNTK#651]
Any example of concatenation of two outputs into one input?

Example network:
h1 = DNNReLULayer(featDim, hiddenDim, features, 1, 1)
o1 = DNNLayer(hiddenDim, labelDim, h1, 1)
h2 = DNNReLULayer(featDim, hiddenDim, features, 1, 1)
o2 = DNNLayer(hiddenDim, labelDim, h2, 1)
#concatenate o1 and o2 into o3?
o = DNNLayer(2, hiddenDim, o3, 1, 1)

And let say o1 and o2 are outputs of two layers and now how to make o3 by concatenating o1 and o2, so o3 can be supplied to other layer?

**Comment by zpbappi** [comment]
I am not sure how do you want to concatenate. For `o1` (_a_ x _b_) and `o2` (_a_ x _b_), if you want to get `o3` (_2a_, _b_), try:
```
o3 = Splice ((o1:o2), axis=1) #Or, simply RowStack((o1:o2))
```

However, if you want to get `o3` (_a_, _2b_), try:
```
o3 = Splice ((o1:o2), axis=2)
```

**Comment by RayFireh** [comment]
RowStack was the answer. Thank You!

Splice probably works with brain script only (as I was getting constant errors in ndl)

**Comment by zpbappi** [comment]
Oh yes. I forgot to mention that I was using BrainScript and latest codebase from the master branch. I am not quite sure about NDL support. It is currently marked as deprecated though.

**Comment by frankseide** [comment]
Yes. We added a new name for the case of tensors, since stacking and rows imply height, which only makes sense for a vector or first axis of a matrix.

In NDL, you can stack wrt axis 2 by first transposing, then RowStack, then transpose back.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Jul 15, 2016 at 7:23 AM +0200, "Zp Bappi" <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh yes. I forgot to mention that I was using BrainScript and latest codebase from the master branch. I am not quite sure about NDL support. It is currently marked as deprecated though.

-

**Comment by pinzhang10** [comment]
I can not use the function is CNTK.core.bs file. It says Undefined function or macro 'Splice'

I cloned the CNTK code yesterday and compiled by myself.

Does anybody know why?

**Comment by pinzhang10** [comment]
Does anybody know how to do the tranpose in NDL?  When I was using ArrayTransposeDimensions, it was saying  EXCEPTION occurred: Undefined function or macro 'ArrayTransposeDimensions' in ArrayTransposeDimensions(inp1, 1, 3).

The same for TransposeDimensions.

Please help!

**Comment by frankseide** [comment]
@pinzhang10, use BrainScriptNetworkBuilder, please see Issue #576 .
