### ISSUE TITLE
Locating the cat;s eyes

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#681]
OK, so lets say I have ResNet or some similar network that is doing classification, and it finds that a given eval image is a "cat" with 99% probability.  Now, I want to also find two points in the image that correspond to the center of the cat's eyes.   How can I do that?   Its like I want 4 real outputs ( the x and y coordinates of each eye ) -- or if we do it only to pixel accuracy it could be 4 integers.  I would train on tons of images in which I've already accurately located the cat's eyes.   Of course, it could be a network separate from the classification task - once we find its a cat, then we run the second network on it to locate the eyes.  Can someone suggests what type of network could do this?  Are there examples around of something similar?  Published papers?  Thanks!

**Comment by mfuntowicz** [comment]
Hi John, 

It seems that the task you're trying to accomplish is very similar to ImageNet Object Localization : 
http://www.image-net.org/challenges/LSVRC/2015/#loc

Usually it's another CNN with a regression task and 4 output (x, y, width, height), which gives you a bounding box.

ImageNet provides a dataset with bounding box in order to start :)
Morgan

**Comment by wolfma61** [comment]
There are object detection samples in the CNTK2.0 release, this is also the topic of ongoing work in CNTK
