### ISSUE TITLE
Exception: Could not open ./train_map.txt for reading

### ISSUE THREAD

**Issue by devinbostIL** [Microsoft/CNTK#690]
Hi,

I'm getting the same error when trying to run some of the cntk files in ../cntk/Examples/Image/Miscellaneous/ImageNet/VGG
 and 
../cntk/Examples/Image/Miscellaneous/ImageNet/AlexNet
and 
../cntk/Examples/Image/Miscellaneous/ImageNet/ResNet

The exception states:

> Could not open ./train_map.txt for reading.

I have attached the log files.
[ResNet_18_Train_CreateEval_Test.txt](https://github.com/Microsoft/CNTK/files/370396/ResNet_18_Train_CreateEval_Test.txt)
[VGG_A_Train_AddTop5Eval_Test.txt](https://github.com/Microsoft/CNTK/files/370395/VGG_A_Train_AddTop5Eval_Test.txt)
[AlexNet_Train_AddTop5Eval_Test.txt](https://github.com/Microsoft/CNTK/files/370401/AlexNet_Train_AddTop5Eval_Test.txt)

This may or may not be related to the other issues that I've reported here: [Error opening file exception when running CPPEvalClient.exe and similar issues with CSEvalClient and failing unit tests](https://github.com/Microsoft/CNTK/issues/670)

and here: [Missing AN4Corpus directory (and iVector) after switching to Intel MKL / pulling latest](https://github.com/Microsoft/CNTK/issues/689)

**Comment by KolyaIvankov** [comment]
Hi! Did You figure out what was the problem after all, or did it just disappear? Having the same issue when trying to run [Simple Regression for CIFAR10](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Regression), so a noob-friendly explanation would have been very welcome.

**Comment by cha-zhang** [comment]
I tested and there is no issue with it. Have you installed CIFAR10 by running https://github.com/Microsoft/CNTK/blob/master/Examples/Image/DataSets/CIFAR-10/install_cifar10.py? Did you change the data path?

**Comment by KolyaIvankov** [comment]
Hi ChaZhang,

Thanks a lot! Indeed this was the case, just got through it several hours before seeing you comment.

As I've said, this was a noob question. Downloading CIFAR-10 to the ...\cntk\Examples\Image\DataSets\CIFAR-10 folder solved the problem.

So, for the people like me, I just leave this comment. Perhaps the problem is, that in the train_map.txt file (probably only when you install CNTK script-wise) the image paths age given in the form

c:\local\cntk\Examples\Image\DataSets\CIFAR-10\train\00000.png

i.e. with the full path and not something like 

...\train\00000.png

so that you really need the CIFAR-10 Database to be stored there (and not, say, somewhere near your project folder as it was in my case).
