### ISSUE TITLE
Big performance difference between the executable (cntk.exe) and C# EvalWrapper class

### ISSUE THREAD

**Issue by huy302** [Microsoft/CNTK#706]
I'm using the same network model, feeding the same set of samples to evaluate the output on the same machine
deviceId is set to -1 to use CPU on both tests since EvalWrapper doesn't support GPU yet
Result: cntk.exe can process around ~4350 samples/sec while EvalWrapper speed is at ~1100 samples/sec

Maybe because I was feeding samples to EvalWrapper one at a time, however, according to #589, seems like batch input is not supported yet

I just wonder if there is some trick to make EvalWrapper faster

Thanks
--
Huy

**Comment by gaizkan** [comment]
Hi,

EvalWrapper is slower than CNTK.exe for several reasons (amongs them because there is a penalty going from C# to C++ for each evaluation). Additionally CNTK.exe has internally other performance improvements (e.g. readers) that EvalWrapper doesn't have.

However, one way to make EvalWrapper perform faster is by using multiple models in the same process (refer to [this](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluate-Multiple-Models) example).

With future versions of the EvalWrapper, there will be many performance enhancements. We are currently working on this. The performance disparity between EvalWrapper and CNTK.exe will reduce greatly as the improvements are implemented.

Thanks,
Gaizka

**Comment by huy302** [comment]
Hi Gaizka,

I suspect the same thing as well. Thanks for the clarification.
Can't wait for the improvement :)

Regards
