### ISSUE TITLE
What action can be used for prediction?

### ISSUE THREAD

**Issue by proteushf** [Microsoft/CNTK#707]
After training, a model xxx.dnn can be generated. Assuming I have a new dataset to be predicted, can I use a config file to run prediction? If so, what action can be use in the config file? Thanks.

**Comment by PeterGriffioen** [comment]
I will be approaching this issue eventually but I've been on leave for month and saw this back then. I'm surprised it hasn't been answered.  While I'm a complete NOOB in this area and I'm currently just using the published binaries, I'm expecting that I'll be writing a dummy CNTK file that will load the previously created model and run the new data through it at a test file. I'll then read the data out of the results of that. This may be a slow method but my apps are not time critical. 

As I dive into compiling the code myself, and if I haven't found a better existing way, I plan an on adapting  the code to do this more efficiently. It seems that most using CNTK are involved with proof of concept research projects rather than throughput production as these type of considerations are given very little documentation priority.

**Comment by frankseide** [comment]
Could you clarify: Do you want to run prediction from file to file, or inside your own program from a vector in a program into a vector in RAM?

For the former, we have the "write" action; for the latter the EvalDLL.

**Comment by PeterGriffioen** [comment]
Thanks Frankseide. I would like eventually to pass across vectors in RAM as I will have millions of them to evaluate. However I have read elsewhere on the issues discussion that EvalDLL only handles one vector at a time using dictionaries (I believe). For me this represents a single pixel of my output (sat images + other sources -> land classification map). Thus I thought in my case it may be better to use the write action with files such that I can process say 24000 vectors at once, which will be a single row of my image output and repeat this say 32000 times. Not quick! I currently do this with my Random Forests generated by Clus and  and NNets from Statistica. Currently the computations are distributed across about 120 cores on various PCs/VMs. I usually make a few thousand species distribution maps a year at the same resolution using the same methods.
