### ISSUE TITLE
Stopping Criterion

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#727]
When autoadjust is used in config file, it looks like early stopping criterion is to check if current learning rate is less than m_minLearnRate which is hard coded with 9.99..e-10. Therefore, we need to recompile CNTK to change m_minLearnRate value. 

I'm wondering if there is any parameter we can control early stopping except recompiling of CNTK?

**Comment by frankseide** [comment]
There should be. @dongyu888, could you comment?

**Comment by dongyu888** [comment]
we don't have it now but can be easily added. i am out of office, but can add it next week if you don't plan to add it by yourself.

<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: funguy74 <notifications@github.com> </div><div>Date: 7/29/16  14:20  (GMT-08:00) </div><div>To: Microsoft/CNTK <CNTK@noreply.github.com> </div><div>Subject: [Microsoft/CNTK] Stopping Criterion (#727) </div><div>
</div>
When autoadjust is used in config file, it looks like early stopping criterion is to check if current learning rate is less than m_minLearnRate which is hard coded with 9.99..e-10. Therefore, we need to recompile CNTK to change m_minLearnRate value.

I'm wondering if there is any parameter we can control early stopping except recompiling of CNTK?

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Microsoft/CNTK/issues/727

**Comment by funguy74** [comment]
It would be great if you can update it. Thanks a lot!

**Comment by dongyu888** [comment]
in the master now. minLearningRatePerSample is the config in the SGD block to control it.

**Comment by funguy74** [comment]
Thanks a lot!
