### ISSUE TITLE
Hands on labs

### ISSUE THREAD

**Issue by jotarun** [Microsoft/CNTK#764]
In https://github.com/Microsoft/CNTK/wiki/Hands-On-Labs-Image-Recognition
why are all the config file contains { } ? 
Haven't seen this syntax before.

In fact, cntk 1.6 gives the exception: 
EXCEPTION occurred: BrainScript network description must be either a BS expression in ( ) or a config record in [ ]

is this the newest syntax to be supported in the future?

**Comment by frankseide** [comment]
Yes, we have switched to { }, because it is more similar to other languages. This is recognized in the latest master, and the binaries for the KDD tutorial that this was prepared for. The instruction page has download instructions for an intermediate binary build that handles this already: https://github.com/Microsoft/CNTK/wiki/KDD-2016-Tutorial.
