### ISSUE TITLE
How does fixed attention hook function work?

### ISSUE THREAD

**Issue by RafaelDrumond** [Microsoft/CNTK#767]
Hi I was checking some of the example from sequence to sequence, and then I found this function:

BS.Seq2Seq.CreateAugmentWithFixedWindowAttentionHook (attentionDim, attentionSpan, decoderDynamicAxis, encoderOutput, enableSelfStabilization=false)

The documentation don't say much about it. Can someone help me  understand what is it for or how does it work?

**Comment by frankseide** [comment]
CNTK has very good handling of sequences. But it has one shortcoming currently, you can only loop over one dimension at a time. For attention, that does not work, you need two loops. So the second loop is simulated by statically unrolling the data.

What it does is that it uses a fixed-length delay line (of length `attentionSpan`). This delay line will remember the last `attentionSpan` outputs of the encoder. It will also create a mask.

`CreateAugmentWithFixedWindowAttentionHook()` will create a BrainScript lambda that you can pass to the recurrent-LSTM functions. That BrainScript lambda will take the decoder's hidden state at a given time step, and know the encoder's hidden state since you passed it in, and then compute the weighted average of the up to `attentionSpan` input hidden states according to the attention formula for the given time step. The recurrent-LSTM function will call this lambda, passing a decoder's hidden state, get back the attention-interpolated encoder's hiden state, and treat it as another data input to the LSTM.

You can look at the source code in this file: https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs, which is also located next to the CNTK executable.

**Comment by RafaelDrumond** [comment]
Thanks Frank!
