### ISSUE TITLE
Exception in running train_cntk2.sh

### ISSUE THREAD

**Issue by housebaby** [Microsoft/CNTK#816]
When runing train_cntk2.sh in Speech example using my own speech data, exception occurs with following log :
.........................................................
reading script file exp_cntk//cntk_train.counts ... 3255057 entries
total 6434 state names in state list exp_cntk//cntk_label.mapping
htkmlfreader: reading MLF file exp_cntk//cntk_train.labels ...ali-to-pdf exp/tri3b_ali/final.mdl 'ark:gunzip -c exp/tri3b_ali/ali._.gz |' ark:- 
LOG (ali-to-pdf:main():ali-to-pdf.cc:68) Converted 3409897 alignments to pdf sequences.
LOG (ali-to-post:main():ali-to-post.cc:65) Converted 3409897 alignments.
 total 3409897 entries
*_EXCEPTION occurred: parsedpath: malformed path '20090626-'**

I checked my feature script that "exp_cntk/cntk_train.feats" redirecting to. It includes following utterance ID. 
200900626-国内简讯-00000-01271 /data/username/cntk/Examples/Speech/CHN/fbank/train/raw_fbank_train.1.ark:997487301

Is it because the script file doesn't support Chinese character , or doesn't support special  punctuation like "-".Can any one explain it ?Thanks so much.

**Comment by frankseide** [comment]
I am a little surprised. This is GB2312, right? GB2312 has the same encoding as ASCII for any character that is parsed in the SCP-file line.

One possibility I see is that CNTK treats the SCP file as a UTF-8 file, and internally converts it to a Unicode string. That conversion might be flagging an invalid UTF-8 character (since the fileis GB2312).

Would you mind trying to convert your SCP file to UTF-8? And then let me know whether that solves the problem?

**Comment by cha-zhang** [comment]
I'm closing this since it's been very old. Please feel free to open a new issue if needed.
