### ISSUE TITLE
CMVN at hidden layer

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#894]
Hi
Is there a method to do CMVN normalization at specific hidden layer of FF-DNN?
I train a network which it's middle hidden layer is tanh, and I want to do CMVN on it's output. I think I'll achieve this by means of

`MeanVarNorm(x)
{
    xMean = Mean(x)
    xStdDev = InvStdDev(x)
    xNorm=PerDimMeanVarNormalization(x,xMean,xStdDev)
}`

but I encountered an exception as bellow:

> EXCEPTION occurred: PerDimMeanVarNormalizationNode should only be called in the evaluation stage. Is any of its descendents a learnable parameter that requires gradient?

Do I use wrong function? If not (that I think the function is OK) how can I do CMVN normalization for the output of middle hidden layer of my network?

**Comment by e-thereal** [comment]
Have you tried BatchNormalization yet? It performs some kind of normalization similar to the  MeanVarNorm layers but for a mini-batch instead of the entire data set, which allows it to be applied to the hidden units as well. (https://github.com/Microsoft/CNTK/wiki/Layers-Reference#batchnormalizationlayer-layernormalizationlayer-stabilizerlayer)

**Comment by n17s** [comment]
BatchNormalization is what you need.
