### ISSUE TITLE
 Is it easy to make loss values of some input samples to zeros in CNTK？

### ISSUE THREAD

**Issue by jingyonghou** [Microsoft/CNTK#895]
Is it easy to make loss values of some input samples to zeros in CNTK？It is some times useful in some sequence embedding task. In some other toolkits, another input matrix so called "class_weight" or "sample_weight" is used to do this and can be specified by user.

**Comment by n17s** [comment]
Yes. Let z is the output of your network, y be the label and w be the weight. Then you can define your loss as 
(Brainscript) 
weighted_cross_entropy = TransposeTimes(w.*y, log(softmax(z))) 
(Python)
weighted_cross_entropy = times_transpose(transpose(log(softmax(z))), transpose(w*y))

You will probably want to use the CNTK text format reader so that you can have a stream |w with the weights for each example.
