### ISSUE TITLE
Windows binaries are not signed -> 'The publisher could not be verified' warning

### ISSUE THREAD

**Issue by jakrivan** [Microsoft/CNTK#898]
CNTK binaries are not signed, so when one downloads the package onto the NTFS file system and then tries to execute from within different executable the CNTK execution is blocked with 'The publisher could not be verified. Are you sure you want to run this software?' warning.

![image](https://cloud.githubusercontent.com/assets/3809076/19192646/35cdc188-8ca7-11e6-85a8-2ac001e283e0.png)

Which needs manual intervention. This can be problem for automated runs (especially if running as a service within session0).

Workaround: removing the metadata - e.g. from explorer:

![image](https://cloud.githubusercontent.com/assets/3809076/19192705/6904b32c-8ca7-11e6-9bfa-1f78ec32c439.png)

Expected behavior: CNTK binaries are signed and so this situation would not occur.

**Comment by JohnCraigPublic** [comment]
What's your point?  And why mention "NTFS file system" ?

**Comment by jakrivan** [comment]
> What's your point?
MSFT product should run flawlessly on MSFT OS and should be identifiable as product from MSFT.
Instead it appears as product from 'unknown publisher' and, under some circumstances, needs manual interventions, even if attempted to run in unattended automations.

> And why mention "NTFS file system" ?
This is triggered by NTFS ADS feature (more reading e.g. here: https://blogs.technet.microsoft.com/askcore/2013/03/24/alternate-data-streams-in-ntfs/).

**Comment by mahilleb-msft** [comment]
Binary drop installation does it's own unblocking since a couple versions back.
I.e., if you follow https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Binary-Script unblocking should not be required today anymore (in the past, a separate "unblocking" steps, as you note it, was part of the documentation). Please note that currently, only our Nuget packages for evaluation are digitally signed.
