### ISSUE TITLE
audio reader?

### ISSUE THREAD

**Issue by arijit17** [Microsoft/CNTK#931]
Hi all:

I'm interested in feeding in audio wav files into CNTK and do some audio analysis. 
I understand that I should use one of the readers: https://github.com/Microsoft/CNTK/tree/master/Source/Readers but, which one? :-)

Is there already some speech/audio analysis code (e.g. FFT, etc) available somewhere in the CNTK repository?

Best Regards,
Arijit

**Comment by hajix** [comment]
Hi

As you mentioned above, there is no way to feed raw audio files to CNTK. However previous attempts, in order to learn from raw waveform, was not so promising.

By the way, a simple way (specially when your data is not so much), to feed raw waveform to CNTK, is to write them in such format which is readable by CNTKTextFormatReader.

I strongly recommend you to do feature extraction by HTK and feed it to your network using HTKMLFReader.

**Comment by jingyonghou** [comment]
CNTK provided HTKMLFReader and also KaldiReader, you may use HTK or Kaldi to process you wav file first and then use CNTK to do your own task.

**Comment by arijit17** [comment]
OK, thanks for the information.
