### ISSUE TITLE
COCO dataset for object detection

### ISSUE THREAD

**Issue by championoaks** [Microsoft/CNTK#941]
Has anybody trained (Resnet) topology within CNTK using COCO dataset for object detection? Would appreciate any pointers on how to do that.

Should we start with the imagenet pretrained models?

**Comment by cha-zhang** [comment]
Currently we only have Pascal VOC dataset working (partially) for object detection (https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FastRCNN). We are in the process of retraining some of our Resnet models in order to better match the original paper. We will look into COCO once we are done with Pascal VOC.
