### ISSUE TITLE
After Anaconda install, error that cntk wheel is not supported

### ISSUE THREAD

**Issue by edrozenberg** [Microsoft/CNTK#956]
Followed all the instructions to get Anaconda set up and activated. For some reason `python --version` shows 3.5, even though the Anaconda instructions should have created a 3.4 environment. Guessing the wheel error is because the active env is 3.5 and the wheel is built for 3.4.

```
(cntk-py34) [me@myserver /usr/local/src/ms-cntk/cntk]$ python --version
Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
(cntk-py34) [me@myserver /usr/local/src/ms-cntk/cntk]$ pip install --upgrade ../cntk/cntk/python/cntk-2.0.beta1.0-cp34-cp34m-linux_x86_64.whl 
cntk-2.0.beta1.0-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.
```

**Comment by mahilleb-msft** [comment]
Hi Ed, you're correct. Currently we only build for Python 3.4 but other Python versions will be supported out of the box soon. Make sure you activate a CNTK-py34 before trying to install the wheel. From #955 I gather you've set up an Python 3.4 environment. Can you try the pip install in there?

Best, Mark

P.S.: if you build from source, you can already build Python 3.5 packages on Linux today, by using "configure --with-py35-path=<dir>" to point the configure script to your Python 3.5 environment [so that <dir>/bin/python exists].

**Comment by wolfma61** [comment]
Leave a comment

**Comment by wolfma61** [comment]
I assume this is closed .
