### ISSUE TITLE
CNTK 2.0 is not available on Azure Data Science Virtual Machine

### ISSUE THREAD

**Issue by xumx** [Microsoft/CNTK#983]
Can't install with the Linux instructions either.

**Comment by sayanpa** [comment]
Azure Data Science VMs are currently rolling out CNTK2.0 AFAIK.  I have installed on Az VM CNTK 2.0 and as well as local Linux box. Can you please elaborate what problems you are running into? Did you use the install scripts?

**Comment by tuzzer** [comment]
Not sure if this is the same problem you had. I followed these instructions: https://github.com/Microsoft/CNTK/wiki/Setup-Linux-Binary-Manual and it seemed to work until Step 5. It tells us to run this: `source "/home/username/cntk/activate-cntk"` but I don't have a file named "activate-cntk". 
I recalled that this files was created when I ran the `./install-cntk.sh` when I was following the [Linux binary installation with scripts](https://github.com/Microsoft/CNTK/wiki/Setup-Linux-Binary-Script#linux-binary-installation-with-scripts) on my Ubuntu machine. This can't run on the Azure DSVM since it's not Ubuntu, but I realized that you can just delete all the unnecessary part and keep only the parts that actually generate the "activate-cntk" script like this: https://gist.github.com/tuzzer/b78d808b90645e6c532ec99a7946f862
Run that and you can then run `source "......./cntk/activate-cntk`.
Then CNTK should work.

**Comment by xumx** [comment]
@sayanpa The current Linux DSVM on Azure seems to use an older version of CNTK

I've provisioned a new VM today, and here is what shows when I run `cntk` command.
`
Build info:                                                                                                                         
                                                                                                                                    
                Built time: Jun  6 2016 20:06:59                                                                                    
                Last modified date: Sun Jun  5 04:28:32 2016                                                                        
                Build type: release                                                                                                 
                Build target: CPU-only                                                                                              
                With 1bit-SGD: no                                                                                                   
                Math lib: acml                                                                                                      
                Build Branch: HEAD                                                                                                  
                Build SHA1: b7ed8dc9e5cd8ab35f4badae86dd42e93e9f2564                                                                
                Built by philly on 3177047f4067                                                                                     
                Build Path: /home/philly/jenkins/workspace/CNTK-Build-Linux  
`

CNTK v2.0 Linux install script can't run on the Azure DSVM since it's not Ubuntu.

**Comment by sayanpa** [comment]
Adding a few folks from our group.


_____________________________

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
